-- -------------------------------------------------------------
-- 
-- File Name: SEL_Reverted\hdlsrc\SEL_test\SEL_toTest_src_LPF.vhd
-- Created: 2026-07-27 16:14:57
-- 
-- Generated by MATLAB 26.1, HDL Coder 26.1, and Simulink 26.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: SEL_toTest_src_LPF
-- Source Path: SEL_test/TESTBENCH/SEL/SEL_WRAPPED/DSP_LOGIC/LPF
-- Hierarchy Level: 3
-- Model version: 1.616
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY SEL_toTest_src_LPF IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        I                                 :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En17
        Q                                 :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En17
        valid                             :   IN    std_logic;
        I_filtered                        :   OUT   std_logic_vector(24 DOWNTO 0);  -- sfix25_En23
        Q_filtered                        :   OUT   std_logic_vector(24 DOWNTO 0);  -- sfix25_En23
        valid_o                           :   OUT   std_logic
        );
END SEL_toTest_src_LPF;


ARCHITECTURE rtl OF SEL_toTest_src_LPF IS

  -- Component Declarations
  COMPONENT SEL_toTest_src_Biquad_Filter
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          dataIn                          :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En17
          validIn                         :   IN    std_logic;
          dataOut                         :   OUT   std_logic_vector(24 DOWNTO 0);  -- sfix25_En23
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT SEL_toTest_src_Biquad_Filter1
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          dataIn                          :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En17
          validIn                         :   IN    std_logic;
          dataOut                         :   OUT   std_logic_vector(24 DOWNTO 0)  -- sfix25_En23
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : SEL_toTest_src_Biquad_Filter
    USE ENTITY work.SEL_toTest_src_Biquad_Filter(rtl);

  FOR ALL : SEL_toTest_src_Biquad_Filter1
    USE ENTITY work.SEL_toTest_src_Biquad_Filter1(rtl);

  -- Signals
  SIGNAL I_signed                         : signed(17 DOWNTO 0);  -- sfix18_En17
  SIGNAL I_1                              : signed(17 DOWNTO 0);  -- sfix18_En17
  SIGNAL rd_1_reg                         : std_logic_vector(4 DOWNTO 0);  -- ufix1 [5]
  SIGNAL valid_1                          : std_logic;
  SIGNAL I_filtered_1                     : std_logic_vector(24 DOWNTO 0);  -- ufix25
  SIGNAL Biquad_Filter_out2               : std_logic;
  SIGNAL I_filtered_signed                : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL Gain_cast                        : signed(49 DOWNTO 0);  -- sfix50_En45
  SIGNAL Gain_out1                        : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL Q_signed                         : signed(17 DOWNTO 0);  -- sfix18_En17
  SIGNAL Q_1                              : signed(17 DOWNTO 0);  -- sfix18_En17
  SIGNAL rd_3_reg                         : std_logic_vector(1 DOWNTO 0);  -- ufix1 [2]
  SIGNAL valid_2                          : std_logic;
  SIGNAL Q_filtered_1                     : std_logic_vector(24 DOWNTO 0);  -- ufix25
  SIGNAL Q_filtered_signed                : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL Gain2_cast                       : signed(49 DOWNTO 0);  -- sfix50_En45
  SIGNAL Gain2_out1                       : signed(24 DOWNTO 0);  -- sfix25_En23

BEGIN
  u_Biquad_Filter : SEL_toTest_src_Biquad_Filter
    PORT MAP( clk => clk,
              reset => reset,
              dataIn => std_logic_vector(I_1),  -- sfix18_En17
              validIn => valid_1,
              dataOut => I_filtered_1,  -- sfix25_En23
              validOut => Biquad_Filter_out2
              );

  u_Biquad_Filter1 : SEL_toTest_src_Biquad_Filter1
    PORT MAP( clk => clk,
              reset => reset,
              dataIn => std_logic_vector(Q_1),  -- sfix18_En17
              validIn => valid_2,
              dataOut => Q_filtered_1  -- sfix25_En23
              );

  I_signed <= signed(I);

  rd_0_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        I_1 <= to_signed(16#00000#, 18);
      ELSE 
        I_1 <= I_signed;
      END IF;
    END IF;
  END PROCESS rd_0_process;


  rd_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        rd_1_reg <= (OTHERS => '0');
      ELSE 
        rd_1_reg(0) <= valid;
        rd_1_reg(4 DOWNTO 1) <= rd_1_reg(3 DOWNTO 0);
      END IF;
    END IF;
  END PROCESS rd_1_process;

  valid_1 <= rd_1_reg(4);

  I_filtered_signed <= signed(I_filtered_1);

  Gain_cast <= resize(I_filtered_signed & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 50);
  
  Gain_out1 <= "0111111111111111111111111" WHEN ((Gain_cast(49) = '0') AND (Gain_cast(48 DOWNTO 46) /= "000")) OR ((Gain_cast(49) = '0') AND (Gain_cast(46 DOWNTO 22) = "0111111111111111111111111")) ELSE
      "1000000000000000000000000" WHEN (Gain_cast(49) = '1') AND (Gain_cast(48 DOWNTO 46) /= "111") ELSE
      Gain_cast(46 DOWNTO 22) + ('0' & Gain_cast(21));

  I_filtered <= std_logic_vector(Gain_out1);

  Q_signed <= signed(Q);

  rd_2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Q_1 <= to_signed(16#00000#, 18);
      ELSE 
        Q_1 <= Q_signed;
      END IF;
    END IF;
  END PROCESS rd_2_process;


  rd_3_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        rd_3_reg <= (OTHERS => '0');
      ELSE 
        rd_3_reg(0) <= valid_1;
        rd_3_reg(1) <= rd_3_reg(0);
      END IF;
    END IF;
  END PROCESS rd_3_process;

  valid_2 <= rd_3_reg(1);

  Q_filtered_signed <= signed(Q_filtered_1);

  Gain2_cast <= resize(Q_filtered_signed & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 50);
  
  Gain2_out1 <= "0111111111111111111111111" WHEN ((Gain2_cast(49) = '0') AND (Gain2_cast(48 DOWNTO 46) /= "000")) OR ((Gain2_cast(49) = '0') AND (Gain2_cast(46 DOWNTO 22) = "0111111111111111111111111")) ELSE
      "1000000000000000000000000" WHEN (Gain2_cast(49) = '1') AND (Gain2_cast(48 DOWNTO 46) /= "111") ELSE
      Gain2_cast(46 DOWNTO 22) + ('0' & Gain2_cast(21));

  Q_filtered <= std_logic_vector(Gain2_out1);

  valid_o <= Biquad_Filter_out2;

END rtl;

