-- -------------------------------------------------------------
-- 
-- File Name: SEL_Reverted\hdlsrc\SEL_test\SEL_toTest_src_MATLAB_Function.vhd
-- Created: 2026-07-27 16:14:58
-- 
-- Generated by MATLAB 26.1, HDL Coder 26.1, and Simulink 26.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: SEL_toTest_src_MATLAB_Function
-- Source Path: SEL_test/TESTBENCH/SEL/SEL_WRAPPED/DSP_LOGIC/NORMALIZE/SCALE_FACTOR/rSqrt/MATLAB Function
-- Hierarchy Level: 6
-- Model version: 1.616
-- 
-- #codegen
-- x_in is ufix28_en27 (28 bits total, 27 fractional bits)
--   Bit 28: 2^0 = 1.0 (Full Scale Power)
--   Bits 27..1: 2^-1 down to 2^-27
-- 1. Extract raw 28-bit integer into a 32-bit container
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.SEL_toTest_src_SEL_pkg.ALL;

ENTITY SEL_toTest_src_MATLAB_Function IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        x_in                              :   IN    std_logic_vector(27 DOWNTO 0);  -- ufix28_En27
        lut_addr_12bit                    :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
        m                                 :   OUT   std_logic_vector(15 DOWNTO 0)  -- uint16
        );
END SEL_toTest_src_MATLAB_Function;


ARCHITECTURE rtl OF SEL_toTest_src_MATLAB_Function IS

  -- Signals
  SIGNAL x_in_unsigned                    : unsigned(27 DOWNTO 0);  -- ufix28_En27
  SIGNAL x_in_1                           : unsigned(27 DOWNTO 0);  -- ufix28_En27
  SIGNAL x_int                            : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL out0                             : std_logic;  -- ufix1
  SIGNAL out0_1                           : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL out0_2                           : std_logic;
  SIGNAL out0_3                           : std_logic;  -- ufix1
  SIGNAL out0_4                           : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL out0_5                           : std_logic;
  SIGNAL out0_6                           : std_logic;  -- ufix1
  SIGNAL out0_7                           : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL out0_8                           : std_logic;
  SIGNAL out0_9                           : std_logic;  -- ufix1
  SIGNAL out0_10                          : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL out0_11                          : std_logic;
  SIGNAL out0_12                          : std_logic;  -- ufix1
  SIGNAL out0_13                          : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL out0_14                          : std_logic;
  SIGNAL out0_15                          : std_logic;  -- ufix1
  SIGNAL out0_16                          : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL out0_17                          : std_logic;
  SIGNAL out0_18                          : std_logic;  -- ufix1
  SIGNAL out0_19                          : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL out0_20                          : std_logic;
  SIGNAL out0_21                          : std_logic;  -- ufix1
  SIGNAL out0_22                          : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL out0_23                          : std_logic;
  SIGNAL out0_24                          : std_logic;  -- ufix1
  SIGNAL out0_25                          : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL out0_26                          : std_logic;
  SIGNAL out0_27                          : std_logic;  -- ufix1
  SIGNAL out0_28                          : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL out0_29                          : std_logic;
  SIGNAL rd_10_reg                        : std_logic_vector(1 DOWNTO 0);  -- ufix1 [2]
  SIGNAL out0_30                          : std_logic;
  SIGNAL out0_31                          : std_logic;  -- ufix1
  SIGNAL out0_32                          : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL out0_33                          : std_logic;
  SIGNAL out0_34                          : std_logic;  -- ufix1
  SIGNAL out0_35                          : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL out0_36                          : std_logic;
  SIGNAL out0_37                          : std_logic;  -- ufix1
  SIGNAL out0_38                          : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL out0_39                          : std_logic;
  SIGNAL out0_40                          : std_logic;  -- ufix1
  SIGNAL out0_41                          : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL out0_42                          : std_logic;
  SIGNAL out0_43                          : std_logic;  -- ufix1
  SIGNAL out0_44                          : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL out0_45                          : std_logic;
  SIGNAL out0_46                          : std_logic;  -- ufix1
  SIGNAL out0_47                          : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL out0_48                          : std_logic;
  SIGNAL out0_49                          : std_logic;  -- ufix1
  SIGNAL out0_50                          : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL out0_51                          : std_logic;
  SIGNAL out0_52                          : std_logic;  -- ufix1
  SIGNAL out0_53                          : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL out0_54                          : std_logic;
  SIGNAL out0_55                          : std_logic;  -- ufix1
  SIGNAL out0_56                          : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL out0_57                          : std_logic;
  SIGNAL out0_58                          : std_logic;  -- ufix1
  SIGNAL out0_59                          : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL out0_60                          : std_logic;
  SIGNAL out0_61                          : std_logic;
  SIGNAL out0_62                          : std_logic;  -- ufix1
  SIGNAL out0_63                          : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL out0_64                          : std_logic;
  SIGNAL out0_65                          : std_logic;  -- ufix1
  SIGNAL out0_66                          : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL out0_67                          : std_logic;
  SIGNAL k                                : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL out0_68                          : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL out0_69                          : std_logic;  -- ufix1
  SIGNAL out0_70                          : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL out0_71                          : std_logic;
  SIGNAL k_1                              : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL out0_72                          : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL out0_73                          : std_logic;  -- ufix1
  SIGNAL out0_74                          : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL out0_75                          : std_logic;
  SIGNAL k_2                              : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL out0_76                          : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL out0_77                          : std_logic;  -- ufix1
  SIGNAL out0_78                          : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL out0_79                          : std_logic;
  SIGNAL k_3                              : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL out0_80                          : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL out0_81                          : std_logic;  -- ufix1
  SIGNAL out0_82                          : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL out0_83                          : std_logic;
  SIGNAL k_4                              : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL out0_84                          : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL out0_85                          : std_logic;  -- ufix1
  SIGNAL out0_86                          : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL out0_87                          : std_logic;
  SIGNAL k_5                              : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL out0_88                          : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL out0_89                          : std_logic;  -- ufix1
  SIGNAL out0_90                          : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL out0_91                          : std_logic;
  SIGNAL k_6                              : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL out0_92                          : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL k_7                              : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL out0_93                          : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL out0_94                          : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL out0_95                          : std_logic;
  SIGNAL k_8                              : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL out0_96                          : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL out0_97                          : std_logic;
  SIGNAL k_9                              : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL out0_98                          : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL out0_99                          : std_logic;
  SIGNAL k_10                             : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL out0_100                         : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL out0_101                         : std_logic;
  SIGNAL k_11                             : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL out0_102                         : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL out0_103                         : std_logic;
  SIGNAL k_12                             : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL out0_104                         : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL out0_105                         : std_logic;
  SIGNAL k_13                             : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL out0_106                         : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL out0_107                         : std_logic;
  SIGNAL k_14                             : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL out0_108                         : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL out0_109                         : std_logic;
  SIGNAL k_15                             : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL out0_110                         : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL out0_111                         : std_logic;
  SIGNAL k_16                             : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL out0_112                         : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL k_17                             : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL out0_113                         : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL out0_114                         : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL rd_9_reg                         : std_logic_vector(1 DOWNTO 0);  -- ufix1 [2]
  SIGNAL out0_115                         : std_logic;
  SIGNAL k_18                             : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL out0_116                         : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL rd_8_reg                         : std_logic_vector(1 DOWNTO 0);  -- ufix1 [2]
  SIGNAL out0_117                         : std_logic;
  SIGNAL k_19                             : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL out0_118                         : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL rd_7_reg                         : std_logic_vector(1 DOWNTO 0);  -- ufix1 [2]
  SIGNAL out0_119                         : std_logic;
  SIGNAL k_20                             : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL out0_120                         : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL rd_6_reg                         : std_logic_vector(1 DOWNTO 0);  -- ufix1 [2]
  SIGNAL out0_121                         : std_logic;
  SIGNAL k_21                             : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL out0_122                         : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL rd_5_reg                         : std_logic_vector(1 DOWNTO 0);  -- ufix1 [2]
  SIGNAL out0_123                         : std_logic;
  SIGNAL k_22                             : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL out0_124                         : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL rd_4_reg                         : std_logic_vector(1 DOWNTO 0);  -- ufix1 [2]
  SIGNAL out0_125                         : std_logic;
  SIGNAL k_23                             : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL out0_126                         : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL rd_3_reg                         : std_logic_vector(1 DOWNTO 0);  -- ufix1 [2]
  SIGNAL out0_127                         : std_logic;
  SIGNAL k_24                             : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL out0_128                         : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL rd_2_reg                         : std_logic_vector(1 DOWNTO 0);  -- ufix1 [2]
  SIGNAL out0_129                         : std_logic;
  SIGNAL k_25                             : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL out0_130                         : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL rd_1_reg                         : std_logic_vector(1 DOWNTO 0);  -- ufix1 [2]
  SIGNAL out0_131                         : std_logic;
  SIGNAL k_26                             : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL out0_132                         : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL k_27                             : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL k_28                             : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL k_29                             : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL const_expression                 : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL rd_24_reg                        : vector_of_unsigned32(0 TO 2);  -- ufix32 [3]
  SIGNAL x_int_1                          : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL x_norm                           : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL out0_133                         : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL out0_134                         : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL r                                : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL out0_135                         : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL const_expression_1               : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL frac_11bit                       : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL lut_addr_12bit_tmp               : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL m_tmp                            : unsigned(15 DOWNTO 0);  -- uint16

BEGIN
  x_in_unsigned <= unsigned(x_in);

  rd_0_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        x_in_1 <= to_unsigned(16#0000000#, 28);
      ELSE 
        x_in_1 <= x_in_unsigned;
      END IF;
    END IF;
  END PROCESS rd_0_process;


  x_int <= resize(x_in_1, 32);

  out0 <= x_int(27);

  out0_1 <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & out0;

  
  out0_2 <= '1' WHEN out0_1 = to_unsigned(1, 32) ELSE
      '0';

  out0_3 <= x_int(26);

  out0_4 <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & out0_3;

  
  out0_5 <= '1' WHEN out0_4 = to_unsigned(1, 32) ELSE
      '0';

  out0_6 <= x_int(25);

  out0_7 <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & out0_6;

  
  out0_8 <= '1' WHEN out0_7 = to_unsigned(1, 32) ELSE
      '0';

  out0_9 <= x_int(24);

  out0_10 <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & out0_9;

  
  out0_11 <= '1' WHEN out0_10 = to_unsigned(1, 32) ELSE
      '0';

  out0_12 <= x_int(23);

  out0_13 <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & out0_12;

  
  out0_14 <= '1' WHEN out0_13 = to_unsigned(1, 32) ELSE
      '0';

  out0_15 <= x_int(22);

  out0_16 <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & out0_15;

  
  out0_17 <= '1' WHEN out0_16 = to_unsigned(1, 32) ELSE
      '0';

  out0_18 <= x_int(21);

  out0_19 <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & out0_18;

  
  out0_20 <= '1' WHEN out0_19 = to_unsigned(1, 32) ELSE
      '0';

  out0_21 <= x_int(20);

  out0_22 <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & out0_21;

  
  out0_23 <= '1' WHEN out0_22 = to_unsigned(1, 32) ELSE
      '0';

  out0_24 <= x_int(19);

  out0_25 <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & out0_24;

  
  out0_26 <= '1' WHEN out0_25 = to_unsigned(1, 32) ELSE
      '0';

  out0_27 <= x_int(18);

  out0_28 <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & out0_27;

  
  out0_29 <= '1' WHEN out0_28 = to_unsigned(1, 32) ELSE
      '0';

  rd_10_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        rd_10_reg <= (OTHERS => '0');
      ELSE 
        rd_10_reg(0) <= out0_29;
        rd_10_reg(1) <= rd_10_reg(0);
      END IF;
    END IF;
  END PROCESS rd_10_process;

  out0_30 <= rd_10_reg(1);

  out0_31 <= x_int(17);

  out0_32 <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & out0_31;

  
  out0_33 <= '1' WHEN out0_32 = to_unsigned(1, 32) ELSE
      '0';

  out0_34 <= x_int(16);

  out0_35 <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & out0_34;

  
  out0_36 <= '1' WHEN out0_35 = to_unsigned(1, 32) ELSE
      '0';

  out0_37 <= x_int(15);

  out0_38 <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & out0_37;

  
  out0_39 <= '1' WHEN out0_38 = to_unsigned(1, 32) ELSE
      '0';

  out0_40 <= x_int(14);

  out0_41 <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & out0_40;

  
  out0_42 <= '1' WHEN out0_41 = to_unsigned(1, 32) ELSE
      '0';

  out0_43 <= x_int(13);

  out0_44 <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & out0_43;

  
  out0_45 <= '1' WHEN out0_44 = to_unsigned(1, 32) ELSE
      '0';

  out0_46 <= x_int(12);

  out0_47 <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & out0_46;

  
  out0_48 <= '1' WHEN out0_47 = to_unsigned(1, 32) ELSE
      '0';

  out0_49 <= x_int(11);

  out0_50 <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & out0_49;

  
  out0_51 <= '1' WHEN out0_50 = to_unsigned(1, 32) ELSE
      '0';

  out0_52 <= x_int(10);

  out0_53 <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & out0_52;

  
  out0_54 <= '1' WHEN out0_53 = to_unsigned(1, 32) ELSE
      '0';

  out0_55 <= x_int(9);

  out0_56 <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & out0_55;

  
  out0_57 <= '1' WHEN out0_56 = to_unsigned(1, 32) ELSE
      '0';

  out0_58 <= x_int(8);

  out0_59 <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & out0_58;

  
  out0_60 <= '1' WHEN out0_59 = to_unsigned(1, 32) ELSE
      '0';

  rd_20_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        out0_61 <= '0';
      ELSE 
        out0_61 <= out0_60;
      END IF;
    END IF;
  END PROCESS rd_20_process;


  out0_62 <= x_int(1);

  out0_63 <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & out0_62;

  
  out0_64 <= '1' WHEN out0_63 = to_unsigned(1, 32) ELSE
      '0';

  out0_65 <= x_int(0);

  out0_66 <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & out0_65;

  
  out0_67 <= '1' WHEN out0_66 = to_unsigned(1, 32) ELSE
      '0';

  k <= to_unsigned(16#001B#, 16);

  
  out0_68 <= k WHEN out0_67 = '0' ELSE
      k;

  out0_69 <= x_int(2);

  out0_70 <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & out0_69;

  
  out0_71 <= '1' WHEN out0_70 = to_unsigned(1, 32) ELSE
      '0';

  k_1 <= to_unsigned(16#001A#, 16);

  
  out0_72 <= out0_68 WHEN out0_64 = '0' ELSE
      k_1;

  out0_73 <= x_int(3);

  out0_74 <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & out0_73;

  
  out0_75 <= '1' WHEN out0_74 = to_unsigned(1, 32) ELSE
      '0';

  k_2 <= to_unsigned(16#0019#, 16);

  
  out0_76 <= out0_72 WHEN out0_71 = '0' ELSE
      k_2;

  out0_77 <= x_int(4);

  out0_78 <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & out0_77;

  
  out0_79 <= '1' WHEN out0_78 = to_unsigned(1, 32) ELSE
      '0';

  k_3 <= to_unsigned(16#0018#, 16);

  
  out0_80 <= out0_76 WHEN out0_75 = '0' ELSE
      k_3;

  out0_81 <= x_int(5);

  out0_82 <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & out0_81;

  
  out0_83 <= '1' WHEN out0_82 = to_unsigned(1, 32) ELSE
      '0';

  k_4 <= to_unsigned(16#0017#, 16);

  
  out0_84 <= out0_80 WHEN out0_79 = '0' ELSE
      k_4;

  out0_85 <= x_int(6);

  out0_86 <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & out0_85;

  
  out0_87 <= '1' WHEN out0_86 = to_unsigned(1, 32) ELSE
      '0';

  k_5 <= to_unsigned(16#0016#, 16);

  
  out0_88 <= out0_84 WHEN out0_83 = '0' ELSE
      k_5;

  out0_89 <= x_int(7);

  out0_90 <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & out0_89;

  
  out0_91 <= '1' WHEN out0_90 = to_unsigned(1, 32) ELSE
      '0';

  k_6 <= to_unsigned(16#0015#, 16);

  
  out0_92 <= out0_88 WHEN out0_87 = '0' ELSE
      k_6;

  k_7 <= to_unsigned(16#0014#, 16);

  
  out0_93 <= out0_92 WHEN out0_91 = '0' ELSE
      k_7;

  rd_21_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        out0_94 <= to_unsigned(16#0000#, 16);
      ELSE 
        out0_94 <= out0_93;
      END IF;
    END IF;
  END PROCESS rd_21_process;


  rd_19_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        out0_95 <= '0';
      ELSE 
        out0_95 <= out0_57;
      END IF;
    END IF;
  END PROCESS rd_19_process;


  k_8 <= to_unsigned(16#0013#, 16);

  
  out0_96 <= out0_94 WHEN out0_61 = '0' ELSE
      k_8;

  rd_18_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        out0_97 <= '0';
      ELSE 
        out0_97 <= out0_54;
      END IF;
    END IF;
  END PROCESS rd_18_process;


  k_9 <= to_unsigned(16#0012#, 16);

  
  out0_98 <= out0_96 WHEN out0_95 = '0' ELSE
      k_9;

  rd_17_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        out0_99 <= '0';
      ELSE 
        out0_99 <= out0_51;
      END IF;
    END IF;
  END PROCESS rd_17_process;


  k_10 <= to_unsigned(16#0011#, 16);

  
  out0_100 <= out0_98 WHEN out0_97 = '0' ELSE
      k_10;

  rd_16_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        out0_101 <= '0';
      ELSE 
        out0_101 <= out0_48;
      END IF;
    END IF;
  END PROCESS rd_16_process;


  k_11 <= to_unsigned(16#0010#, 16);

  
  out0_102 <= out0_100 WHEN out0_99 = '0' ELSE
      k_11;

  rd_15_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        out0_103 <= '0';
      ELSE 
        out0_103 <= out0_45;
      END IF;
    END IF;
  END PROCESS rd_15_process;


  k_12 <= to_unsigned(16#000F#, 16);

  
  out0_104 <= out0_102 WHEN out0_101 = '0' ELSE
      k_12;

  rd_14_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        out0_105 <= '0';
      ELSE 
        out0_105 <= out0_42;
      END IF;
    END IF;
  END PROCESS rd_14_process;


  k_13 <= to_unsigned(16#000E#, 16);

  
  out0_106 <= out0_104 WHEN out0_103 = '0' ELSE
      k_13;

  rd_13_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        out0_107 <= '0';
      ELSE 
        out0_107 <= out0_39;
      END IF;
    END IF;
  END PROCESS rd_13_process;


  k_14 <= to_unsigned(16#000D#, 16);

  
  out0_108 <= out0_106 WHEN out0_105 = '0' ELSE
      k_14;

  rd_12_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        out0_109 <= '0';
      ELSE 
        out0_109 <= out0_36;
      END IF;
    END IF;
  END PROCESS rd_12_process;


  k_15 <= to_unsigned(16#000C#, 16);

  
  out0_110 <= out0_108 WHEN out0_107 = '0' ELSE
      k_15;

  rd_11_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        out0_111 <= '0';
      ELSE 
        out0_111 <= out0_33;
      END IF;
    END IF;
  END PROCESS rd_11_process;


  k_16 <= to_unsigned(16#000B#, 16);

  
  out0_112 <= out0_110 WHEN out0_109 = '0' ELSE
      k_16;

  k_17 <= to_unsigned(16#000A#, 16);

  
  out0_113 <= out0_112 WHEN out0_111 = '0' ELSE
      k_17;

  rd_22_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        out0_114 <= to_unsigned(16#0000#, 16);
      ELSE 
        out0_114 <= out0_113;
      END IF;
    END IF;
  END PROCESS rd_22_process;


  rd_9_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        rd_9_reg <= (OTHERS => '0');
      ELSE 
        rd_9_reg(0) <= out0_26;
        rd_9_reg(1) <= rd_9_reg(0);
      END IF;
    END IF;
  END PROCESS rd_9_process;

  out0_115 <= rd_9_reg(1);

  k_18 <= to_unsigned(16#0009#, 16);

  
  out0_116 <= out0_114 WHEN out0_30 = '0' ELSE
      k_18;

  rd_8_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        rd_8_reg <= (OTHERS => '0');
      ELSE 
        rd_8_reg(0) <= out0_23;
        rd_8_reg(1) <= rd_8_reg(0);
      END IF;
    END IF;
  END PROCESS rd_8_process;

  out0_117 <= rd_8_reg(1);

  k_19 <= to_unsigned(16#0008#, 16);

  
  out0_118 <= out0_116 WHEN out0_115 = '0' ELSE
      k_19;

  rd_7_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        rd_7_reg <= (OTHERS => '0');
      ELSE 
        rd_7_reg(0) <= out0_20;
        rd_7_reg(1) <= rd_7_reg(0);
      END IF;
    END IF;
  END PROCESS rd_7_process;

  out0_119 <= rd_7_reg(1);

  k_20 <= to_unsigned(16#0007#, 16);

  
  out0_120 <= out0_118 WHEN out0_117 = '0' ELSE
      k_20;

  rd_6_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        rd_6_reg <= (OTHERS => '0');
      ELSE 
        rd_6_reg(0) <= out0_17;
        rd_6_reg(1) <= rd_6_reg(0);
      END IF;
    END IF;
  END PROCESS rd_6_process;

  out0_121 <= rd_6_reg(1);

  k_21 <= to_unsigned(16#0006#, 16);

  
  out0_122 <= out0_120 WHEN out0_119 = '0' ELSE
      k_21;

  rd_5_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        rd_5_reg <= (OTHERS => '0');
      ELSE 
        rd_5_reg(0) <= out0_14;
        rd_5_reg(1) <= rd_5_reg(0);
      END IF;
    END IF;
  END PROCESS rd_5_process;

  out0_123 <= rd_5_reg(1);

  k_22 <= to_unsigned(16#0005#, 16);

  
  out0_124 <= out0_122 WHEN out0_121 = '0' ELSE
      k_22;

  rd_4_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        rd_4_reg <= (OTHERS => '0');
      ELSE 
        rd_4_reg(0) <= out0_11;
        rd_4_reg(1) <= rd_4_reg(0);
      END IF;
    END IF;
  END PROCESS rd_4_process;

  out0_125 <= rd_4_reg(1);

  k_23 <= to_unsigned(16#0004#, 16);

  
  out0_126 <= out0_124 WHEN out0_123 = '0' ELSE
      k_23;

  rd_3_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        rd_3_reg <= (OTHERS => '0');
      ELSE 
        rd_3_reg(0) <= out0_8;
        rd_3_reg(1) <= rd_3_reg(0);
      END IF;
    END IF;
  END PROCESS rd_3_process;

  out0_127 <= rd_3_reg(1);

  k_24 <= to_unsigned(16#0003#, 16);

  
  out0_128 <= out0_126 WHEN out0_125 = '0' ELSE
      k_24;

  rd_2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        rd_2_reg <= (OTHERS => '0');
      ELSE 
        rd_2_reg(0) <= out0_5;
        rd_2_reg(1) <= rd_2_reg(0);
      END IF;
    END IF;
  END PROCESS rd_2_process;

  out0_129 <= rd_2_reg(1);

  k_25 <= to_unsigned(16#0002#, 16);

  
  out0_130 <= out0_128 WHEN out0_127 = '0' ELSE
      k_25;

  rd_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        rd_1_reg <= (OTHERS => '0');
      ELSE 
        rd_1_reg(0) <= out0_2;
        rd_1_reg(1) <= rd_1_reg(0);
      END IF;
    END IF;
  END PROCESS rd_1_process;

  out0_131 <= rd_1_reg(1);

  k_26 <= to_unsigned(16#0001#, 16);

  
  out0_132 <= out0_130 WHEN out0_129 = '0' ELSE
      k_26;

  k_27 <= to_unsigned(16#0000#, 16);

  -- 2. Priority Encoder for Leading Zero Count (LZC)
  -- k measures shift count to align the leading '1' to Bit 28 (2^0)
  
  k_28 <= out0_132 WHEN out0_131 = '0' ELSE
      k_27;

  rd_23_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        k_29 <= to_unsigned(16#0000#, 16);
      ELSE 
        k_29 <= k_28;
      END IF;
    END IF;
  END PROCESS rd_23_process;


  const_expression <= to_unsigned(16#0001#, 16);

  rd_24_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        rd_24_reg <= (OTHERS => to_unsigned(0, 32));
      ELSE 
        rd_24_reg(0) <= x_int;
        rd_24_reg(1 TO 2) <= rd_24_reg(0 TO 1);
      END IF;
    END IF;
  END PROCESS rd_24_process;

  x_int_1 <= rd_24_reg(2);

  -- k & 1
  -- 4. Normalize input: shift left so leading '1' lands on Bit 28
  x_norm <= x_int_1 sll to_integer(k_29);

  -- 5. Extract top 11 fractional bits (Bits 27 down to 17)
  -- Shift right by 16 moves Bit 17 to Bit 1, mask with 2047 (0x07FF)
  out0_133 <= SHIFT_RIGHT(x_norm, 16);

  
  out0_134 <= X"FFFF" WHEN out0_133(31 DOWNTO 16) /= X"0000" ELSE
      out0_133(15 DOWNTO 0);

  -- k >> 1 (m ranges from 0 to 13)
  r <= k_29 AND const_expression;

  -- 6. Combine parity bit r (Bit 12) with 11-bit address (Bits 11..1)
  out0_135 <= r sll 11;

  const_expression_1 <= to_unsigned(16#07FF#, 16);

  frac_11bit <= out0_134 AND const_expression_1;

  lut_addr_12bit_tmp <= out0_135 OR frac_11bit;

  lut_addr_12bit <= std_logic_vector(lut_addr_12bit_tmp);

  -- Zero clamp
  -- 3. Extract post-LUT shift m and parity bit r
  m_tmp <= SHIFT_RIGHT(k_28, 1);

  m <= std_logic_vector(m_tmp);

END rtl;

