-- -------------------------------------------------------------
-- 
-- File Name: SEL_Reverted\hdlsrc\SEL_test\SEL_toTest_fifo_data_OUT.vhd
-- Created: 2026-07-27 16:15:07
-- 
-- Generated by MATLAB 26.1, HDL Coder 26.1, and Simulink 26.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: SEL_toTest_fifo_data_OUT
-- Source Path: SEL_toTest/SEL_toTest_axi4_stream_dac2_master/SEL_toTest_fifo_data_OUT
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY SEL_toTest_fifo_data_OUT IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        In_rsvd                           :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16
        Push                              :   IN    std_logic;  -- ufix1
        Pop                               :   IN    std_logic;  -- ufix1
        Out_rsvd                          :   OUT   std_logic_vector(15 DOWNTO 0);  -- ufix16
        Empty                             :   OUT   std_logic;  -- ufix1
        AFull                             :   OUT   std_logic  -- ufix1
        );
END SEL_toTest_fifo_data_OUT;


ARCHITECTURE rtl OF SEL_toTest_fifo_data_OUT IS

  -- Component Declarations
  COMPONENT SEL_toTest_SimpleDualPortRAM_generic
    GENERIC( AddrWidth                    : integer;
             DataWidth                    : integer
             );
    PORT( clk                             :   IN    std_logic;
          enb                             :   IN    std_logic;
          wr_din                          :   IN    std_logic_vector(DataWidth - 1 DOWNTO 0);  -- generic width
          wr_addr                         :   IN    std_logic_vector(AddrWidth - 1 DOWNTO 0);  -- generic width
          wr_en                           :   IN    std_logic;  -- ufix1
          rd_addr                         :   IN    std_logic_vector(AddrWidth - 1 DOWNTO 0);  -- generic width
          dout                            :   OUT   std_logic_vector(DataWidth - 1 DOWNTO 0)  -- generic width
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : SEL_toTest_SimpleDualPortRAM_generic
    USE ENTITY work.SEL_toTest_SimpleDualPortRAM_generic(rtl);

  -- Signals
  SIGNAL R_x                              : std_logic;  -- ufix1
  SIGNAL cache_wr_en                      : std_logic;  -- ufix1
  SIGNAL out_wr_en                        : std_logic;  -- ufix1
  SIGNAL fwft_wr_en                       : std_logic;  -- ufix1
  SIGNAL R_x_1                            : std_logic;  -- ufix1
  SIGNAL fifo_valid                       : std_logic;  -- ufix1
  SIGNAL Q_keep                           : std_logic;  -- ufix1
  SIGNAL out_valid                        : std_logic;  -- ufix1
  SIGNAL fifo_and_out_valid               : std_logic;  -- ufix1
  SIGNAL R_x_2                            : std_logic;  -- ufix1
  SIGNAL cache_valid                      : std_logic;  -- ufix1
  SIGNAL Q_keep_1                         : std_logic;  -- ufix1
  SIGNAL cache_update                     : std_logic;  -- ufix1
  SIGNAL Q_next                           : std_logic;  -- ufix1
  SIGNAL all_valid                        : std_logic;  -- ufix1
  SIGNAL w_we_bool                        : std_logic;
  SIGNAL w_re_bool                        : std_logic;
  SIGNAL num_enb                          : std_logic;
  SIGNAL fifo_pop                         : std_logic;  -- ufix1
  SIGNAL not_empty                        : std_logic;
  SIGNAL w_re                             : std_logic;  -- ufix1
  SIGNAL w_re_neg                         : std_logic;
  SIGNAL Full                             : std_logic;  -- ufix1
  SIGNAL not_full                         : std_logic;  -- ufix1
  SIGNAL valid_push                       : std_logic;  -- ufix1
  SIGNAL Num                              : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL fifo_nfull                       : std_logic;  -- ufix1
  SIGNAL fifo_push                        : std_logic;  -- ufix1
  SIGNAL w_we                             : std_logic;  -- ufix1
  SIGNAL num_entries_dir                  : std_logic;
  SIGNAL num_entries_count                : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL num_entries_count_next           : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL num_entries_count_step           : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL Empty_1                          : std_logic;  -- ufix1
  SIGNAL Q_next_1                         : std_logic;  -- ufix1
  SIGNAL int_valid                        : std_logic;  -- ufix1
  SIGNAL Q_keep_2                         : std_logic;  -- ufix1
  SIGNAL Q_next_2                         : std_logic;  -- ufix1
  SIGNAL Empty_2                          : std_logic;  -- ufix1
  SIGNAL data_flow                        : std_logic;  -- ufix1
  SIGNAL w_d1                             : std_logic;  -- ufix1
  SIGNAL w_waddr                          : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL w_raddr                          : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL w_waddr_1                        : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL w_waddr_unsigned                 : unsigned(15 DOWNTO 0);  -- ufix16
  SIGNAL w_out                            : unsigned(15 DOWNTO 0);  -- ufix16
  SIGNAL w_d2                             : unsigned(15 DOWNTO 0);  -- ufix16
  SIGNAL cache_data                       : unsigned(15 DOWNTO 0);  -- ufix16
  SIGNAL data_out_next                    : unsigned(15 DOWNTO 0);  -- ufix16
  SIGNAL Out_tmp                          : unsigned(15 DOWNTO 0);  -- ufix16
  SIGNAL afull_num                        : unsigned(2 DOWNTO 0);  -- ufix3

BEGIN
  -- us1: Upsample by 1, Sample offset 0 
  u_SEL_toTest_fifo_data_OUT_classic_ram_generic : SEL_toTest_SimpleDualPortRAM_generic
    GENERIC MAP( AddrWidth => 2,
                 DataWidth => 16
                 )
    PORT MAP( clk => clk,
              enb => enb,
              wr_din => In_rsvd,
              wr_addr => std_logic_vector(w_waddr),
              wr_en => w_we,  -- ufix1
              rd_addr => std_logic_vector(w_raddr),
              dout => w_waddr_1
              );

  R_x <=  NOT Pop;

  fwft_wr_en <= cache_wr_en OR out_wr_en;

  R_x_1 <=  NOT fwft_wr_en;

  Q_keep <= R_x_1 AND fifo_valid;

  fifo_and_out_valid <= fifo_valid AND out_valid;

  R_x_2 <=  NOT out_wr_en;

  Q_keep_1 <= R_x_2 AND cache_valid;

  
  cache_update <= '1' WHEN cache_valid = out_wr_en ELSE
      '0';

  cache_wr_en <= cache_update AND fifo_valid;

  Q_next <= cache_wr_en OR Q_keep_1;

  Q_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        cache_valid <= '0';
      ELSIF enb = '1' THEN
        cache_valid <= Q_next;
      END IF;
    END IF;
  END PROCESS Q_reg_process;


  all_valid <= cache_valid AND fifo_and_out_valid;

  num_enb <= w_we_bool XOR w_re_bool;

  w_re <= fifo_pop AND not_empty;

  w_re_bool <= w_re;

  w_re_neg <=  NOT w_re_bool;

  not_full <=  NOT Full;

  valid_push <= fifo_pop OR not_full;

  
  Full <= '1' WHEN Num = to_unsigned(16#4#, 3) ELSE
      '0';

  fifo_nfull <=  NOT Full;

  -- us2: Upsample by 1, Sample offset 0 
  fifo_push <= Push AND fifo_nfull;

  w_we <= fifo_push AND valid_push;

  w_we_bool <= w_we;

  num_entries_dir <= w_we_bool AND w_re_neg;

  -- Free running, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  num_entries_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        num_entries_count <= to_unsigned(16#0#, 3);
      ELSIF enb = '1' AND num_enb = '1' THEN
        num_entries_count <= num_entries_count_next;
      END IF;
    END IF;
  END PROCESS num_entries_process;

  Num <= num_entries_count;
  
  num_entries_count_step <= to_unsigned(16#1#, 3) WHEN num_entries_dir = '1' ELSE
      to_unsigned(16#7#, 3);
  num_entries_count_next <= num_entries_count + num_entries_count_step;

  
  not_empty <= '1' WHEN Num /= to_unsigned(16#0#, 3) ELSE
      '0';

  Empty_1 <=  NOT not_empty;

  -- us3: Upsample by 1, Sample offset 0 
  fifo_pop <=  NOT (Empty_1 OR all_valid);

  Q_next_1 <= fifo_pop OR Q_keep;

  Q_reg_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        fifo_valid <= '0';
      ELSIF enb = '1' THEN
        fifo_valid <= Q_next_1;
      END IF;
    END IF;
  END PROCESS Q_reg_1_process;


  int_valid <= fifo_valid OR cache_valid;

  Q_keep_2 <= R_x AND out_valid;

  Q_next_2 <= out_wr_en OR Q_keep_2;

  Q_reg_2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        out_valid <= '0';
      ELSIF enb = '1' THEN
        out_valid <= Q_next_2;
      END IF;
    END IF;
  END PROCESS Q_reg_2_process;


  Empty_2 <=  NOT out_valid;

  data_flow <= Pop OR Empty_2;

  out_wr_en <= data_flow AND int_valid;

  reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        w_d1 <= '0';
      ELSIF enb = '1' THEN
        w_d1 <= w_re;
      END IF;
    END IF;
  END PROCESS reg_process;


  -- Count limited, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  --  count to value  = 3
  write_counter_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        w_waddr <= to_unsigned(16#0#, 2);
      ELSIF enb = '1' AND w_we = '1' THEN
        w_waddr <= w_waddr + to_unsigned(16#1#, 2);
      END IF;
    END IF;
  END PROCESS write_counter_process;


  -- Count limited, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  --  count to value  = 3
  read_counter_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        w_raddr <= to_unsigned(16#0#, 2);
      ELSIF enb = '1' AND w_re = '1' THEN
        w_raddr <= w_raddr + to_unsigned(16#1#, 2);
      END IF;
    END IF;
  END PROCESS read_counter_process;


  w_waddr_unsigned <= unsigned(w_waddr_1);

  f_d2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        w_d2 <= to_unsigned(16#0000#, 16);
      ELSIF enb = '1' THEN
        w_d2 <= w_out;
      END IF;
    END IF;
  END PROCESS f_d2_process;


  
  w_out <= w_d2 WHEN w_d1 = '0' ELSE
      w_waddr_unsigned;

  cache_data_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        cache_data <= to_unsigned(16#0000#, 16);
      ELSIF enb = '1' AND cache_wr_en = '1' THEN
        cache_data <= w_out;
      END IF;
    END IF;
  END PROCESS cache_data_reg_process;


  
  data_out_next <= w_out WHEN cache_valid = '0' ELSE
      cache_data;

  out_data_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Out_tmp <= to_unsigned(16#0000#, 16);
      ELSIF enb = '1' AND out_wr_en = '1' THEN
        Out_tmp <= data_out_next;
      END IF;
    END IF;
  END PROCESS out_data_reg_process;


  Out_rsvd <= std_logic_vector(Out_tmp);

  Empty <= Empty_2;

  afull_num <= to_unsigned(16#3#, 3);

  
  AFull <= '1' WHEN Num >= afull_num ELSE
      '0';

END rtl;

