-- -------------------------------------------------------------
-- 
-- File Name: SEL_Reverted\hdlsrc\SEL_test\SEL_toTest_src_COMPLEX_ROTATE.vhd
-- Created: 2026-07-27 16:14:57
-- 
-- Generated by MATLAB 26.1, HDL Coder 26.1, and Simulink 26.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: SEL_toTest_src_COMPLEX_ROTATE
-- Source Path: SEL_test/TESTBENCH/SEL/SEL_WRAPPED/DSP_LOGIC/COMPLEX_ROTATE
-- Hierarchy Level: 3
-- Model version: 1.616
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY SEL_toTest_src_COMPLEX_ROTATE IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        I                                 :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En23
        Q                                 :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En23
        valid                             :   IN    std_logic;
        user_offset_PHASE_COS             :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
        user_offset_PHASE_SIN             :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
        I_offset                          :   OUT   std_logic_vector(25 DOWNTO 0);  -- sfix26_En23
        Q_offset                          :   OUT   std_logic_vector(25 DOWNTO 0);  -- sfix26_En23
        valid_o                           :   OUT   std_logic
        );
END SEL_toTest_src_COMPLEX_ROTATE;


ARCHITECTURE rtl OF SEL_toTest_src_COMPLEX_ROTATE IS

  -- Component Declarations
  COMPONENT SEL_toTest_src_Subsystem
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          I                               :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En23
          Q                               :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En23
          phase_sin                       :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
          phase_cos                       :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
          Qsin                            :   OUT   std_logic_vector(24 DOWNTO 0);  -- sfix25_En23
          Icos                            :   OUT   std_logic_vector(24 DOWNTO 0);  -- sfix25_En23
          Isin                            :   OUT   std_logic_vector(24 DOWNTO 0);  -- sfix25_En23
          Qcos                            :   OUT   std_logic_vector(24 DOWNTO 0)  -- sfix25_En23
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : SEL_toTest_src_Subsystem
    USE ENTITY work.SEL_toTest_src_Subsystem(rtl);

  -- Signals
  SIGNAL PHASE_COS                        : signed(17 DOWNTO 0);  -- sfix18_En16
  SIGNAL PHASE_COS_1                      : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL PHASE_SIN                        : signed(17 DOWNTO 0);  -- sfix18_En16
  SIGNAL PHASE_SIN_1                      : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL Subsystem_Qsin                   : std_logic_vector(24 DOWNTO 0);  -- ufix25
  SIGNAL Subsystem_Icos                   : std_logic_vector(24 DOWNTO 0);  -- ufix25
  SIGNAL Subsystem_Isin                   : std_logic_vector(24 DOWNTO 0);  -- ufix25
  SIGNAL Subsystem_Qcos                   : std_logic_vector(24 DOWNTO 0);  -- ufix25
  SIGNAL Subsystem_Icos_signed            : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL Subsystem_Icos_1                 : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL Subsystem_Qsin_signed            : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL Subsystem_Qsin_1                 : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL I_sum_sub_cast                   : signed(25 DOWNTO 0);  -- sfix26_En23
  SIGNAL I_sum_sub_cast_1                 : signed(25 DOWNTO 0);  -- sfix26_En23
  SIGNAL I_sum_out1                       : signed(25 DOWNTO 0);  -- sfix26_En23
  SIGNAL Subsystem_Isin_signed            : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL Subsystem_Isin_1                 : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL Subsystem_Qcos_signed            : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL Subsystem_Qcos_1                 : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL Q_sum_add_cast                   : signed(25 DOWNTO 0);  -- sfix26_En23
  SIGNAL Q_sum_add_cast_1                 : signed(25 DOWNTO 0);  -- sfix26_En23
  SIGNAL Q_sum_out1                       : signed(25 DOWNTO 0);  -- sfix26_En23

BEGIN
  -- phi = AXI_lite input phase offset
  -- I_rotated = I * cos(phi) - Q * sin(phi)
  -- Q_rotated = Q * cos(phi) + I * sin(phi)

  u_Subsystem : SEL_toTest_src_Subsystem
    PORT MAP( clk => clk,
              reset => reset,
              I => I,  -- sfix25_En23
              Q => Q,  -- sfix25_En23
              phase_sin => PHASE_COS_1,  -- sfix18_En16
              phase_cos => PHASE_SIN_1,  -- sfix18_En16
              Qsin => Subsystem_Qsin,  -- sfix25_En23
              Icos => Subsystem_Icos,  -- sfix25_En23
              Isin => Subsystem_Isin,  -- sfix25_En23
              Qcos => Subsystem_Qcos  -- sfix25_En23
              );

  PHASE_COS <= signed(user_offset_PHASE_COS);

  PHASE_COS_1 <= std_logic_vector(PHASE_COS);

  PHASE_SIN <= signed(user_offset_PHASE_SIN);

  PHASE_SIN_1 <= std_logic_vector(PHASE_SIN);

  Subsystem_Icos_signed <= signed(Subsystem_Icos);

  rd_0_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Subsystem_Icos_1 <= to_signed(16#0000000#, 25);
      ELSE 
        Subsystem_Icos_1 <= Subsystem_Icos_signed;
      END IF;
    END IF;
  END PROCESS rd_0_process;


  Subsystem_Qsin_signed <= signed(Subsystem_Qsin);

  rd_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Subsystem_Qsin_1 <= to_signed(16#0000000#, 25);
      ELSE 
        Subsystem_Qsin_1 <= Subsystem_Qsin_signed;
      END IF;
    END IF;
  END PROCESS rd_1_process;


  I_sum_sub_cast <= resize(Subsystem_Icos_1, 26);
  I_sum_sub_cast_1 <= resize(Subsystem_Qsin_1, 26);
  I_sum_out1 <= I_sum_sub_cast - I_sum_sub_cast_1;

  I_offset <= std_logic_vector(I_sum_out1);

  Subsystem_Isin_signed <= signed(Subsystem_Isin);

  rd_2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Subsystem_Isin_1 <= to_signed(16#0000000#, 25);
      ELSE 
        Subsystem_Isin_1 <= Subsystem_Isin_signed;
      END IF;
    END IF;
  END PROCESS rd_2_process;


  Subsystem_Qcos_signed <= signed(Subsystem_Qcos);

  rd_3_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Subsystem_Qcos_1 <= to_signed(16#0000000#, 25);
      ELSE 
        Subsystem_Qcos_1 <= Subsystem_Qcos_signed;
      END IF;
    END IF;
  END PROCESS rd_3_process;


  Q_sum_add_cast <= resize(Subsystem_Isin_1, 26);
  Q_sum_add_cast_1 <= resize(Subsystem_Qcos_1, 26);
  Q_sum_out1 <= Q_sum_add_cast + Q_sum_add_cast_1;

  Q_offset <= std_logic_vector(Q_sum_out1);

  valid_o <= valid;

END rtl;

