-- -------------------------------------------------------------
-- 
-- File Name: SEL_Reverted\hdlsrc\SEL_test\SEL_toTest_src_Subsystem.vhd
-- Created: 2026-07-27 16:14:57
-- 
-- Generated by MATLAB 26.1, HDL Coder 26.1, and Simulink 26.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: SEL_toTest_src_Subsystem
-- Source Path: SEL_test/TESTBENCH/SEL/SEL_WRAPPED/DSP_LOGIC/COMPLEX_ROTATE/Subsystem
-- Hierarchy Level: 4
-- Model version: 1.616
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.SEL_toTest_src_SEL_pkg.ALL;

ENTITY SEL_toTest_src_Subsystem IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        I                                 :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En23
        Q                                 :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En23
        phase_sin                         :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
        phase_cos                         :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
        Qsin                              :   OUT   std_logic_vector(24 DOWNTO 0);  -- sfix25_En23
        Icos                              :   OUT   std_logic_vector(24 DOWNTO 0);  -- sfix25_En23
        Isin                              :   OUT   std_logic_vector(24 DOWNTO 0);  -- sfix25_En23
        Qcos                              :   OUT   std_logic_vector(24 DOWNTO 0)  -- sfix25_En23
        );
END SEL_toTest_src_Subsystem;


ARCHITECTURE rtl OF SEL_toTest_src_Subsystem IS

  -- Signals
  SIGNAL phase_sin_signed                 : signed(17 DOWNTO 0);  -- sfix18_En16
  SIGNAL rd_0_reg                         : vector_of_signed18(0 TO 18);  -- sfix18 [19]
  SIGNAL phase_sin_1                      : signed(17 DOWNTO 0);  -- sfix18_En16
  SIGNAL phase_sin_2                      : signed(17 DOWNTO 0);  -- sfix18_En16
  SIGNAL Q_signed                         : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL Q_1                              : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL Q_sin_out1                       : signed(42 DOWNTO 0);  -- sfix43_En39
  SIGNAL Q_sin_out1_1                     : signed(42 DOWNTO 0);  -- sfix43_En39
  SIGNAL Q_sin_out1_2                     : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL I_signed                         : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL I_1                              : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL phase_cos_signed                 : signed(17 DOWNTO 0);  -- sfix18_En16
  SIGNAL rd_1_reg                         : vector_of_signed18(0 TO 18);  -- sfix18 [19]
  SIGNAL phase_cos_1                      : signed(17 DOWNTO 0);  -- sfix18_En16
  SIGNAL phase_cos_2                      : signed(17 DOWNTO 0);  -- sfix18_En16
  SIGNAL I_cos_out1                       : signed(42 DOWNTO 0);  -- sfix43_En39
  SIGNAL I_cos_out1_1                     : signed(42 DOWNTO 0);  -- sfix43_En39
  SIGNAL I_cos_out1_2                     : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL I_sin_out1                       : signed(42 DOWNTO 0);  -- sfix43_En39
  SIGNAL I_sin_out1_1                     : signed(42 DOWNTO 0);  -- sfix43_En39
  SIGNAL I_sin_out1_2                     : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL Q_cos_out1                       : signed(42 DOWNTO 0);  -- sfix43_En39
  SIGNAL Q_cos_out1_1                     : signed(42 DOWNTO 0);  -- sfix43_En39
  SIGNAL Q_cos_out1_2                     : signed(24 DOWNTO 0);  -- sfix25_En23

  ATTRIBUTE use_dsp : string;

  ATTRIBUTE use_dsp OF Q_sin_out1 : SIGNAL IS "yes";
  ATTRIBUTE use_dsp OF I_cos_out1 : SIGNAL IS "yes";
  ATTRIBUTE use_dsp OF I_sin_out1 : SIGNAL IS "yes";
  ATTRIBUTE use_dsp OF Q_cos_out1 : SIGNAL IS "yes";

BEGIN
  phase_sin_signed <= signed(phase_sin);

  rd_0_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        rd_0_reg <= (OTHERS => to_signed(16#00000#, 18));
      ELSE 
        rd_0_reg(0) <= phase_sin_signed;
        rd_0_reg(1 TO 18) <= rd_0_reg(0 TO 17);
      END IF;
    END IF;
  END PROCESS rd_0_process;

  phase_sin_1 <= rd_0_reg(18);

  reduced_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        phase_sin_2 <= to_signed(16#00000#, 18);
      ELSE 
        phase_sin_2 <= phase_sin_1;
      END IF;
    END IF;
  END PROCESS reduced_process;


  Q_signed <= signed(Q);

  reduced_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Q_1 <= to_signed(16#0000000#, 25);
      ELSE 
        Q_1 <= Q_signed;
      END IF;
    END IF;
  END PROCESS reduced_1_process;


  Q_sin_out1 <= phase_sin_2 * Q_1;

  PipelineRegister3_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Q_sin_out1_1 <= to_signed(0, 43);
      ELSE 
        Q_sin_out1_1 <= Q_sin_out1;
      END IF;
    END IF;
  END PROCESS PipelineRegister3_process;


  
  Q_sin_out1_2 <= "0111111111111111111111111" WHEN ((Q_sin_out1_1(42) = '0') AND (Q_sin_out1_1(41 DOWNTO 40) /= "00")) OR ((Q_sin_out1_1(42) = '0') AND (Q_sin_out1_1(40 DOWNTO 16) = "0111111111111111111111111")) ELSE
      "1000000000000000000000000" WHEN (Q_sin_out1_1(42) = '1') AND (Q_sin_out1_1(41 DOWNTO 40) /= "11") ELSE
      Q_sin_out1_1(40 DOWNTO 16) + ('0' & Q_sin_out1_1(15));

  Qsin <= std_logic_vector(Q_sin_out1_2);

  I_signed <= signed(I);

  reduced_2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        I_1 <= to_signed(16#0000000#, 25);
      ELSE 
        I_1 <= I_signed;
      END IF;
    END IF;
  END PROCESS reduced_2_process;


  phase_cos_signed <= signed(phase_cos);

  rd_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        rd_1_reg <= (OTHERS => to_signed(16#00000#, 18));
      ELSE 
        rd_1_reg(0) <= phase_cos_signed;
        rd_1_reg(1 TO 18) <= rd_1_reg(0 TO 17);
      END IF;
    END IF;
  END PROCESS rd_1_process;

  phase_cos_1 <= rd_1_reg(18);

  reduced_3_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        phase_cos_2 <= to_signed(16#00000#, 18);
      ELSE 
        phase_cos_2 <= phase_cos_1;
      END IF;
    END IF;
  END PROCESS reduced_3_process;


  I_cos_out1 <= I_1 * phase_cos_2;

  PipelineRegister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        I_cos_out1_1 <= to_signed(0, 43);
      ELSE 
        I_cos_out1_1 <= I_cos_out1;
      END IF;
    END IF;
  END PROCESS PipelineRegister_process;


  
  I_cos_out1_2 <= "0111111111111111111111111" WHEN ((I_cos_out1_1(42) = '0') AND (I_cos_out1_1(41 DOWNTO 40) /= "00")) OR ((I_cos_out1_1(42) = '0') AND (I_cos_out1_1(40 DOWNTO 16) = "0111111111111111111111111")) ELSE
      "1000000000000000000000000" WHEN (I_cos_out1_1(42) = '1') AND (I_cos_out1_1(41 DOWNTO 40) /= "11") ELSE
      I_cos_out1_1(40 DOWNTO 16) + ('0' & I_cos_out1_1(15));

  Icos <= std_logic_vector(I_cos_out1_2);

  I_sin_out1 <= phase_sin_2 * I_1;

  PipelineRegister1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        I_sin_out1_1 <= to_signed(0, 43);
      ELSE 
        I_sin_out1_1 <= I_sin_out1;
      END IF;
    END IF;
  END PROCESS PipelineRegister1_process;


  
  I_sin_out1_2 <= "0111111111111111111111111" WHEN ((I_sin_out1_1(42) = '0') AND (I_sin_out1_1(41 DOWNTO 40) /= "00")) OR ((I_sin_out1_1(42) = '0') AND (I_sin_out1_1(40 DOWNTO 16) = "0111111111111111111111111")) ELSE
      "1000000000000000000000000" WHEN (I_sin_out1_1(42) = '1') AND (I_sin_out1_1(41 DOWNTO 40) /= "11") ELSE
      I_sin_out1_1(40 DOWNTO 16) + ('0' & I_sin_out1_1(15));

  Isin <= std_logic_vector(I_sin_out1_2);

  Q_cos_out1 <= Q_1 * phase_cos_2;

  PipelineRegister2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Q_cos_out1_1 <= to_signed(0, 43);
      ELSE 
        Q_cos_out1_1 <= Q_cos_out1;
      END IF;
    END IF;
  END PROCESS PipelineRegister2_process;


  
  Q_cos_out1_2 <= "0111111111111111111111111" WHEN ((Q_cos_out1_1(42) = '0') AND (Q_cos_out1_1(41 DOWNTO 40) /= "00")) OR ((Q_cos_out1_1(42) = '0') AND (Q_cos_out1_1(40 DOWNTO 16) = "0111111111111111111111111")) ELSE
      "1000000000000000000000000" WHEN (Q_cos_out1_1(42) = '1') AND (Q_cos_out1_1(41 DOWNTO 40) /= "11") ELSE
      Q_cos_out1_1(40 DOWNTO 16) + ('0' & Q_cos_out1_1(15));

  Qcos <= std_logic_vector(Q_cos_out1_2);

END rtl;

