-- -------------------------------------------------------------
-- 
-- File Name: SEL_Reverted\hdlsrc\SEL_test\SEL_toTest_dut.vhd
-- Created: 2026-07-27 16:15:07
-- 
-- Generated by MATLAB 26.1, HDL Coder 26.1, and Simulink 26.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: SEL_toTest_dut
-- Source Path: SEL_toTest/SEL_toTest_dut
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY SEL_toTest_dut IS
  PORT( clk_1                             :   IN    std_logic;  -- ufix1
        reset_1                           :   IN    std_logic;  -- ufix1
        S_AXIS_ADC1_TDATA                 :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16
        S_AXIS_ADC1_TVALID                :   IN    std_logic;  -- ufix1
        AXI4_LITE_CONTROL_PHASE_COS       :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
        AXI4_LITE_CONTROL_PHASE_SIN       :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
        AXI4_LITE_CONTROL_MAG_SET         :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
        AXI4_LITE_CONTROL_K_HIGH          :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
        AXI4_LITE_CONTROL_K_LOW           :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
        AXI4_LITE_CONTROL_PULSE_WIDTH     :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        AXI4_LITE_CONTROL_PULSE_EN        :   IN    std_logic;  -- ufix1
        AXI4_LITE_CONTROL_AUTO_EN         :   IN    std_logic;  -- ufix1
        AXI4_LITE_CONTROL_REP_PERIOD      :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        M_AXIS_DAC1_TDATA                 :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16
        M_AXIS_DAC1_TVALID                :   OUT   std_logic;  -- ufix1
        M_AXIS_DAC2_TDATA                 :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16
        M_AXIS_DAC2_TVALID                :   OUT   std_logic  -- ufix1
        );
END SEL_toTest_dut;


ARCHITECTURE rtl OF SEL_toTest_dut IS

  -- Component Declarations
  COMPONENT SEL_toTest_src_SEL
    PORT( clk                             :   IN    std_logic;  -- ufix1
          reset                           :   IN    std_logic;  -- ufix1
          S_AXIS_ADC1_TDATA               :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16
          S_AXIS_ADC1_TVALID              :   IN    std_logic;  -- ufix1
          AXI4_LITE_CONTROL_PHASE_COS     :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
          AXI4_LITE_CONTROL_PHASE_SIN     :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
          AXI4_LITE_CONTROL_MAG_SET       :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
          AXI4_LITE_CONTROL_K_HIGH        :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
          AXI4_LITE_CONTROL_K_LOW         :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
          AXI4_LITE_CONTROL_PULSE_WIDTH   :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          AXI4_LITE_CONTROL_PULSE_EN      :   IN    std_logic;  -- ufix1
          AXI4_LITE_CONTROL_AUTO_EN       :   IN    std_logic;  -- ufix1
          AXI4_LITE_CONTROL_REP_PERIOD    :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          M_AXIS_DAC1_TDATA               :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16
          M_AXIS_DAC1_TVALID              :   OUT   std_logic;  -- ufix1
          M_AXIS_DAC2_TDATA               :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16
          M_AXIS_DAC2_TVALID              :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : SEL_toTest_src_SEL
    USE ENTITY work.SEL_toTest_src_SEL(rtl);

  -- Signals
  SIGNAL clk_sig                          : std_logic;  -- ufix1
  SIGNAL reset_sig                        : std_logic;  -- ufix1
  SIGNAL S_AXIS_ADC1_TVALID_sig           : std_logic;  -- ufix1
  SIGNAL AXI4_LITE_CONTROL_PULSE_EN_sig   : std_logic;  -- ufix1
  SIGNAL AXI4_LITE_CONTROL_AUTO_EN_sig    : std_logic;  -- ufix1
  SIGNAL M_AXIS_DAC1_TDATA_sig            : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL M_AXIS_DAC1_TVALID_sig           : std_logic;  -- ufix1
  SIGNAL M_AXIS_DAC2_TDATA_sig            : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL M_AXIS_DAC2_TVALID_sig           : std_logic;  -- ufix1

BEGIN
  u_SEL_toTest_src_SEL : SEL_toTest_src_SEL
    PORT MAP( clk => clk_sig,  -- ufix1
              reset => reset_sig,  -- ufix1
              S_AXIS_ADC1_TDATA => S_AXIS_ADC1_TDATA,  -- sfix16
              S_AXIS_ADC1_TVALID => S_AXIS_ADC1_TVALID_sig,  -- ufix1
              AXI4_LITE_CONTROL_PHASE_COS => AXI4_LITE_CONTROL_PHASE_COS,  -- sfix18_En16
              AXI4_LITE_CONTROL_PHASE_SIN => AXI4_LITE_CONTROL_PHASE_SIN,  -- sfix18_En16
              AXI4_LITE_CONTROL_MAG_SET => AXI4_LITE_CONTROL_MAG_SET,  -- sfix18_En16
              AXI4_LITE_CONTROL_K_HIGH => AXI4_LITE_CONTROL_K_HIGH,  -- sfix18_En16
              AXI4_LITE_CONTROL_K_LOW => AXI4_LITE_CONTROL_K_LOW,  -- sfix18_En16
              AXI4_LITE_CONTROL_PULSE_WIDTH => AXI4_LITE_CONTROL_PULSE_WIDTH,  -- ufix32
              AXI4_LITE_CONTROL_PULSE_EN => AXI4_LITE_CONTROL_PULSE_EN_sig,  -- ufix1
              AXI4_LITE_CONTROL_AUTO_EN => AXI4_LITE_CONTROL_AUTO_EN_sig,  -- ufix1
              AXI4_LITE_CONTROL_REP_PERIOD => AXI4_LITE_CONTROL_REP_PERIOD,  -- ufix32
              M_AXIS_DAC1_TDATA => M_AXIS_DAC1_TDATA_sig,  -- sfix16
              M_AXIS_DAC1_TVALID => M_AXIS_DAC1_TVALID_sig,  -- ufix1
              M_AXIS_DAC2_TDATA => M_AXIS_DAC2_TDATA_sig,  -- sfix16
              M_AXIS_DAC2_TVALID => M_AXIS_DAC2_TVALID_sig  -- ufix1
              );

  clk_sig <= clk_1;

  reset_sig <= reset_1;

  S_AXIS_ADC1_TVALID_sig <= S_AXIS_ADC1_TVALID;

  AXI4_LITE_CONTROL_PULSE_EN_sig <= AXI4_LITE_CONTROL_PULSE_EN;

  AXI4_LITE_CONTROL_AUTO_EN_sig <= AXI4_LITE_CONTROL_AUTO_EN;

  M_AXIS_DAC1_TDATA <= M_AXIS_DAC1_TDATA_sig;

  M_AXIS_DAC1_TVALID <= M_AXIS_DAC1_TVALID_sig;

  M_AXIS_DAC2_TDATA <= M_AXIS_DAC2_TDATA_sig;

  M_AXIS_DAC2_TVALID <= M_AXIS_DAC2_TVALID_sig;

END rtl;

