-- -------------------------------------------------------------
-- 
-- File Name: SEL_Reverted\hdlsrc\SEL_test\SEL_toTest_axi4_stream_adc1_slave.vhd
-- Created: 2026-07-27 16:15:07
-- 
-- Generated by MATLAB 26.1, HDL Coder 26.1, and Simulink 26.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: SEL_toTest_axi4_stream_adc1_slave
-- Source Path: SEL_toTest/SEL_toTest_axi4_stream_adc1_slave
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY SEL_toTest_axi4_stream_adc1_slave IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        AXI4_Stream_ADC1_Slave_TDATA      :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16
        AXI4_Stream_ADC1_Slave_TVALID     :   IN    std_logic;  -- ufix1
        AXI4_Stream_ADC1_Slave_TREADY     :   OUT   std_logic;  -- ufix1
        user_data                         :   OUT   std_logic_vector(15 DOWNTO 0);  -- ufix16
        user_valid                        :   OUT   std_logic  -- ufix1
        );
END SEL_toTest_axi4_stream_adc1_slave;


ARCHITECTURE rtl OF SEL_toTest_axi4_stream_adc1_slave IS

  -- Component Declarations
  COMPONENT SEL_toTest_fifo_data
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          In_rsvd                         :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16
          Push                            :   IN    std_logic;  -- ufix1
          Pop                             :   IN    std_logic;  -- ufix1
          Out_rsvd                        :   OUT   std_logic_vector(15 DOWNTO 0);  -- ufix16
          Empty                           :   OUT   std_logic;  -- ufix1
          Full                            :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : SEL_toTest_fifo_data
    USE ENTITY work.SEL_toTest_fifo_data(rtl);

  -- Signals
  SIGNAL const_1                          : std_logic;  -- ufix1
  SIGNAL fifo_rd_ack                      : std_logic;  -- ufix1
  SIGNAL stream_in_fifo_user_data         : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL fifo_empty                       : std_logic;  -- ufix1
  SIGNAL fifo_full                        : std_logic;  -- ufix1
  SIGNAL fifo_empty_neg                   : std_logic;  -- ufix1
  SIGNAL stream_in_user_valid             : std_logic;  -- ufix1

BEGIN
  u_SEL_toTest_fifo_data_inst : SEL_toTest_fifo_data
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              In_rsvd => AXI4_Stream_ADC1_Slave_TDATA,  -- ufix16
              Push => AXI4_Stream_ADC1_Slave_TVALID,  -- ufix1
              Pop => fifo_rd_ack,  -- ufix1
              Out_rsvd => stream_in_fifo_user_data,  -- ufix16
              Empty => fifo_empty,  -- ufix1
              Full => fifo_full  -- ufix1
              );

  const_1 <= '1';

  intdelay_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        fifo_rd_ack <= '0';
      ELSIF enb = '1' THEN
        fifo_rd_ack <= const_1;
      END IF;
    END IF;
  END PROCESS intdelay_process;


  AXI4_Stream_ADC1_Slave_TREADY <=  NOT fifo_full;

  user_data <= stream_in_fifo_user_data;

  fifo_empty_neg <=  NOT fifo_empty;

  stream_in_user_valid <= fifo_empty_neg AND fifo_rd_ack;

  user_valid <= stream_in_user_valid;

END rtl;

