-- -------------------------------------------------------------
-- 
-- File Name: SEL_Reverted\hdlsrc\SEL_test\SEL_toTest_src_SEL.vhd
-- Created: 2026-07-27 16:14:58
-- 
-- Generated by MATLAB 26.1, HDL Coder 26.1, and Simulink 26.1
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 8e-09
-- Target subsystem base rate: 8e-09
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: SEL_toTest_src_SEL
-- Source Path: SEL_test/TESTBENCH/SEL
-- Hierarchy Level: 0
-- Model version: 1.616
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.SEL_toTest_src_SEL_pkg.ALL;

ENTITY SEL_toTest_src_SEL IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        S_AXIS_ADC1_TDATA                 :   IN    std_logic_vector(15 DOWNTO 0);  -- int16
        S_AXIS_ADC1_TVALID                :   IN    std_logic;
        AXI4_LITE_CONTROL_PHASE_COS       :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
        AXI4_LITE_CONTROL_PHASE_SIN       :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
        AXI4_LITE_CONTROL_MAG_SET         :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
        AXI4_LITE_CONTROL_K_HIGH          :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
        AXI4_LITE_CONTROL_K_LOW           :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
        AXI4_LITE_CONTROL_PULSE_WIDTH     :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        AXI4_LITE_CONTROL_PULSE_EN        :   IN    std_logic;
        AXI4_LITE_CONTROL_AUTO_EN         :   IN    std_logic;
        AXI4_LITE_CONTROL_REP_PERIOD      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        M_AXIS_DAC1_TDATA                 :   OUT   std_logic_vector(15 DOWNTO 0);  -- int16
        M_AXIS_DAC1_TVALID                :   OUT   std_logic;
        M_AXIS_DAC2_TDATA                 :   OUT   std_logic_vector(15 DOWNTO 0);  -- int16
        M_AXIS_DAC2_TVALID                :   OUT   std_logic
        );
END SEL_toTest_src_SEL;


ARCHITECTURE rtl OF SEL_toTest_src_SEL IS

  -- Component Declarations
  COMPONENT SEL_toTest_src_SEL_WRAPPED
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          S_AXIS_ADC1_TDATA               :   IN    std_logic_vector(15 DOWNTO 0);  -- int16
          S_AXIS_ADC1_TVALID              :   IN    std_logic;
          CONTROL_PHASE_COS               :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
          CONTROL_PHASE_SIN               :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
          CONTROL_MAG_SET                 :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
          CONTROL_K_HIGH                  :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
          CONTROL_K_LOW                   :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
          CONTROL_PULSE_WIDTH             :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          CONTROL_PULSE_EN                :   IN    std_logic;
          CONTROL_AUTO_EN                 :   IN    std_logic;
          CONTROL_REP_PERIOD              :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          M_AXIS_DAC1_TDATA               :   OUT   std_logic_vector(15 DOWNTO 0);  -- int16
          M_AXIS_DAC1_TVALID              :   OUT   std_logic;
          M_AXIS_DAC2_TDATA               :   OUT   std_logic_vector(15 DOWNTO 0);  -- int16
          M_AXIS_DAC2_TVALID              :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : SEL_toTest_src_SEL_WRAPPED
    USE ENTITY work.SEL_toTest_src_SEL_WRAPPED(rtl);

  -- Signals
  SIGNAL TVALID                           : std_logic;
  SIGNAL SEL_WRAPPED_M_AXIS_DAC1_TDATA    : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL SEL_WRAPPED_M_AXIS_DAC1_TVALID   : std_logic;
  SIGNAL SEL_WRAPPED_M_AXIS_DAC2_TDATA    : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL SEL_WRAPPED_M_AXIS_DAC2_TVALID   : std_logic;
  SIGNAL TDATA                            : signed(15 DOWNTO 0);  -- int16
  SIGNAL rd_0_reg                         : vector_of_signed16(0 TO 2);  -- sfix16 [3]
  SIGNAL TDATA_1                          : signed(15 DOWNTO 0);  -- int16
  SIGNAL TVALID_1                         : std_logic;
  SIGNAL rd_1_reg                         : std_logic_vector(25 DOWNTO 0);  -- ufix1 [26]
  SIGNAL TVALID_2                         : std_logic;
  SIGNAL TDATA_2                          : signed(15 DOWNTO 0);  -- int16
  SIGNAL rd_2_reg                         : vector_of_signed16(0 TO 31);  -- sfix16 [32]
  SIGNAL TDATA_3                          : signed(15 DOWNTO 0);  -- int16
  SIGNAL TVALID_3                         : std_logic;
  SIGNAL rd_3_reg                         : std_logic_vector(31 DOWNTO 0);  -- ufix1 [32]
  SIGNAL TVALID_4                         : std_logic;

BEGIN
  u_SEL_WRAPPED : SEL_toTest_src_SEL_WRAPPED
    PORT MAP( clk => clk,
              reset => reset,
              S_AXIS_ADC1_TDATA => S_AXIS_ADC1_TDATA,  -- int16
              S_AXIS_ADC1_TVALID => TVALID,
              CONTROL_PHASE_COS => AXI4_LITE_CONTROL_PHASE_COS,  -- sfix18_En16
              CONTROL_PHASE_SIN => AXI4_LITE_CONTROL_PHASE_SIN,  -- sfix18_En16
              CONTROL_MAG_SET => AXI4_LITE_CONTROL_MAG_SET,  -- sfix18_En16
              CONTROL_K_HIGH => AXI4_LITE_CONTROL_K_HIGH,  -- sfix18_En16
              CONTROL_K_LOW => AXI4_LITE_CONTROL_K_LOW,  -- sfix18_En16
              CONTROL_PULSE_WIDTH => AXI4_LITE_CONTROL_PULSE_WIDTH,  -- uint32
              CONTROL_PULSE_EN => AXI4_LITE_CONTROL_PULSE_EN,
              CONTROL_AUTO_EN => AXI4_LITE_CONTROL_AUTO_EN,
              CONTROL_REP_PERIOD => AXI4_LITE_CONTROL_REP_PERIOD,  -- uint32
              M_AXIS_DAC1_TDATA => SEL_WRAPPED_M_AXIS_DAC1_TDATA,  -- int16
              M_AXIS_DAC1_TVALID => SEL_WRAPPED_M_AXIS_DAC1_TVALID,
              M_AXIS_DAC2_TDATA => SEL_WRAPPED_M_AXIS_DAC2_TDATA,  -- int16
              M_AXIS_DAC2_TVALID => SEL_WRAPPED_M_AXIS_DAC2_TVALID
              );

  TVALID <= S_AXIS_ADC1_TVALID;

  TDATA <= signed(SEL_WRAPPED_M_AXIS_DAC1_TDATA);

  rd_0_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        rd_0_reg <= (OTHERS => to_signed(16#0000#, 16));
      ELSE 
        rd_0_reg(0) <= TDATA;
        rd_0_reg(1 TO 2) <= rd_0_reg(0 TO 1);
      END IF;
    END IF;
  END PROCESS rd_0_process;

  TDATA_1 <= rd_0_reg(2);

  M_AXIS_DAC1_TDATA <= std_logic_vector(TDATA_1);

  TVALID_1 <= SEL_WRAPPED_M_AXIS_DAC1_TVALID;

  rd_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        rd_1_reg <= (OTHERS => '0');
      ELSE 
        rd_1_reg(0) <= TVALID_1;
        rd_1_reg(25 DOWNTO 1) <= rd_1_reg(24 DOWNTO 0);
      END IF;
    END IF;
  END PROCESS rd_1_process;

  TVALID_2 <= rd_1_reg(25);

  M_AXIS_DAC1_TVALID <= TVALID_2;

  TDATA_2 <= signed(SEL_WRAPPED_M_AXIS_DAC2_TDATA);

  rd_2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        rd_2_reg <= (OTHERS => to_signed(16#0000#, 16));
      ELSE 
        rd_2_reg(0) <= TDATA_2;
        rd_2_reg(1 TO 31) <= rd_2_reg(0 TO 30);
      END IF;
    END IF;
  END PROCESS rd_2_process;

  TDATA_3 <= rd_2_reg(31);

  M_AXIS_DAC2_TDATA <= std_logic_vector(TDATA_3);

  TVALID_3 <= SEL_WRAPPED_M_AXIS_DAC2_TVALID;

  rd_3_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        rd_3_reg <= (OTHERS => '0');
      ELSE 
        rd_3_reg(0) <= TVALID_3;
        rd_3_reg(31 DOWNTO 1) <= rd_3_reg(30 DOWNTO 0);
      END IF;
    END IF;
  END PROCESS rd_3_process;

  TVALID_4 <= rd_3_reg(31);

  M_AXIS_DAC2_TVALID <= TVALID_4;

END rtl;

