-- -------------------------------------------------------------
-- 
-- File Name: SEL_Reverted\hdlsrc\SEL_test\SEL_toTest_pkg.vhd
-- Created: 2026-07-27 16:15:07
-- 
-- Generated by MATLAB 26.1, HDL Coder 26.1, and Simulink 26.1
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE SEL_toTest_pkg IS
  TYPE vector_of_real IS ARRAY (NATURAL RANGE <>) OF real;
END SEL_toTest_pkg;

