-- -------------------------------------------------------------
-- 
-- File Name: SEL_Reverted\hdlsrc\SEL_test\SEL_toTest_src_SEL_WRAPPED.vhd
-- Created: 2026-07-27 16:14:58
-- 
-- Generated by MATLAB 26.1, HDL Coder 26.1, and Simulink 26.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: SEL_toTest_src_SEL_WRAPPED
-- Source Path: SEL_test/TESTBENCH/SEL/SEL_WRAPPED
-- Hierarchy Level: 1
-- Model version: 1.616
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY SEL_toTest_src_SEL_WRAPPED IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        S_AXIS_ADC1_TDATA                 :   IN    std_logic_vector(15 DOWNTO 0);  -- int16
        S_AXIS_ADC1_TVALID                :   IN    std_logic;
        CONTROL_PHASE_COS                 :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
        CONTROL_PHASE_SIN                 :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
        CONTROL_MAG_SET                   :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
        CONTROL_K_HIGH                    :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
        CONTROL_K_LOW                     :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
        CONTROL_PULSE_WIDTH               :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        CONTROL_PULSE_EN                  :   IN    std_logic;
        CONTROL_AUTO_EN                   :   IN    std_logic;
        CONTROL_REP_PERIOD                :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        M_AXIS_DAC1_TDATA                 :   OUT   std_logic_vector(15 DOWNTO 0);  -- int16
        M_AXIS_DAC1_TVALID                :   OUT   std_logic;
        M_AXIS_DAC2_TDATA                 :   OUT   std_logic_vector(15 DOWNTO 0);  -- int16
        M_AXIS_DAC2_TVALID                :   OUT   std_logic
        );
END SEL_toTest_src_SEL_WRAPPED;


ARCHITECTURE rtl OF SEL_toTest_src_SEL_WRAPPED IS

  -- Component Declarations
  COMPONENT SEL_toTest_src_DSP_LOGIC
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          ADC1_IN_TDATA                   :   IN    std_logic_vector(15 DOWNTO 0);  -- int16
          AXI_LITE_CONTROL_PHASE_COS      :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
          AXI_LITE_CONTROL_PHASE_SIN      :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
          AXI_LITE_CONTROL_MAG_SET        :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
          AXI_LITE_CONTROL_K_HIGH         :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
          AXI_LITE_CONTROL_K_LOW          :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
          AXI_LITE_CONTROL_PULSE_WIDTH    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          AXI_LITE_CONTROL_PULSE_EN       :   IN    std_logic;
          AXI_LITE_CONTROL_AUTO_EN        :   IN    std_logic;
          AXI_LITE_CONTROL_REP_PERIOD     :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          DAC1_OUT_TDATA                  :   OUT   std_logic_vector(15 DOWNTO 0);  -- int16
          DAC1_OUT_TVALID                 :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : SEL_toTest_src_DSP_LOGIC
    USE ENTITY work.SEL_toTest_src_DSP_LOGIC(rtl);

  -- Signals
  SIGNAL DSP_LOGIC_DAC1_OUT_TDATA         : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL DSP_LOGIC_DAC1_OUT_TVALID        : std_logic;

BEGIN
  -- DAC1
  -- DAC2
  -- ADC1
  -- CONTROL

  u_DSP_LOGIC : SEL_toTest_src_DSP_LOGIC
    PORT MAP( clk => clk,
              reset => reset,
              ADC1_IN_TDATA => S_AXIS_ADC1_TDATA,  -- int16
              AXI_LITE_CONTROL_PHASE_COS => CONTROL_PHASE_COS,  -- sfix18_En16
              AXI_LITE_CONTROL_PHASE_SIN => CONTROL_PHASE_SIN,  -- sfix18_En16
              AXI_LITE_CONTROL_MAG_SET => CONTROL_MAG_SET,  -- sfix18_En16
              AXI_LITE_CONTROL_K_HIGH => CONTROL_K_HIGH,  -- sfix18_En16
              AXI_LITE_CONTROL_K_LOW => CONTROL_K_LOW,  -- sfix18_En16
              AXI_LITE_CONTROL_PULSE_WIDTH => CONTROL_PULSE_WIDTH,  -- uint32
              AXI_LITE_CONTROL_PULSE_EN => CONTROL_PULSE_EN,
              AXI_LITE_CONTROL_AUTO_EN => CONTROL_AUTO_EN,
              AXI_LITE_CONTROL_REP_PERIOD => CONTROL_REP_PERIOD,  -- uint32
              DAC1_OUT_TDATA => DSP_LOGIC_DAC1_OUT_TDATA,  -- int16
              DAC1_OUT_TVALID => DSP_LOGIC_DAC1_OUT_TVALID
              );

  M_AXIS_DAC1_TDATA <= DSP_LOGIC_DAC1_OUT_TDATA;

  M_AXIS_DAC1_TVALID <= DSP_LOGIC_DAC1_OUT_TVALID;

  M_AXIS_DAC2_TDATA <= S_AXIS_ADC1_TDATA;

  M_AXIS_DAC2_TVALID <= S_AXIS_ADC1_TVALID;

END rtl;

