-- -------------------------------------------------------------
-- 
-- File Name: SEL_Reverted\hdlsrc\SEL_test\SEL_toTest_src_DEMUX.vhd
-- Created: 2026-07-27 16:14:57
-- 
-- Generated by MATLAB 26.1, HDL Coder 26.1, and Simulink 26.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: SEL_toTest_src_DEMUX
-- Source Path: SEL_test/TESTBENCH/SEL/SEL_WRAPPED/DSP_LOGIC/DEMUX
-- Hierarchy Level: 3
-- Model version: 1.616
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY SEL_toTest_src_DEMUX IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        adc_TDATA                         :   IN    std_logic_vector(15 DOWNTO 0);  -- int16
        I                                 :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En17
        Q                                 :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En17
        valid_o                           :   OUT   std_logic;
        Mix_bus_NSIN_MIX                  :   OUT   std_logic_vector(24 DOWNTO 0);  -- sfix25_En23
        Mix_bus_COS_MIX                   :   OUT   std_logic_vector(24 DOWNTO 0)  -- sfix25_En23
        );
END SEL_toTest_src_DEMUX;


ARCHITECTURE rtl OF SEL_toTest_src_DEMUX IS

  -- Component Declarations
  COMPONENT SEL_toTest_src_NCO_block
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          mix_bus_out_NSIN_MIX            :   OUT   std_logic_vector(24 DOWNTO 0);  -- sfix25_En23
          mix_bus_out_COS_MIX             :   OUT   std_logic_vector(24 DOWNTO 0);  -- sfix25_En23
          valid_out                       :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT SEL_toTest_src_MIX
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          adc_in_TDATA                    :   IN    std_logic_vector(15 DOWNTO 0);  -- int16
          mix_bus_in_NSIN_MIX             :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En23
          mix_bus_in_COS_MIX              :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En23
          valid_in                        :   IN    std_logic;
          Q_mix1                          :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En17
          I_mixed                         :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En17
          mix_bus_out_NSIN_MIX            :   OUT   std_logic_vector(24 DOWNTO 0);  -- sfix25_En23
          mix_bus_out_COS_MIX             :   OUT   std_logic_vector(24 DOWNTO 0);  -- sfix25_En23
          valid_out                       :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : SEL_toTest_src_NCO_block
    USE ENTITY work.SEL_toTest_src_NCO_block(rtl);

  FOR ALL : SEL_toTest_src_MIX
    USE ENTITY work.SEL_toTest_src_MIX(rtl);

  -- Signals
  SIGNAL NCO_mix_bus_out_NSIN_MIX         : std_logic_vector(24 DOWNTO 0);  -- ufix25
  SIGNAL NCO_mix_bus_out_COS_MIX          : std_logic_vector(24 DOWNTO 0);  -- ufix25
  SIGNAL NCO_valid_out                    : std_logic;
  SIGNAL MIX_Q_mix1                       : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL MIX_I_mixed                      : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL MIX_mix_bus_out_NSIN_MIX         : std_logic_vector(24 DOWNTO 0);  -- ufix25
  SIGNAL MIX_mix_bus_out_COS_MIX          : std_logic_vector(24 DOWNTO 0);  -- ufix25
  SIGNAL MIX_valid_out                    : std_logic;

BEGIN
  u_NCO : SEL_toTest_src_NCO_block
    PORT MAP( clk => clk,
              reset => reset,
              mix_bus_out_NSIN_MIX => NCO_mix_bus_out_NSIN_MIX,  -- sfix25_En23
              mix_bus_out_COS_MIX => NCO_mix_bus_out_COS_MIX,  -- sfix25_En23
              valid_out => NCO_valid_out
              );

  u_MIX : SEL_toTest_src_MIX
    PORT MAP( clk => clk,
              reset => reset,
              adc_in_TDATA => adc_TDATA,  -- int16
              mix_bus_in_NSIN_MIX => NCO_mix_bus_out_NSIN_MIX,  -- sfix25_En23
              mix_bus_in_COS_MIX => NCO_mix_bus_out_COS_MIX,  -- sfix25_En23
              valid_in => NCO_valid_out,
              Q_mix1 => MIX_Q_mix1,  -- sfix18_En17
              I_mixed => MIX_I_mixed,  -- sfix18_En17
              mix_bus_out_NSIN_MIX => MIX_mix_bus_out_NSIN_MIX,  -- sfix25_En23
              mix_bus_out_COS_MIX => MIX_mix_bus_out_COS_MIX,  -- sfix25_En23
              valid_out => MIX_valid_out
              );

  I <= MIX_I_mixed;

  Q <= MIX_Q_mix1;

  valid_o <= MIX_valid_out;

  Mix_bus_NSIN_MIX <= MIX_mix_bus_out_NSIN_MIX;

  Mix_bus_COS_MIX <= MIX_mix_bus_out_COS_MIX;

END rtl;

