-- -------------------------------------------------------------
-- 
-- File Name: SEL_Reverted\hdlsrc\SEL_test\SEL_toTest_src_NORMALIZE.vhd
-- Created: 2026-07-27 16:14:58
-- 
-- Generated by MATLAB 26.1, HDL Coder 26.1, and Simulink 26.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: SEL_toTest_src_NORMALIZE
-- Source Path: SEL_test/TESTBENCH/SEL/SEL_WRAPPED/DSP_LOGIC/NORMALIZE
-- Hierarchy Level: 3
-- Model version: 1.616
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.SEL_toTest_src_SEL_pkg.ALL;

ENTITY SEL_toTest_src_NORMALIZE IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        I                                 :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En23
        Q                                 :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En23
        valid                             :   IN    std_logic;
        pulse_bus_K_HIGH                  :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
        pulse_bus_K_LOW                   :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
        pulse_bus_PULSE_WIDTH             :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        pulse_bus_PULSE_EN                :   IN    std_logic;
        pulse_bus_AUTO_EN                 :   IN    std_logic;
        pulse_bus_REP_PERIOD              :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        I_normalized                      :   OUT   std_logic_vector(24 DOWNTO 0);  -- sfix25_En23
        Q_normalized                      :   OUT   std_logic_vector(24 DOWNTO 0);  -- sfix25_En23
        valid_o                           :   OUT   std_logic
        );
END SEL_toTest_src_NORMALIZE;


ARCHITECTURE rtl OF SEL_toTest_src_NORMALIZE IS

  -- Component Declarations
  COMPONENT SEL_toTest_src_SCALE_FACTOR
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          In1                             :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En23
          In2                             :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En23
          Out1                            :   OUT   std_logic_vector(17 DOWNTO 0)  -- ufix18_En4
          );
  END COMPONENT;

  COMPONENT SEL_toTest_src_MATLAB_Function_block
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          START                           :   IN    std_logic;
          AUTO_EN                         :   IN    std_logic;
          PULSE_WIDTH                     :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          REP_PERIOD                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          K_HIGH                          :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
          K_LOW                           :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
          k_pulse                         :   OUT   std_logic_vector(17 DOWNTO 0)  -- sfix18_En16
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : SEL_toTest_src_SCALE_FACTOR
    USE ENTITY work.SEL_toTest_src_SCALE_FACTOR(rtl);

  FOR ALL : SEL_toTest_src_MATLAB_Function_block
    USE ENTITY work.SEL_toTest_src_MATLAB_Function_block(rtl);

  -- Signals
  SIGNAL I_signed                         : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL rd_0_reg                         : vector_of_signed25(0 TO 11);  -- sfix25 [12]
  SIGNAL I_1                              : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL I_2                              : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL SCALE_FACTOR_Out1                : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL SCALE_FACTOR_Out1_unsigned       : unsigned(17 DOWNTO 0);  -- ufix18_En4
  SIGNAL SCALE_FACTOR_Out1_1              : unsigned(17 DOWNTO 0);  -- ufix18_En4
  SIGNAL PULSE_EN                         : std_logic;
  SIGNAL AUTO_EN                          : std_logic;
  SIGNAL PULSE_WIDTH                      : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL PULSE_WIDTH_1                    : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL REP_PERIOD                       : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL REP_PERIOD_1                     : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL K_HIGH                           : signed(17 DOWNTO 0);  -- sfix18_En16
  SIGNAL K_HIGH_1                         : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL K_LOW                            : signed(17 DOWNTO 0);  -- sfix18_En16
  SIGNAL K_LOW_1                          : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL k_pulse                          : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL k_pulse_signed                   : signed(17 DOWNTO 0);  -- sfix18_En16
  SIGNAL rd_1_reg                         : vector_of_signed18(0 TO 13);  -- sfix18 [14]
  SIGNAL k_pulse_1                        : signed(17 DOWNTO 0);  -- sfix18_En16
  SIGNAL k_pulse_2                        : signed(17 DOWNTO 0);  -- sfix18_En16
  SIGNAL Product2_cast                    : signed(18 DOWNTO 0);  -- sfix19_En4
  SIGNAL Product2_mul_temp                : signed(36 DOWNTO 0);  -- sfix37_En20
  SIGNAL Product2_out1                    : signed(35 DOWNTO 0);  -- sfix36_En20
  SIGNAL Product2_out1_1                  : signed(35 DOWNTO 0);  -- sfix36_En20
  SIGNAL Product2_out1_2                  : unsigned(17 DOWNTO 0);  -- ufix18_En11
  SIGNAL Product2_out1_3                  : unsigned(17 DOWNTO 0);  -- ufix18_En11
  SIGNAL Product_cast                     : signed(18 DOWNTO 0);  -- sfix19_En11
  SIGNAL Product_mul_temp                 : signed(43 DOWNTO 0);  -- sfix44_En34
  SIGNAL Product_out1                     : signed(42 DOWNTO 0);  -- sfix43_En34
  SIGNAL Product_out1_1                   : signed(42 DOWNTO 0);  -- sfix43_En34
  SIGNAL Product_out1_2                   : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL Q_signed                         : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL rd_2_reg                         : vector_of_signed25(0 TO 9);  -- sfix25 [10]
  SIGNAL Q_1                              : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL Q_2                              : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL Product1_cast                    : signed(18 DOWNTO 0);  -- sfix19_En11
  SIGNAL Product1_mul_temp                : signed(43 DOWNTO 0);  -- sfix44_En34
  SIGNAL Product1_out1                    : signed(42 DOWNTO 0);  -- sfix43_En34
  SIGNAL Product1_out1_1                  : signed(42 DOWNTO 0);  -- sfix43_En34
  SIGNAL Product1_out1_2                  : signed(24 DOWNTO 0);  -- sfix25_En23

BEGIN
  -- A_norm = A * scale_out

  u_SCALE_FACTOR : SEL_toTest_src_SCALE_FACTOR
    PORT MAP( clk => clk,
              reset => reset,
              In1 => I,  -- sfix25_En23
              In2 => Q,  -- sfix25_En23
              Out1 => SCALE_FACTOR_Out1  -- ufix18_En4
              );

  u_MATLAB_Function : SEL_toTest_src_MATLAB_Function_block
    PORT MAP( clk => clk,
              reset => reset,
              START => PULSE_EN,
              AUTO_EN => AUTO_EN,
              PULSE_WIDTH => PULSE_WIDTH_1,  -- uint32
              REP_PERIOD => REP_PERIOD_1,  -- uint32
              K_HIGH => K_HIGH_1,  -- sfix18_En16
              K_LOW => K_LOW_1,  -- sfix18_En16
              k_pulse => k_pulse  -- sfix18_En16
              );

  I_signed <= signed(I);

  rd_0_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        rd_0_reg <= (OTHERS => to_signed(16#0000000#, 25));
      ELSE 
        rd_0_reg(0) <= I_signed;
        rd_0_reg(1 TO 11) <= rd_0_reg(0 TO 10);
      END IF;
    END IF;
  END PROCESS rd_0_process;

  I_1 <= rd_0_reg(11);

  HwModeRegister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        I_2 <= to_signed(16#0000000#, 25);
      ELSE 
        I_2 <= I_1;
      END IF;
    END IF;
  END PROCESS HwModeRegister_process;


  SCALE_FACTOR_Out1_unsigned <= unsigned(SCALE_FACTOR_Out1);

  HwModeRegister4_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        SCALE_FACTOR_Out1_1 <= to_unsigned(16#00000#, 18);
      ELSE 
        SCALE_FACTOR_Out1_1 <= SCALE_FACTOR_Out1_unsigned;
      END IF;
    END IF;
  END PROCESS HwModeRegister4_process;


  PULSE_EN <= pulse_bus_PULSE_EN;

  AUTO_EN <= pulse_bus_AUTO_EN;

  PULSE_WIDTH <= unsigned(pulse_bus_PULSE_WIDTH);

  PULSE_WIDTH_1 <= std_logic_vector(PULSE_WIDTH);

  REP_PERIOD <= unsigned(pulse_bus_REP_PERIOD);

  REP_PERIOD_1 <= std_logic_vector(REP_PERIOD);

  K_HIGH <= signed(pulse_bus_K_HIGH);

  K_HIGH_1 <= std_logic_vector(K_HIGH);

  K_LOW <= signed(pulse_bus_K_LOW);

  K_LOW_1 <= std_logic_vector(K_LOW);

  k_pulse_signed <= signed(k_pulse);

  rd_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        rd_1_reg <= (OTHERS => to_signed(16#00000#, 18));
      ELSE 
        rd_1_reg(0) <= k_pulse_signed;
        rd_1_reg(1 TO 13) <= rd_1_reg(0 TO 12);
      END IF;
    END IF;
  END PROCESS rd_1_process;

  k_pulse_1 <= rd_1_reg(13);

  HwModeRegister5_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        k_pulse_2 <= to_signed(16#00000#, 18);
      ELSE 
        k_pulse_2 <= k_pulse_1;
      END IF;
    END IF;
  END PROCESS HwModeRegister5_process;


  Product2_cast <= signed(resize(SCALE_FACTOR_Out1_1, 19));
  Product2_mul_temp <= Product2_cast * k_pulse_2;
  Product2_out1 <= Product2_mul_temp(35 DOWNTO 0);

  PipelineRegister2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Product2_out1_1 <= to_signed(0, 36);
      ELSE 
        Product2_out1_1 <= Product2_out1;
      END IF;
    END IF;
  END PROCESS PipelineRegister2_process;


  
  Product2_out1_2 <= "111111111111111111" WHEN ((Product2_out1_1(35) = '0') AND (Product2_out1_1(34 DOWNTO 27) /= "00000000")) OR ((Product2_out1_1(35) = '0') AND (Product2_out1_1(26 DOWNTO 9) = "111111111111111111")) ELSE
      "000000000000000000" WHEN Product2_out1_1(35) = '1' ELSE
      unsigned(Product2_out1_1(26 DOWNTO 9)) + ('0' & Product2_out1_1(8));

  reduced_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Product2_out1_3 <= to_unsigned(16#00000#, 18);
      ELSE 
        Product2_out1_3 <= Product2_out1_2;
      END IF;
    END IF;
  END PROCESS reduced_process;


  Product_cast <= signed(resize(Product2_out1_3, 19));
  Product_mul_temp <= I_2 * Product_cast;
  Product_out1 <= Product_mul_temp(42 DOWNTO 0);

  PipelineRegister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Product_out1_1 <= to_signed(0, 43);
      ELSE 
        Product_out1_1 <= Product_out1;
      END IF;
    END IF;
  END PROCESS PipelineRegister_process;


  
  Product_out1_2 <= "0111111111111111111111111" WHEN ((Product_out1_1(42) = '0') AND (Product_out1_1(41 DOWNTO 35) /= "0000000")) OR ((Product_out1_1(42) = '0') AND (Product_out1_1(35 DOWNTO 11) = "0111111111111111111111111")) ELSE
      "1000000000000000000000000" WHEN (Product_out1_1(42) = '1') AND (Product_out1_1(41 DOWNTO 35) /= "1111111") ELSE
      Product_out1_1(35 DOWNTO 11) + ('0' & Product_out1_1(10));

  I_normalized <= std_logic_vector(Product_out1_2);

  Q_signed <= signed(Q);

  rd_2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        rd_2_reg <= (OTHERS => to_signed(16#0000000#, 25));
      ELSE 
        rd_2_reg(0) <= Q_signed;
        rd_2_reg(1 TO 9) <= rd_2_reg(0 TO 8);
      END IF;
    END IF;
  END PROCESS rd_2_process;

  Q_1 <= rd_2_reg(9);

  HwModeRegister3_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Q_2 <= to_signed(16#0000000#, 25);
      ELSE 
        Q_2 <= Q_1;
      END IF;
    END IF;
  END PROCESS HwModeRegister3_process;


  Product1_cast <= signed(resize(Product2_out1_3, 19));
  Product1_mul_temp <= Product1_cast * Q_2;
  Product1_out1 <= Product1_mul_temp(42 DOWNTO 0);

  PipelineRegister1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Product1_out1_1 <= to_signed(0, 43);
      ELSE 
        Product1_out1_1 <= Product1_out1;
      END IF;
    END IF;
  END PROCESS PipelineRegister1_process;


  
  Product1_out1_2 <= "0111111111111111111111111" WHEN ((Product1_out1_1(42) = '0') AND (Product1_out1_1(41 DOWNTO 35) /= "0000000")) OR ((Product1_out1_1(42) = '0') AND (Product1_out1_1(35 DOWNTO 11) = "0111111111111111111111111")) ELSE
      "1000000000000000000000000" WHEN (Product1_out1_1(42) = '1') AND (Product1_out1_1(41 DOWNTO 35) /= "1111111") ELSE
      Product1_out1_1(35 DOWNTO 11) + ('0' & Product1_out1_1(10));

  Q_normalized <= std_logic_vector(Product1_out1_2);

  valid_o <= valid;

END rtl;

