-- -------------------------------------------------------------
-- 
-- File Name: SEL_Reverted\hdlsrc\SEL_test\SEL_toTest_src_NCO.vhd
-- Created: 2026-07-27 16:14:57
-- 
-- Generated by MATLAB 26.1, HDL Coder 26.1, and Simulink 26.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: SEL_toTest_src_NCO
-- Source Path: SEL_test/TESTBENCH/SEL/SEL_WRAPPED/DSP_LOGIC/DEMUX/NCO/NCO
-- Hierarchy Level: 5
-- Model version: 1.616
-- 
-- NCO
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.SEL_toTest_src_SEL_pkg.ALL;

ENTITY SEL_toTest_src_NCO IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        inc                               :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        validIn                           :   IN    std_logic;
        phase                             :   OUT   std_logic_vector(13 DOWNTO 0);  -- ufix14
        validOut                          :   OUT   std_logic
        );
END SEL_toTest_src_NCO;


ARCHITECTURE rtl OF SEL_toTest_src_NCO IS

  -- Component Declarations
  COMPONENT SEL_toTest_src_DitherGen
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          validIn                         :   IN    std_logic;
          dither                          :   OUT   std_logic_vector(3 DOWNTO 0)  -- ufix4
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : SEL_toTest_src_DitherGen
    USE ENTITY work.SEL_toTest_src_DitherGen(rtl);

  -- Signals
  SIGNAL outsel_reg_reg                   : std_logic_vector(4 DOWNTO 0);  -- ufix1 [5]
  SIGNAL outsel                           : std_logic;
  SIGNAL phasezero                        : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL const0                           : signed(31 DOWNTO 0);  -- sfix32
  SIGNAL inc_unsigned                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL pInc                             : signed(31 DOWNTO 0);  -- sfix32
  SIGNAL validPInc                        : signed(31 DOWNTO 0);  -- sfix32
  SIGNAL accphase_reg                     : signed(31 DOWNTO 0);  -- sfix32
  SIGNAL addpInc                          : signed(31 DOWNTO 0);  -- sfix32
  SIGNAL pOffset                          : signed(31 DOWNTO 0);  -- sfix32
  SIGNAL accoffset                        : signed(31 DOWNTO 0);  -- sfix32
  SIGNAL accoffsete_reg                   : signed(31 DOWNTO 0);  -- sfix32
  SIGNAL dither                           : std_logic_vector(3 DOWNTO 0);  -- ufix4
  SIGNAL dither_unsigned                  : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL casteddither                     : signed(31 DOWNTO 0);  -- sfix32
  SIGNAL dither_reg                       : signed(31 DOWNTO 0);  -- sfix32
  SIGNAL accumulator                      : signed(31 DOWNTO 0);  -- sfix32
  SIGNAL accQuantized                     : unsigned(13 DOWNTO 0);  -- ufix14_E18
  SIGNAL quantacc_s                       : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL OutPhaseRegister_reg             : vector_of_unsigned14(0 TO 3);  -- ufix14 [4]
  SIGNAL phaseDly                         : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL phaseOut                         : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL phase_tmp                        : unsigned(13 DOWNTO 0);  -- ufix14

BEGIN
  u_dither_inst : SEL_toTest_src_DitherGen
    PORT MAP( clk => clk,
              reset => reset,
              validIn => validIn,
              dither => dither  -- ufix4
              );

  outsel_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        outsel_reg_reg <= (OTHERS => '0');
      ELSE 
        outsel_reg_reg(0) <= validIn;
        outsel_reg_reg(4 DOWNTO 1) <= outsel_reg_reg(3 DOWNTO 0);
      END IF;
    END IF;
  END PROCESS outsel_reg_process;

  outsel <= outsel_reg_reg(4);

  phasezero <= to_unsigned(16#0000#, 14);

  -- Constant Zero
  const0 <= to_signed(0, 32);

  inc_unsigned <= unsigned(inc);

  pInc <= signed(inc_unsigned);

  
  validPInc <= const0 WHEN validIn = '0' ELSE
      pInc;

  -- Add phase increment
  addpInc <= accphase_reg + validPInc;

  -- Phase increment accumulator register
  AccPhaseRegister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        accphase_reg <= to_signed(0, 32);
      ELSE 
        accphase_reg <= addpInc;
      END IF;
    END IF;
  END PROCESS AccPhaseRegister_process;


  pOffset <= to_signed(0, 32);

  -- Add phase offset
  accoffset <= accphase_reg + pOffset;

  -- Phase offset accumulator register
  AccOffsetRegister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        accoffsete_reg <= to_signed(0, 32);
      ELSE 
        accoffsete_reg <= accoffset;
      END IF;
    END IF;
  END PROCESS AccOffsetRegister_process;


  dither_unsigned <= unsigned(dither);

  casteddither <= signed(resize(dither_unsigned, 32));

  -- Dither input register
  DitherRegister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        dither_reg <= to_signed(0, 32);
      ELSE 
        dither_reg <= casteddither;
      END IF;
    END IF;
  END PROCESS DitherRegister_process;


  -- Add dither
  accumulator <= accoffsete_reg + dither_reg;

  -- Phase quantization
  accQuantized <= unsigned(accumulator(31 DOWNTO 18));

  quantacc_s <= accQuantized;

  OutPhaseRegister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        OutPhaseRegister_reg <= (OTHERS => to_unsigned(16#0000#, 14));
      ELSE 
        OutPhaseRegister_reg(0) <= quantacc_s;
        OutPhaseRegister_reg(1 TO 3) <= OutPhaseRegister_reg(0 TO 2);
      END IF;
    END IF;
  END PROCESS OutPhaseRegister_process;

  phaseDly <= OutPhaseRegister_reg(3);

  
  phaseOut <= phasezero WHEN outsel = '0' ELSE
      phaseDly;

  -- Output phase register
  OutPhaseRegister_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        phase_tmp <= to_unsigned(16#0000#, 14);
      ELSE 
        phase_tmp <= phaseOut;
      END IF;
    END IF;
  END PROCESS OutPhaseRegister_1_process;


  phase <= std_logic_vector(phase_tmp);

  -- validOut register
  validOut_reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        validOut <= '0';
      ELSE 
        validOut <= outsel;
      END IF;
    END IF;
  END PROCESS validOut_reg_process;


END rtl;

