-- -------------------------------------------------------------
-- 
-- File Name: SEL_Reverted\hdlsrc\SEL_test\SEL_toTest_src_MATLAB_Function1.vhd
-- Created: 2026-07-27 16:14:58
-- 
-- Generated by MATLAB 26.1, HDL Coder 26.1, and Simulink 26.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: SEL_toTest_src_MATLAB_Function1
-- Source Path: SEL_test/TESTBENCH/SEL/SEL_WRAPPED/DSP_LOGIC/NORMALIZE/SCALE_FACTOR/rSqrt/MATLAB Function1
-- Hierarchy Level: 6
-- Model version: 1.616
-- 
-- #codegen
-- lut_val_16bit : ufix16_en15 (16 bits from LUT)
-- m              : uint16 [0..13]
-- K              : ufix18_en4 (18-bit Word Length for DSP slice, max gain 16383.9)
-- 1. Extract raw 16-bit integer into 32-bit container to prevent shift overflow
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY SEL_toTest_src_MATLAB_Function1 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        lut_val_16bit                     :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16_En15
        m                                 :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        K                                 :   OUT   std_logic_vector(17 DOWNTO 0)  -- ufix18_En4
        );
END SEL_toTest_src_MATLAB_Function1;


ARCHITECTURE rtl OF SEL_toTest_src_MATLAB_Function1 IS

  -- Signals
  SIGNAL lut_val_16bit_unsigned           : unsigned(15 DOWNTO 0);  -- ufix16_En15
  SIGNAL out0                             : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL N_lut                            : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL m_unsigned                       : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL m_1                              : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL out0_1                           : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL out0_2                           : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL N_shifted                        : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL N_final                          : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL raw18                            : unsigned(17 DOWNTO 0);  -- ufix18
  SIGNAL K_tmp                            : unsigned(17 DOWNTO 0);  -- ufix18_En4

BEGIN
  lut_val_16bit_unsigned <= unsigned(lut_val_16bit);

  out0 <= lut_val_16bit_unsigned;

  N_lut <= resize(out0, 32);

  m_unsigned <= unsigned(m);

  rd_0_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        m_1 <= to_unsigned(16#0000#, 16);
      ELSE 
        m_1 <= m_unsigned;
      END IF;
    END IF;
  END PROCESS rd_0_process;


  -- 2. Dynamic left shift by m (m ranges from 0 to 13)
  out0_1 <= resize(m_1, 32);

  rd_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        out0_2 <= to_unsigned(0, 32);
      ELSE 
        out0_2 <= out0_1;
      END IF;
    END IF;
  END PROCESS rd_1_process;


  N_shifted <= N_lut sll to_integer(out0_2);

  -- 3. Truncate 11 LSBs to transition from en15 -> en4 (15 - 4 = 11)
  N_final <= SHIFT_RIGHT(N_shifted, 11);

  -- 4. Store in 18-bit container & re-interpret bit pattern as ufix18_en4
  
  raw18 <= "111111111111111111" WHEN N_final(31 DOWNTO 18) /= "00000000000000" ELSE
      N_final(17 DOWNTO 0);

  K_tmp <= raw18;

  K <= std_logic_vector(K_tmp);

END rtl;

