-- -------------------------------------------------------------
-- 
-- File Name: SEL_Reverted\hdlsrc\SEL_test\SEL_toTest_src_MATLAB_Function_block.vhd
-- Created: 2026-07-27 16:14:58
-- 
-- Generated by MATLAB 26.1, HDL Coder 26.1, and Simulink 26.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: SEL_toTest_src_MATLAB_Function_block
-- Source Path: SEL_test/TESTBENCH/SEL/SEL_WRAPPED/DSP_LOGIC/NORMALIZE/MATLAB Function
-- Hierarchy Level: 4
-- Model version: 1.616
-- 
-- #codegen
-- 
-- Configurable Hardware Pulse Generator for SEL Loop Control
-- Outputs k_pulse to scale normalized I/Q vectors without breaking phase lock.
-- 
-- Inputs:
--   START       : Single-shot trigger (PULSE_EN) from AXI register (Boolean)
--   AUTO_EN     : Continuous repeating mode toggle (Boolean)
--   PULSE_WIDTH : Pulse ON duration in clock cycles (uint32)
--   REP_PERIOD  : Total period (ON + OFF) in clock cycles (uint32)
--   K_HIGH      : Pulse ON scale factor, typical 1.0 (sfix18_En16)
--   K_LOW       : Pulse OFF scale factor, e.g., 0.0 or 0.01 keep-alive (sfix18_En16)
-- 
-- Output:
--   k_pulse     : Pulsed multiplier value (sfix18_En16)
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY SEL_toTest_src_MATLAB_Function_block IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        START                             :   IN    std_logic;
        AUTO_EN                           :   IN    std_logic;
        PULSE_WIDTH                       :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        REP_PERIOD                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        K_HIGH                            :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
        K_LOW                             :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
        k_pulse                           :   OUT   std_logic_vector(17 DOWNTO 0)  -- sfix18_En16
        );
END SEL_toTest_src_MATLAB_Function_block;


ARCHITECTURE rtl OF SEL_toTest_src_MATLAB_Function_block IS

  -- Signals
  SIGNAL out0                             : std_logic;
  SIGNAL out0_1                           : std_logic;
  SIGNAL start_pulse                      : std_logic;
  SIGNAL REP_PERIOD_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL out0_2                           : std_logic;
  SIGNAL out0_3                           : std_logic;
  SIGNAL auto_trigger                     : std_logic;
  SIGNAL rep_count                        : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL const_expression                 : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL out0_4                           : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL rep_count_1                      : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL rep_count_2                      : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL rep_count_3                      : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL out0_5                           : std_logic;
  SIGNAL rep_count_4                      : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL rep_count_5                      : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL auto_trigger_1                   : std_logic;
  SIGNAL auto_trigger_2                   : std_logic;
  SIGNAL auto_trigger_3                   : std_logic;
  SIGNAL out0_6                           : std_logic;
  SIGNAL pulse_count                      : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL PULSE_WIDTH_unsigned             : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL PULSE_WIDTH_1                    : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL pulse_active                     : std_logic;
  SIGNAL pulse_active_1                   : std_logic;
  SIGNAL pulse_count_1                    : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL pulse_count_2                    : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL out0_7                           : std_logic;
  SIGNAL pulse_count_3                    : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL pulse_active_2                   : std_logic;
  SIGNAL pulse_count_4                    : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL pulse_count_5                    : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL pulse_active_3                   : std_logic;
  SIGNAL pulse_active_4                   : std_logic;
  SIGNAL pulse_active_5                   : std_logic;
  SIGNAL K_LOW_signed                     : signed(17 DOWNTO 0);  -- sfix18_En16
  SIGNAL K_LOW_1                          : signed(17 DOWNTO 0);  -- sfix18_En16
  SIGNAL K_HIGH_signed                    : signed(17 DOWNTO 0);  -- sfix18_En16
  SIGNAL K_HIGH_1                         : signed(17 DOWNTO 0);  -- sfix18_En16
  SIGNAL k_pulse_1                        : signed(17 DOWNTO 0);  -- sfix18_En16
  SIGNAL k_pulse_tmp                      : signed(17 DOWNTO 0);  -- sfix18_En16

BEGIN
  -------------------------------------------------------------------------
  -- 1. Trigger Detection
  -------------------------------------------------------------------------
  -- Single-shot rising edge trigger
  out0 <=  NOT START;

  rd_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        out0_1 <= '0';
      ELSE 
        out0_1 <= out0;
      END IF;
    END IF;
  END PROCESS rd_1_process;


  start_pulse <= START AND out0_1;

  REP_PERIOD_unsigned <= unsigned(REP_PERIOD);

  
  out0_2 <= '1' WHEN REP_PERIOD_unsigned > to_unsigned(0, 32) ELSE
      '0';

  out0_3 <= AUTO_EN AND out0_2;

  auto_trigger <= '0';

  rep_count <= to_unsigned(0, 32);

  const_expression <= to_unsigned(1, 32);

  out0_4 <= REP_PERIOD_unsigned - const_expression;

  rep_count_2 <= rep_count_1 + const_expression;

  rd_2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        rep_count_3 <= to_unsigned(0, 32);
      ELSE 
        rep_count_3 <= rep_count_2;
      END IF;
    END IF;
  END PROCESS rd_2_process;


  
  rep_count_4 <= rep_count_3 WHEN out0_5 = '0' ELSE
      rep_count;

  -- Continuous repetition auto-trigger
  
  rep_count_1 <= rep_count WHEN out0_3 = '0' ELSE
      rep_count_4;

  rd_3_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        rep_count_5 <= to_unsigned(0, 32);
      ELSE 
        rep_count_5 <= rep_count_1;
      END IF;
    END IF;
  END PROCESS rd_3_process;


  
  out0_5 <= '1' WHEN rep_count_5 >= out0_4 ELSE
      '0';

  auto_trigger_1 <= '1';

  
  auto_trigger_2 <= auto_trigger WHEN out0_5 = '0' ELSE
      auto_trigger_1;

  -- Continuous repetition auto-trigger
  
  auto_trigger_3 <= auto_trigger WHEN out0_3 = '0' ELSE
      auto_trigger_2;

  out0_6 <= start_pulse OR auto_trigger_3;

  pulse_count <= to_unsigned(0, 32);

  PULSE_WIDTH_unsigned <= unsigned(PULSE_WIDTH);

  rd_4_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        PULSE_WIDTH_1 <= to_unsigned(0, 32);
      ELSE 
        PULSE_WIDTH_1 <= PULSE_WIDTH_unsigned;
      END IF;
    END IF;
  END PROCESS rd_4_process;


  pulse_active <= '0';

  pulse_active_1 <= '1';

  pulse_count_2 <= pulse_count_1 + const_expression;

  
  pulse_count_3 <= pulse_count WHEN out0_7 = '0' ELSE
      pulse_count_2;

  -------------------------------------------------------------------------
  -- 2. Pulse Output State Machine
  -------------------------------------------------------------------------
  
  pulse_count_4 <= pulse_count_1 WHEN pulse_active_2 = '0' ELSE
      pulse_count_3;

  -- Combined trigger condition
  
  pulse_count_5 <= pulse_count_4 WHEN out0_6 = '0' ELSE
      pulse_count;

  rd_6_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        pulse_count_1 <= to_unsigned(0, 32);
      ELSE 
        pulse_count_1 <= pulse_count_5;
      END IF;
    END IF;
  END PROCESS rd_6_process;


  
  out0_7 <= '1' WHEN pulse_count_1 < PULSE_WIDTH_1 ELSE
      '0';

  
  pulse_active_3 <= pulse_active WHEN out0_7 = '0' ELSE
      pulse_active_2;

  -------------------------------------------------------------------------
  -- 2. Pulse Output State Machine
  -------------------------------------------------------------------------
  
  pulse_active_4 <= pulse_active_2 WHEN pulse_active_2 = '0' ELSE
      pulse_active_3;

  -- Combined trigger condition
  
  pulse_active_5 <= pulse_active_4 WHEN out0_6 = '0' ELSE
      pulse_active_1;

  rd_5_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        pulse_active_2 <= '0';
      ELSE 
        pulse_active_2 <= pulse_active_5;
      END IF;
    END IF;
  END PROCESS rd_5_process;


  K_LOW_signed <= signed(K_LOW);

  rd_7_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        K_LOW_1 <= to_signed(16#00000#, 18);
      ELSE 
        K_LOW_1 <= K_LOW_signed;
      END IF;
    END IF;
  END PROCESS rd_7_process;


  K_HIGH_signed <= signed(K_HIGH);

  rd_0_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        K_HIGH_1 <= to_signed(16#00000#, 18);
      ELSE 
        K_HIGH_1 <= K_HIGH_signed;
      END IF;
    END IF;
  END PROCESS rd_0_process;


  
  k_pulse_1 <= K_LOW_1 WHEN out0_7 = '0' ELSE
      K_HIGH_1;

  -------------------------------------------------------------------------
  -- 2. Pulse Output State Machine
  -------------------------------------------------------------------------
  
  k_pulse_tmp <= K_LOW_1 WHEN pulse_active_2 = '0' ELSE
      k_pulse_1;

  k_pulse <= std_logic_vector(k_pulse_tmp);

END rtl;

