-- -------------------------------------------------------------
-- 
-- File Name: SEL_Reverted\hdlsrc\SEL_test\SEL_toTest_src_Biquad_Filter1.vhd
-- Created: 2026-07-27 16:14:57
-- 
-- Generated by MATLAB 26.1, HDL Coder 26.1, and Simulink 26.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: SEL_toTest_src_Biquad_Filter1
-- Source Path: SEL_test/TESTBENCH/SEL/SEL_WRAPPED/DSP_LOGIC/LPF/Biquad Filter1
-- Hierarchy Level: 4
-- Model version: 1.616
-- 
-- Biquad Filter
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY SEL_toTest_src_Biquad_Filter1 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        dataIn                            :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En17
        validIn                           :   IN    std_logic;
        dataOut                           :   OUT   std_logic_vector(24 DOWNTO 0)  -- sfix25_En23
        );
END SEL_toTest_src_Biquad_Filter1;


ARCHITECTURE rtl OF SEL_toTest_src_Biquad_Filter1 IS

  -- Component Declarations
  COMPONENT SEL_toTest_src_BiquadPipeSection1_block
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          dataIn                          :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En23
          validIn                         :   IN    std_logic;
          dataOut                         :   OUT   std_logic_vector(24 DOWNTO 0);  -- sfix25_En23
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : SEL_toTest_src_BiquadPipeSection1_block
    USE ENTITY work.SEL_toTest_src_BiquadPipeSection1_block(rtl);

  -- Signals
  SIGNAL dataIn_signed                    : signed(17 DOWNTO 0);  -- sfix18_En17
  SIGNAL sec0reg                          : signed(17 DOWNTO 0);  -- sfix18_En17
  SIGNAL sec0mul                          : signed(42 DOWNTO 0);  -- sfix43_En40
  SIGNAL sec0mulreg                       : signed(42 DOWNTO 0);  -- sfix43_En40
  SIGNAL sec0dtc                          : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL sec0out                          : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL sec0validreg                     : std_logic;
  SIGNAL sec0mulvalidreg                  : std_logic;
  SIGNAL sec0validout                     : std_logic;
  SIGNAL sec1out                          : std_logic_vector(24 DOWNTO 0);  -- ufix25
  SIGNAL sec1validout                     : std_logic;
  SIGNAL sec1mulvalidreg                  : std_logic;
  SIGNAL sec1validout_1                   : std_logic;
  SIGNAL zerooutconst                     : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL sec1out_signed                   : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL sec1mul                          : signed(49 DOWNTO 0);  -- sfix50_En46
  SIGNAL sec1mulreg                       : signed(49 DOWNTO 0);  -- sfix50_En46
  SIGNAL sec1dtc                          : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL sec1out_1                        : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL preout                           : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL dataOut_tmp                      : signed(24 DOWNTO 0);  -- sfix25_En23

BEGIN
  u_BiquadSection1_inst : SEL_toTest_src_BiquadPipeSection1_block
    PORT MAP( clk => clk,
              reset => reset,
              dataIn => std_logic_vector(sec0out),  -- sfix25_En23
              validIn => sec0validout,
              dataOut => sec1out,  -- sfix25_En23
              validOut => sec1validout
              );

  dataIn_signed <= signed(dataIn);

  sec0dataregister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        sec0reg <= to_signed(16#00000#, 18);
      ELSE 
        sec0reg <= dataIn_signed;
      END IF;
    END IF;
  END PROCESS sec0dataregister_process;


  sec0mul <= to_signed(16#006470C#, 25) * sec0reg;

  sec0muldataregister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        sec0mulreg <= to_signed(0, 43);
      ELSE 
        sec0mulreg <= sec0mul;
      END IF;
    END IF;
  END PROCESS sec0muldataregister_process;


  
  sec0dtc <= "0111111111111111111111111" WHEN ((sec0mulreg(42) = '0') AND (sec0mulreg(41) /= '0')) OR ((sec0mulreg(42) = '0') AND (sec0mulreg(41 DOWNTO 17) = "0111111111111111111111111")) ELSE
      "1000000000000000000000000" WHEN (sec0mulreg(42) = '1') AND (sec0mulreg(41) /= '1') ELSE
      sec0mulreg(41 DOWNTO 17) + ('0' & sec0mulreg(16));

  sec0OutRegister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        sec0out <= to_signed(16#0000000#, 25);
      ELSE 
        sec0out <= sec0dtc;
      END IF;
    END IF;
  END PROCESS sec0OutRegister_process;


  sec0validregister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        sec0validreg <= '0';
      ELSE 
        sec0validreg <= validIn;
      END IF;
    END IF;
  END PROCESS sec0validregister_process;


  sec0mulvalidregister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        sec0mulvalidreg <= '0';
      ELSE 
        sec0mulvalidreg <= sec0validreg;
      END IF;
    END IF;
  END PROCESS sec0mulvalidregister_process;


  sec0validoutregister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        sec0validout <= '0';
      ELSE 
        sec0validout <= sec0mulvalidreg;
      END IF;
    END IF;
  END PROCESS sec0validoutregister_process;


  sec1mulvalidregister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        sec1mulvalidreg <= '0';
      ELSE 
        sec1mulvalidreg <= sec1validout;
      END IF;
    END IF;
  END PROCESS sec1mulvalidregister_process;


  sec1validoutregister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        sec1validout_1 <= '0';
      ELSE 
        sec1validout_1 <= sec1mulvalidreg;
      END IF;
    END IF;
  END PROCESS sec1validoutregister_process;


  zerooutconst <= to_signed(16#0000000#, 25);

  sec1out_signed <= signed(sec1out);

  sec1mul <= resize(sec1out_signed & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 50);

  sec1muldataregister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        sec1mulreg <= to_signed(0, 50);
      ELSE 
        sec1mulreg <= sec1mul;
      END IF;
    END IF;
  END PROCESS sec1muldataregister_process;


  
  sec1dtc <= "0111111111111111111111111" WHEN ((sec1mulreg(49) = '0') AND (sec1mulreg(48 DOWNTO 47) /= "00")) OR ((sec1mulreg(49) = '0') AND (sec1mulreg(47 DOWNTO 23) = "0111111111111111111111111")) ELSE
      "1000000000000000000000000" WHEN (sec1mulreg(49) = '1') AND (sec1mulreg(48 DOWNTO 47) /= "11") ELSE
      sec1mulreg(47 DOWNTO 23) + ('0' & sec1mulreg(22));

  sec1OutRegister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        sec1out_1 <= to_signed(16#0000000#, 25);
      ELSE 
        sec1out_1 <= sec1dtc;
      END IF;
    END IF;
  END PROCESS sec1OutRegister_process;


  
  preout <= zerooutconst WHEN sec1validout_1 = '0' ELSE
      sec1out_1;

  OutRegister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        dataOut_tmp <= to_signed(16#0000000#, 25);
      ELSE 
        dataOut_tmp <= preout;
      END IF;
    END IF;
  END PROCESS OutRegister_process;


  dataOut <= std_logic_vector(dataOut_tmp);

END rtl;

