-- -------------------------------------------------------------
-- 
-- File Name: SEL_Reverted\hdlsrc\SEL_test\SEL_toTest_src_NCO_block.vhd
-- Created: 2026-07-27 16:14:57
-- 
-- Generated by MATLAB 26.1, HDL Coder 26.1, and Simulink 26.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: SEL_toTest_src_NCO_block
-- Source Path: SEL_test/TESTBENCH/SEL/SEL_WRAPPED/DSP_LOGIC/DEMUX/NCO
-- Hierarchy Level: 4
-- Model version: 1.616
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY SEL_toTest_src_NCO_block IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        mix_bus_out_NSIN_MIX              :   OUT   std_logic_vector(24 DOWNTO 0);  -- sfix25_En23
        mix_bus_out_COS_MIX               :   OUT   std_logic_vector(24 DOWNTO 0);  -- sfix25_En23
        valid_out                         :   OUT   std_logic
        );
END SEL_toTest_src_NCO_block;


ARCHITECTURE rtl OF SEL_toTest_src_NCO_block IS

  -- Component Declarations
  COMPONENT SEL_toTest_src_NCO
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          inc                             :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          validIn                         :   IN    std_logic;
          phase                           :   OUT   std_logic_vector(13 DOWNTO 0);  -- ufix14
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT SEL_toTest_src_Sine_HDL_Optimized
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          u                               :   IN    std_logic_vector(13 DOWNTO 0);  -- ufix14_En14
          x                               :   OUT   std_logic_vector(24 DOWNTO 0)  -- sfix25_En23
          );
  END COMPONENT;

  COMPONENT SEL_toTest_src_Sine_HDL_Optimized1
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          u                               :   IN    std_logic_vector(13 DOWNTO 0);  -- ufix14_En14
          x                               :   OUT   std_logic_vector(24 DOWNTO 0)  -- sfix25_En23
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : SEL_toTest_src_NCO
    USE ENTITY work.SEL_toTest_src_NCO(rtl);

  FOR ALL : SEL_toTest_src_Sine_HDL_Optimized
    USE ENTITY work.SEL_toTest_src_Sine_HDL_Optimized(rtl);

  FOR ALL : SEL_toTest_src_Sine_HDL_Optimized1
    USE ENTITY work.SEL_toTest_src_Sine_HDL_Optimized1(rtl);

  -- Signals
  SIGNAL kconst                           : signed(24 DOWNTO 0);  -- sfix25_En24
  SIGNAL kconst_1                         : signed(24 DOWNTO 0);  -- sfix25_En24
  SIGNAL Constant_out1                    : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Constant2_out1                   : std_logic;
  SIGNAL NCO_out2                         : std_logic_vector(13 DOWNTO 0);  -- ufix14
  SIGNAL TVALID                           : std_logic;
  SIGNAL NCO_out2_unsigned                : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL Data_Type_Conversion_out1        : unsigned(13 DOWNTO 0);  -- ufix14_En14
  SIGNAL Sine_HDL_Optimized_x             : std_logic_vector(24 DOWNTO 0);  -- ufix25
  SIGNAL Sine_HDL_Optimized_x_signed      : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL Delay1_out1                      : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL NSIN_MIX                         : signed(49 DOWNTO 0);  -- sfix50_En47
  SIGNAL NSIN_MIX_1                       : signed(49 DOWNTO 0);  -- sfix50_En47
  SIGNAL NSIN_MIX_2                       : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL Bus_Creator1_out1_buff_NSIN_MIX  : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL COS_MIX                          : std_logic_vector(24 DOWNTO 0);  -- ufix25
  SIGNAL COS_MIX_1                        : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL Bus_Creator1_out1_buff_COS_MIX   : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL Delay2_out1_buff                 : std_logic;

BEGIN
  u_NCO : SEL_toTest_src_NCO
    PORT MAP( clk => clk,
              reset => reset,
              inc => std_logic_vector(Constant_out1),  -- uint32
              validIn => Constant2_out1,
              phase => NCO_out2,  -- ufix14
              validOut => TVALID
              );

  u_Sine_HDL_Optimized : SEL_toTest_src_Sine_HDL_Optimized
    PORT MAP( clk => clk,
              reset => reset,
              u => std_logic_vector(Data_Type_Conversion_out1),  -- ufix14_En14
              x => Sine_HDL_Optimized_x  -- sfix25_En23
              );

  u_Sine_HDL_Optimized1 : SEL_toTest_src_Sine_HDL_Optimized1
    PORT MAP( clk => clk,
              reset => reset,
              u => std_logic_vector(Data_Type_Conversion_out1),  -- ufix14_En14
              x => COS_MIX  -- sfix25_En23
              );

  kconst <= to_signed(-16#1000000#, 25);

  HwModeRegister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        kconst_1 <= to_signed(16#0000000#, 25);
      ELSE 
        kconst_1 <= kconst;
      END IF;
    END IF;
  END PROCESS HwModeRegister_process;


  Constant_out1 <= to_unsigned(343597384, 32);

  Constant2_out1 <= '1';

  NCO_out2_unsigned <= unsigned(NCO_out2);

  Data_Type_Conversion_out1 <= NCO_out2_unsigned;

  Sine_HDL_Optimized_x_signed <= signed(Sine_HDL_Optimized_x);

  HwModeRegister1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay1_out1 <= to_signed(16#0000000#, 25);
      ELSE 
        Delay1_out1 <= Sine_HDL_Optimized_x_signed;
      END IF;
    END IF;
  END PROCESS HwModeRegister1_process;


  NSIN_MIX <= kconst_1 * Delay1_out1;

  PipelineRegister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        NSIN_MIX_1 <= to_signed(0, 50);
      ELSE 
        NSIN_MIX_1 <= NSIN_MIX;
      END IF;
    END IF;
  END PROCESS PipelineRegister_process;


  
  NSIN_MIX_2 <= "0111111111111111111111111" WHEN ((NSIN_MIX_1(49) = '0') AND (NSIN_MIX_1(48) /= '0')) OR ((NSIN_MIX_1(49) = '0') AND (NSIN_MIX_1(48 DOWNTO 24) = "0111111111111111111111111")) ELSE
      "1000000000000000000000000" WHEN (NSIN_MIX_1(49) = '1') AND (NSIN_MIX_1(48) /= '1') ELSE
      NSIN_MIX_1(48 DOWNTO 24) + ('0' & NSIN_MIX_1(23));

  c_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Bus_Creator1_out1_buff_NSIN_MIX <= to_signed(16#0000000#, 25);
      ELSE 
        Bus_Creator1_out1_buff_NSIN_MIX <= NSIN_MIX_2;
      END IF;
    END IF;
  END PROCESS c_process;


  mix_bus_out_NSIN_MIX <= std_logic_vector(Bus_Creator1_out1_buff_NSIN_MIX);

  COS_MIX_1 <= signed(COS_MIX);

  c_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Bus_Creator1_out1_buff_COS_MIX <= to_signed(16#0000000#, 25);
      ELSE 
        Bus_Creator1_out1_buff_COS_MIX <= COS_MIX_1;
      END IF;
    END IF;
  END PROCESS c_1_process;


  mix_bus_out_COS_MIX <= std_logic_vector(Bus_Creator1_out1_buff_COS_MIX);

  cd_0_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay2_out1_buff <= '0';
      ELSE 
        Delay2_out1_buff <= TVALID;
      END IF;
    END IF;
  END PROCESS cd_0_process;


  valid_out <= Delay2_out1_buff;

END rtl;

