-- -------------------------------------------------------------
-- 
-- File Name: SEL_Reverted\hdlsrc\SEL_test\SEL_toTest_addr_decoder.vhd
-- Created: 2026-07-27 16:15:07
-- 
-- Generated by MATLAB 26.1, HDL Coder 26.1, and Simulink 26.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: SEL_toTest_addr_decoder
-- Source Path: SEL_toTest/SEL_toTest_axi_lite/SEL_toTest_addr_decoder
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.SEL_toTest_pkg.ALL;

ENTITY SEL_toTest_addr_decoder IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        data_write                        :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        addr_write                        :   IN    std_logic_vector(13 DOWNTO 0);  -- ufix14
        wr_enb                            :   IN    std_logic;  -- ufix1
        addr_read                         :   IN    std_logic_vector(13 DOWNTO 0);  -- ufix14
        rd_enb                            :   IN    std_logic;  -- ufix1
        read_ip_timestamp                 :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        data_read                         :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        write_packet_size_axi4_stream_dac2_master :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        write_packet_size_axi4_stream_dac1_master :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        write_AXI4_LITE_CONTROL_PHASE_COS :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
        write_AXI4_LITE_CONTROL_PHASE_SIN :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
        write_AXI4_LITE_CONTROL_MAG_SET   :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
        write_AXI4_LITE_CONTROL_K_HIGH    :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
        write_AXI4_LITE_CONTROL_K_LOW     :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
        write_AXI4_LITE_CONTROL_PULSE_WIDTH :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        write_AXI4_LITE_CONTROL_PULSE_EN  :   OUT   std_logic;  -- ufix1
        write_AXI4_LITE_CONTROL_AUTO_EN   :   OUT   std_logic;  -- ufix1
        write_AXI4_LITE_CONTROL_REP_PERIOD :   OUT   std_logic_vector(31 DOWNTO 0)  -- ufix32
        );
END SEL_toTest_addr_decoder;


ARCHITECTURE rtl OF SEL_toTest_addr_decoder IS

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL addr_read_unsigned               : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL address_select_MSBs              : unsigned(6 DOWNTO 0);  -- ufix7
  SIGNAL address_select_level1            : unsigned(6 DOWNTO 0);  -- ufix7
  SIGNAL addr_write_unsigned              : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL decode_sel_packet_size_axi4_stream_dac2_master_1_1 : std_logic;  -- ufix1
  SIGNAL reg_enb_packet_size_axi4_stream_dac2_master_1_1 : std_logic;  -- ufix1
  SIGNAL data_write_unsigned              : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL const_1                          : std_logic;  -- ufix1
  SIGNAL data_reg_packet_size_axi4_stream_dac2_master_1_1 : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL decode_sel_packet_size_axi4_stream_dac1_master_1_1 : std_logic;  -- ufix1
  SIGNAL reg_enb_packet_size_axi4_stream_dac1_master_1_1 : std_logic;  -- ufix1
  SIGNAL data_reg_packet_size_axi4_stream_dac1_master_1_1 : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL read_ip_timestamp_unsigned       : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL read_reg_ip_timestamp            : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL decode_sel_AXI4_LITE_CONTROL_PHASE_COS_1_1 : std_logic;  -- ufix1
  SIGNAL reg_enb_AXI4_LITE_CONTROL_PHASE_COS_1_1 : std_logic;  -- ufix1
  SIGNAL data_in_AXI4_LITE_CONTROL_PHASE_COS : signed(17 DOWNTO 0);  -- sfix18_En16
  SIGNAL data_reg_AXI4_LITE_CONTROL_PHASE_COS_1_1 : signed(17 DOWNTO 0);  -- sfix18_En16
  SIGNAL data_slice_AXI4_LITE_CONTROL_PHASE_COS_1 : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL decode_sel_AXI4_LITE_CONTROL_PHASE_SIN_1_1 : std_logic;  -- ufix1
  SIGNAL reg_enb_AXI4_LITE_CONTROL_PHASE_SIN_1_1 : std_logic;  -- ufix1
  SIGNAL data_in_AXI4_LITE_CONTROL_PHASE_SIN : signed(17 DOWNTO 0);  -- sfix18_En16
  SIGNAL data_reg_AXI4_LITE_CONTROL_PHASE_SIN_1_1 : signed(17 DOWNTO 0);  -- sfix18_En16
  SIGNAL data_slice_AXI4_LITE_CONTROL_PHASE_SIN_1 : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL decode_sel_AXI4_LITE_CONTROL_MAG_SET_1_1 : std_logic;  -- ufix1
  SIGNAL reg_enb_AXI4_LITE_CONTROL_MAG_SET_1_1 : std_logic;  -- ufix1
  SIGNAL data_in_AXI4_LITE_CONTROL_MAG_SET : signed(17 DOWNTO 0);  -- sfix18_En16
  SIGNAL data_reg_AXI4_LITE_CONTROL_MAG_SET_1_1 : signed(17 DOWNTO 0);  -- sfix18_En16
  SIGNAL data_slice_AXI4_LITE_CONTROL_MAG_SET_1 : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL decode_sel_AXI4_LITE_CONTROL_K_HIGH_1_1 : std_logic;  -- ufix1
  SIGNAL reg_enb_AXI4_LITE_CONTROL_K_HIGH_1_1 : std_logic;  -- ufix1
  SIGNAL data_in_AXI4_LITE_CONTROL_K_HIGH : signed(17 DOWNTO 0);  -- sfix18_En16
  SIGNAL data_reg_AXI4_LITE_CONTROL_K_HIGH_1_1 : signed(17 DOWNTO 0);  -- sfix18_En16
  SIGNAL data_slice_AXI4_LITE_CONTROL_K_HIGH_1 : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL decode_sel_AXI4_LITE_CONTROL_K_LOW_1_1 : std_logic;  -- ufix1
  SIGNAL reg_enb_AXI4_LITE_CONTROL_K_LOW_1_1 : std_logic;  -- ufix1
  SIGNAL data_in_AXI4_LITE_CONTROL_K_LOW  : signed(17 DOWNTO 0);  -- sfix18_En16
  SIGNAL data_reg_AXI4_LITE_CONTROL_K_LOW_1_1 : signed(17 DOWNTO 0);  -- sfix18_En16
  SIGNAL data_slice_AXI4_LITE_CONTROL_K_LOW_1 : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL decode_sel_AXI4_LITE_CONTROL_PULSE_WIDTH_1_1 : std_logic;  -- ufix1
  SIGNAL reg_enb_AXI4_LITE_CONTROL_PULSE_WIDTH_1_1 : std_logic;  -- ufix1
  SIGNAL data_reg_AXI4_LITE_CONTROL_PULSE_WIDTH_1_1 : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL decode_sel_AXI4_LITE_CONTROL_PULSE_EN_1_1 : std_logic;  -- ufix1
  SIGNAL reg_enb_AXI4_LITE_CONTROL_PULSE_EN_1_1 : std_logic;  -- ufix1
  SIGNAL data_in_AXI4_LITE_CONTROL_PULSE_EN : std_logic;  -- ufix1
  SIGNAL data_reg_AXI4_LITE_CONTROL_PULSE_EN_1_1 : std_logic;  -- ufix1
  SIGNAL data_slice_AXI4_LITE_CONTROL_PULSE_EN_1 : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL decode_sel_AXI4_LITE_CONTROL_AUTO_EN_1_1 : std_logic;  -- ufix1
  SIGNAL reg_enb_AXI4_LITE_CONTROL_AUTO_EN_1_1 : std_logic;  -- ufix1
  SIGNAL data_in_AXI4_LITE_CONTROL_AUTO_EN : std_logic;  -- ufix1
  SIGNAL data_reg_AXI4_LITE_CONTROL_AUTO_EN_1_1 : std_logic;  -- ufix1
  SIGNAL data_slice_AXI4_LITE_CONTROL_AUTO_EN_1 : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL decode_sel_AXI4_LITE_CONTROL_REP_PERIOD_1_1 : std_logic;  -- ufix1
  SIGNAL reg_enb_AXI4_LITE_CONTROL_REP_PERIOD_1_1 : std_logic;  -- ufix1
  SIGNAL data_reg_AXI4_LITE_CONTROL_REP_PERIOD_1_1 : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL const_0                          : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL mux_out0_level1                  : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL mux_out_decoded                  : unsigned(31 DOWNTO 0);  -- ufix32

BEGIN
  addr_read_unsigned <= unsigned(addr_read);

  address_select_MSBs <= addr_read_unsigned(13 DOWNTO 7);

  address_select_level1 <= addr_read_unsigned(6 DOWNTO 0);

  addr_write_unsigned <= unsigned(addr_write);

  
  decode_sel_packet_size_axi4_stream_dac2_master_1_1 <= '1' WHEN addr_write_unsigned = to_unsigned(16#0002#, 14) ELSE
      '0';

  reg_enb_packet_size_axi4_stream_dac2_master_1_1 <= decode_sel_packet_size_axi4_stream_dac2_master_1_1 AND wr_enb;

  data_write_unsigned <= unsigned(data_write);

  const_1 <= '1';

  enb <= const_1;

  reg_packet_size_axi4_stream_dac2_master_1_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        data_reg_packet_size_axi4_stream_dac2_master_1_1 <= to_unsigned(1024, 32);
      ELSIF enb = '1' AND reg_enb_packet_size_axi4_stream_dac2_master_1_1 = '1' THEN
        data_reg_packet_size_axi4_stream_dac2_master_1_1 <= data_write_unsigned;
      END IF;
    END IF;
  END PROCESS reg_packet_size_axi4_stream_dac2_master_1_1_process;


  
  decode_sel_packet_size_axi4_stream_dac1_master_1_1 <= '1' WHEN addr_write_unsigned = to_unsigned(16#0003#, 14) ELSE
      '0';

  reg_enb_packet_size_axi4_stream_dac1_master_1_1 <= decode_sel_packet_size_axi4_stream_dac1_master_1_1 AND wr_enb;

  reg_packet_size_axi4_stream_dac1_master_1_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        data_reg_packet_size_axi4_stream_dac1_master_1_1 <= to_unsigned(1024, 32);
      ELSIF enb = '1' AND reg_enb_packet_size_axi4_stream_dac1_master_1_1 = '1' THEN
        data_reg_packet_size_axi4_stream_dac1_master_1_1 <= data_write_unsigned;
      END IF;
    END IF;
  END PROCESS reg_packet_size_axi4_stream_dac1_master_1_1_process;


  read_ip_timestamp_unsigned <= unsigned(read_ip_timestamp);

  reg_ip_timestamp_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        read_reg_ip_timestamp <= to_unsigned(0, 32);
      ELSIF enb = '1' THEN
        read_reg_ip_timestamp <= read_ip_timestamp_unsigned;
      END IF;
    END IF;
  END PROCESS reg_ip_timestamp_process;


  
  decode_sel_AXI4_LITE_CONTROL_PHASE_COS_1_1 <= '1' WHEN addr_write_unsigned = to_unsigned(16#0040#, 14) ELSE
      '0';

  reg_enb_AXI4_LITE_CONTROL_PHASE_COS_1_1 <= decode_sel_AXI4_LITE_CONTROL_PHASE_COS_1_1 AND wr_enb;

  data_in_AXI4_LITE_CONTROL_PHASE_COS <= signed(data_write_unsigned(17 DOWNTO 0));

  reg_AXI4_LITE_CONTROL_PHASE_COS_1_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        data_reg_AXI4_LITE_CONTROL_PHASE_COS_1_1 <= to_signed(16#00000#, 18);
      ELSIF enb = '1' AND reg_enb_AXI4_LITE_CONTROL_PHASE_COS_1_1 = '1' THEN
        data_reg_AXI4_LITE_CONTROL_PHASE_COS_1_1 <= data_in_AXI4_LITE_CONTROL_PHASE_COS;
      END IF;
    END IF;
  END PROCESS reg_AXI4_LITE_CONTROL_PHASE_COS_1_1_process;


  data_slice_AXI4_LITE_CONTROL_PHASE_COS_1 <= unsigned(resize(data_reg_AXI4_LITE_CONTROL_PHASE_COS_1_1, 32));

  
  decode_sel_AXI4_LITE_CONTROL_PHASE_SIN_1_1 <= '1' WHEN addr_write_unsigned = to_unsigned(16#0041#, 14) ELSE
      '0';

  reg_enb_AXI4_LITE_CONTROL_PHASE_SIN_1_1 <= decode_sel_AXI4_LITE_CONTROL_PHASE_SIN_1_1 AND wr_enb;

  data_in_AXI4_LITE_CONTROL_PHASE_SIN <= signed(data_write_unsigned(17 DOWNTO 0));

  reg_AXI4_LITE_CONTROL_PHASE_SIN_1_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        data_reg_AXI4_LITE_CONTROL_PHASE_SIN_1_1 <= to_signed(16#00000#, 18);
      ELSIF enb = '1' AND reg_enb_AXI4_LITE_CONTROL_PHASE_SIN_1_1 = '1' THEN
        data_reg_AXI4_LITE_CONTROL_PHASE_SIN_1_1 <= data_in_AXI4_LITE_CONTROL_PHASE_SIN;
      END IF;
    END IF;
  END PROCESS reg_AXI4_LITE_CONTROL_PHASE_SIN_1_1_process;


  data_slice_AXI4_LITE_CONTROL_PHASE_SIN_1 <= unsigned(resize(data_reg_AXI4_LITE_CONTROL_PHASE_SIN_1_1, 32));

  
  decode_sel_AXI4_LITE_CONTROL_MAG_SET_1_1 <= '1' WHEN addr_write_unsigned = to_unsigned(16#0042#, 14) ELSE
      '0';

  reg_enb_AXI4_LITE_CONTROL_MAG_SET_1_1 <= decode_sel_AXI4_LITE_CONTROL_MAG_SET_1_1 AND wr_enb;

  data_in_AXI4_LITE_CONTROL_MAG_SET <= signed(data_write_unsigned(17 DOWNTO 0));

  reg_AXI4_LITE_CONTROL_MAG_SET_1_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        data_reg_AXI4_LITE_CONTROL_MAG_SET_1_1 <= to_signed(16#00000#, 18);
      ELSIF enb = '1' AND reg_enb_AXI4_LITE_CONTROL_MAG_SET_1_1 = '1' THEN
        data_reg_AXI4_LITE_CONTROL_MAG_SET_1_1 <= data_in_AXI4_LITE_CONTROL_MAG_SET;
      END IF;
    END IF;
  END PROCESS reg_AXI4_LITE_CONTROL_MAG_SET_1_1_process;


  data_slice_AXI4_LITE_CONTROL_MAG_SET_1 <= unsigned(resize(data_reg_AXI4_LITE_CONTROL_MAG_SET_1_1, 32));

  
  decode_sel_AXI4_LITE_CONTROL_K_HIGH_1_1 <= '1' WHEN addr_write_unsigned = to_unsigned(16#0043#, 14) ELSE
      '0';

  reg_enb_AXI4_LITE_CONTROL_K_HIGH_1_1 <= decode_sel_AXI4_LITE_CONTROL_K_HIGH_1_1 AND wr_enb;

  data_in_AXI4_LITE_CONTROL_K_HIGH <= signed(data_write_unsigned(17 DOWNTO 0));

  reg_AXI4_LITE_CONTROL_K_HIGH_1_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        data_reg_AXI4_LITE_CONTROL_K_HIGH_1_1 <= to_signed(16#00000#, 18);
      ELSIF enb = '1' AND reg_enb_AXI4_LITE_CONTROL_K_HIGH_1_1 = '1' THEN
        data_reg_AXI4_LITE_CONTROL_K_HIGH_1_1 <= data_in_AXI4_LITE_CONTROL_K_HIGH;
      END IF;
    END IF;
  END PROCESS reg_AXI4_LITE_CONTROL_K_HIGH_1_1_process;


  data_slice_AXI4_LITE_CONTROL_K_HIGH_1 <= unsigned(resize(data_reg_AXI4_LITE_CONTROL_K_HIGH_1_1, 32));

  
  decode_sel_AXI4_LITE_CONTROL_K_LOW_1_1 <= '1' WHEN addr_write_unsigned = to_unsigned(16#0044#, 14) ELSE
      '0';

  reg_enb_AXI4_LITE_CONTROL_K_LOW_1_1 <= decode_sel_AXI4_LITE_CONTROL_K_LOW_1_1 AND wr_enb;

  data_in_AXI4_LITE_CONTROL_K_LOW <= signed(data_write_unsigned(17 DOWNTO 0));

  reg_AXI4_LITE_CONTROL_K_LOW_1_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        data_reg_AXI4_LITE_CONTROL_K_LOW_1_1 <= to_signed(16#00000#, 18);
      ELSIF enb = '1' AND reg_enb_AXI4_LITE_CONTROL_K_LOW_1_1 = '1' THEN
        data_reg_AXI4_LITE_CONTROL_K_LOW_1_1 <= data_in_AXI4_LITE_CONTROL_K_LOW;
      END IF;
    END IF;
  END PROCESS reg_AXI4_LITE_CONTROL_K_LOW_1_1_process;


  data_slice_AXI4_LITE_CONTROL_K_LOW_1 <= unsigned(resize(data_reg_AXI4_LITE_CONTROL_K_LOW_1_1, 32));

  
  decode_sel_AXI4_LITE_CONTROL_PULSE_WIDTH_1_1 <= '1' WHEN addr_write_unsigned = to_unsigned(16#0045#, 14) ELSE
      '0';

  reg_enb_AXI4_LITE_CONTROL_PULSE_WIDTH_1_1 <= decode_sel_AXI4_LITE_CONTROL_PULSE_WIDTH_1_1 AND wr_enb;

  reg_AXI4_LITE_CONTROL_PULSE_WIDTH_1_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        data_reg_AXI4_LITE_CONTROL_PULSE_WIDTH_1_1 <= to_unsigned(0, 32);
      ELSIF enb = '1' AND reg_enb_AXI4_LITE_CONTROL_PULSE_WIDTH_1_1 = '1' THEN
        data_reg_AXI4_LITE_CONTROL_PULSE_WIDTH_1_1 <= data_write_unsigned;
      END IF;
    END IF;
  END PROCESS reg_AXI4_LITE_CONTROL_PULSE_WIDTH_1_1_process;


  
  decode_sel_AXI4_LITE_CONTROL_PULSE_EN_1_1 <= '1' WHEN addr_write_unsigned = to_unsigned(16#0046#, 14) ELSE
      '0';

  reg_enb_AXI4_LITE_CONTROL_PULSE_EN_1_1 <= decode_sel_AXI4_LITE_CONTROL_PULSE_EN_1_1 AND wr_enb;

  data_in_AXI4_LITE_CONTROL_PULSE_EN <= data_write_unsigned(0);

  reg_AXI4_LITE_CONTROL_PULSE_EN_1_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        data_reg_AXI4_LITE_CONTROL_PULSE_EN_1_1 <= '0';
      ELSIF enb = '1' AND reg_enb_AXI4_LITE_CONTROL_PULSE_EN_1_1 = '1' THEN
        data_reg_AXI4_LITE_CONTROL_PULSE_EN_1_1 <= data_in_AXI4_LITE_CONTROL_PULSE_EN;
      END IF;
    END IF;
  END PROCESS reg_AXI4_LITE_CONTROL_PULSE_EN_1_1_process;


  data_slice_AXI4_LITE_CONTROL_PULSE_EN_1 <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & data_reg_AXI4_LITE_CONTROL_PULSE_EN_1_1;

  
  decode_sel_AXI4_LITE_CONTROL_AUTO_EN_1_1 <= '1' WHEN addr_write_unsigned = to_unsigned(16#0047#, 14) ELSE
      '0';

  reg_enb_AXI4_LITE_CONTROL_AUTO_EN_1_1 <= decode_sel_AXI4_LITE_CONTROL_AUTO_EN_1_1 AND wr_enb;

  data_in_AXI4_LITE_CONTROL_AUTO_EN <= data_write_unsigned(0);

  reg_AXI4_LITE_CONTROL_AUTO_EN_1_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        data_reg_AXI4_LITE_CONTROL_AUTO_EN_1_1 <= '0';
      ELSIF enb = '1' AND reg_enb_AXI4_LITE_CONTROL_AUTO_EN_1_1 = '1' THEN
        data_reg_AXI4_LITE_CONTROL_AUTO_EN_1_1 <= data_in_AXI4_LITE_CONTROL_AUTO_EN;
      END IF;
    END IF;
  END PROCESS reg_AXI4_LITE_CONTROL_AUTO_EN_1_1_process;


  data_slice_AXI4_LITE_CONTROL_AUTO_EN_1 <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & data_reg_AXI4_LITE_CONTROL_AUTO_EN_1_1;

  
  decode_sel_AXI4_LITE_CONTROL_REP_PERIOD_1_1 <= '1' WHEN addr_write_unsigned = to_unsigned(16#0048#, 14) ELSE
      '0';

  reg_enb_AXI4_LITE_CONTROL_REP_PERIOD_1_1 <= decode_sel_AXI4_LITE_CONTROL_REP_PERIOD_1_1 AND wr_enb;

  reg_AXI4_LITE_CONTROL_REP_PERIOD_1_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        data_reg_AXI4_LITE_CONTROL_REP_PERIOD_1_1 <= to_unsigned(0, 32);
      ELSIF enb = '1' AND reg_enb_AXI4_LITE_CONTROL_REP_PERIOD_1_1 = '1' THEN
        data_reg_AXI4_LITE_CONTROL_REP_PERIOD_1_1 <= data_write_unsigned;
      END IF;
    END IF;
  END PROCESS reg_AXI4_LITE_CONTROL_REP_PERIOD_1_1_process;


  const_0 <= to_unsigned(0, 32);

  mux0_level1_output : PROCESS (address_select_level1, const_0, data_reg_AXI4_LITE_CONTROL_PULSE_WIDTH_1_1,
       data_reg_AXI4_LITE_CONTROL_REP_PERIOD_1_1,
       data_reg_packet_size_axi4_stream_dac1_master_1_1,
       data_reg_packet_size_axi4_stream_dac2_master_1_1,
       data_slice_AXI4_LITE_CONTROL_AUTO_EN_1,
       data_slice_AXI4_LITE_CONTROL_K_HIGH_1,
       data_slice_AXI4_LITE_CONTROL_K_LOW_1,
       data_slice_AXI4_LITE_CONTROL_MAG_SET_1,
       data_slice_AXI4_LITE_CONTROL_PHASE_COS_1,
       data_slice_AXI4_LITE_CONTROL_PHASE_SIN_1,
       data_slice_AXI4_LITE_CONTROL_PULSE_EN_1, read_reg_ip_timestamp)
  BEGIN
    CASE address_select_level1 IS
      WHEN "0000010" =>
        mux_out0_level1 <= data_reg_packet_size_axi4_stream_dac2_master_1_1;
      WHEN "0000011" =>
        mux_out0_level1 <= data_reg_packet_size_axi4_stream_dac1_master_1_1;
      WHEN "0000100" =>
        mux_out0_level1 <= read_reg_ip_timestamp;
      WHEN "1000000" =>
        mux_out0_level1 <= data_slice_AXI4_LITE_CONTROL_PHASE_COS_1;
      WHEN "1000001" =>
        mux_out0_level1 <= data_slice_AXI4_LITE_CONTROL_PHASE_SIN_1;
      WHEN "1000010" =>
        mux_out0_level1 <= data_slice_AXI4_LITE_CONTROL_MAG_SET_1;
      WHEN "1000011" =>
        mux_out0_level1 <= data_slice_AXI4_LITE_CONTROL_K_HIGH_1;
      WHEN "1000100" =>
        mux_out0_level1 <= data_slice_AXI4_LITE_CONTROL_K_LOW_1;
      WHEN "1000101" =>
        mux_out0_level1 <= data_reg_AXI4_LITE_CONTROL_PULSE_WIDTH_1_1;
      WHEN "1000110" =>
        mux_out0_level1 <= data_slice_AXI4_LITE_CONTROL_PULSE_EN_1;
      WHEN "1000111" =>
        mux_out0_level1 <= data_slice_AXI4_LITE_CONTROL_AUTO_EN_1;
      WHEN "1001000" =>
        mux_out0_level1 <= data_reg_AXI4_LITE_CONTROL_REP_PERIOD_1_1;
      WHEN OTHERS => 
        mux_out0_level1 <= const_0;
    END CASE;
  END PROCESS mux0_level1_output;


  
  mux_out_decoded <= mux_out0_level1 WHEN address_select_MSBs = to_unsigned(16#00#, 7) ELSE
      const_0;

  data_read <= std_logic_vector(mux_out_decoded);

  write_packet_size_axi4_stream_dac2_master <= std_logic_vector(data_reg_packet_size_axi4_stream_dac2_master_1_1);

  write_packet_size_axi4_stream_dac1_master <= std_logic_vector(data_reg_packet_size_axi4_stream_dac1_master_1_1);

  write_AXI4_LITE_CONTROL_PHASE_COS <= std_logic_vector(data_reg_AXI4_LITE_CONTROL_PHASE_COS_1_1);

  write_AXI4_LITE_CONTROL_PHASE_SIN <= std_logic_vector(data_reg_AXI4_LITE_CONTROL_PHASE_SIN_1_1);

  write_AXI4_LITE_CONTROL_MAG_SET <= std_logic_vector(data_reg_AXI4_LITE_CONTROL_MAG_SET_1_1);

  write_AXI4_LITE_CONTROL_K_HIGH <= std_logic_vector(data_reg_AXI4_LITE_CONTROL_K_HIGH_1_1);

  write_AXI4_LITE_CONTROL_K_LOW <= std_logic_vector(data_reg_AXI4_LITE_CONTROL_K_LOW_1_1);

  write_AXI4_LITE_CONTROL_PULSE_WIDTH <= std_logic_vector(data_reg_AXI4_LITE_CONTROL_PULSE_WIDTH_1_1);

  write_AXI4_LITE_CONTROL_PULSE_EN <= data_reg_AXI4_LITE_CONTROL_PULSE_EN_1_1;

  write_AXI4_LITE_CONTROL_AUTO_EN <= data_reg_AXI4_LITE_CONTROL_AUTO_EN_1_1;

  write_AXI4_LITE_CONTROL_REP_PERIOD <= std_logic_vector(data_reg_AXI4_LITE_CONTROL_REP_PERIOD_1_1);

END rtl;

