-- -------------------------------------------------------------
-- 
-- File Name: SEL_Reverted\hdlsrc\SEL_test\SEL_toTest_src_BiquadPipeSection1.vhd
-- Created: 2026-07-27 16:14:57
-- 
-- Generated by MATLAB 26.1, HDL Coder 26.1, and Simulink 26.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: SEL_toTest_src_BiquadPipeSection1
-- Source Path: SEL_test/TESTBENCH/SEL/SEL_WRAPPED/DSP_LOGIC/LPF/Biquad Filter/BiquadPipeSection1
-- Hierarchy Level: 5
-- Model version: 1.616
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.SEL_toTest_src_SEL_pkg.ALL;

ENTITY SEL_toTest_src_BiquadPipeSection1 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        dataIn                            :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En23
        validIn                           :   IN    std_logic;
        dataOut                           :   OUT   std_logic_vector(24 DOWNTO 0);  -- sfix25_En23
        validOut                          :   OUT   std_logic
        );
END SEL_toTest_src_BiquadPipeSection1;


ARCHITECTURE rtl OF SEL_toTest_src_BiquadPipeSection1 IS

  -- Signals
  SIGNAL inValidReg                       : std_logic;
  SIGNAL dataIn_signed                    : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL inReg                            : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL delayline1Num1                   : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL numPre11Num1                     : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL numPre21Num1                     : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL prod1Num1                        : signed(49 DOWNTO 0);  -- sfix50_En46
  SIGNAL numPost11Num1                    : signed(49 DOWNTO 0);  -- sfix50_En46
  SIGNAL numPost21Num1                    : signed(49 DOWNTO 0);  -- sfix50_En46
  SIGNAL delayline2Num1                   : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL numPre12Num1                     : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL numPre22Num1                     : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL prod2Num1                        : signed(49 DOWNTO 0);  -- sfix50_En46
  SIGNAL numPost12Num1                    : signed(49 DOWNTO 0);  -- sfix50_En46
  SIGNAL numPost22Num1                    : signed(49 DOWNTO 0);  -- sfix50_En46
  SIGNAL adder_add_cast                   : signed(50 DOWNTO 0);  -- sfix51_En46
  SIGNAL adder_add_cast_1                 : signed(50 DOWNTO 0);  -- sfix51_En46
  SIGNAL sumL1V1Num1                      : signed(50 DOWNTO 0);  -- sfix51_En46
  SIGNAL sumregL1V1Num1                   : signed(50 DOWNTO 0);  -- sfix51_En46
  SIGNAL delayline3Num1                   : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL numPre13Num1                     : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL numPre23Num1                     : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL prod3Num1                        : signed(49 DOWNTO 0);  -- sfix50_En46
  SIGNAL numPost13Num1                    : signed(49 DOWNTO 0);  -- sfix50_En46
  SIGNAL numPost23Num1                    : signed(49 DOWNTO 0);  -- sfix50_En46
  SIGNAL sumL1V2Num1                      : signed(50 DOWNTO 0);  -- sfix51_En46
  SIGNAL sumregL1V2Num1                   : signed(50 DOWNTO 0);  -- sfix51_En46
  SIGNAL adder_add_cast_2                 : signed(51 DOWNTO 0);  -- sfix52_En46
  SIGNAL adder_add_cast_3                 : signed(51 DOWNTO 0);  -- sfix52_En46
  SIGNAL sumL2V1Num1                      : signed(51 DOWNTO 0);  -- sfix52_En46
  SIGNAL sumregL2V1Num1                   : signed(51 DOWNTO 0);  -- sfix52_En46
  SIGNAL delayline1NumZero1               : signed(51 DOWNTO 0);  -- sfix52_En46
  SIGNAL numPre11NumZero1                 : signed(51 DOWNTO 0);  -- sfix52_En46
  SIGNAL numPre21NumZero1                 : signed(51 DOWNTO 0);  -- sfix52_En46
  SIGNAL prod1NumZero1                    : signed(76 DOWNTO 0);  -- sfix77_En69
  SIGNAL numPost11NumZero1                : signed(76 DOWNTO 0);  -- sfix77_En69
  SIGNAL numPost21NumZero1                : signed(76 DOWNTO 0);  -- sfix77_En69
  SIGNAL delayline2NumZero1               : signed(51 DOWNTO 0);  -- sfix52_En46
  SIGNAL numPre12NumZero1                 : signed(51 DOWNTO 0);  -- sfix52_En46
  SIGNAL numPre22NumZero1                 : signed(51 DOWNTO 0);  -- sfix52_En46
  SIGNAL prod2NumZero1                    : signed(76 DOWNTO 0);  -- sfix77_En69
  SIGNAL numPost12NumZero1                : signed(76 DOWNTO 0);  -- sfix77_En69
  SIGNAL numPost22NumZero1                : signed(76 DOWNTO 0);  -- sfix77_En69
  SIGNAL adder_add_cast_4                 : signed(77 DOWNTO 0);  -- sfix78_En69
  SIGNAL adder_add_cast_5                 : signed(77 DOWNTO 0);  -- sfix78_En69
  SIGNAL sumL1V1NumZero1                  : signed(77 DOWNTO 0);  -- sfix78_En69
  SIGNAL sumregL1V1NumZero1               : signed(77 DOWNTO 0);  -- sfix78_En69
  SIGNAL delayline3NumZero1               : signed(51 DOWNTO 0);  -- sfix52_En46
  SIGNAL numPre13NumZero1                 : signed(51 DOWNTO 0);  -- sfix52_En46
  SIGNAL numPre23NumZero1                 : signed(51 DOWNTO 0);  -- sfix52_En46
  SIGNAL prod3NumZero1                    : signed(76 DOWNTO 0);  -- sfix77_En69
  SIGNAL numPost13NumZero1                : signed(76 DOWNTO 0);  -- sfix77_En69
  SIGNAL numPost23NumZero1                : signed(76 DOWNTO 0);  -- sfix77_En69
  SIGNAL delayline4NumZero1               : signed(51 DOWNTO 0);  -- sfix52_En46
  SIGNAL numPre14NumZero1                 : signed(51 DOWNTO 0);  -- sfix52_En46
  SIGNAL numPre24NumZero1                 : signed(51 DOWNTO 0);  -- sfix52_En46
  SIGNAL prod4NumZero1                    : signed(76 DOWNTO 0);  -- sfix77_En69
  SIGNAL numPost14NumZero1                : signed(76 DOWNTO 0);  -- sfix77_En69
  SIGNAL numPost24NumZero1                : signed(76 DOWNTO 0);  -- sfix77_En69
  SIGNAL adder_add_cast_6                 : signed(77 DOWNTO 0);  -- sfix78_En69
  SIGNAL adder_add_cast_7                 : signed(77 DOWNTO 0);  -- sfix78_En69
  SIGNAL sumL1V2NumZero1                  : signed(77 DOWNTO 0);  -- sfix78_En69
  SIGNAL sumregL1V2NumZero1               : signed(77 DOWNTO 0);  -- sfix78_En69
  SIGNAL adder_add_cast_8                 : signed(78 DOWNTO 0);  -- sfix79_En69
  SIGNAL adder_add_cast_9                 : signed(78 DOWNTO 0);  -- sfix79_En69
  SIGNAL sumL2V1NumZero1                  : signed(78 DOWNTO 0);  -- sfix79_En69
  SIGNAL sumregL2V1NumZero1               : signed(78 DOWNTO 0);  -- sfix79_En69
  SIGNAL delayline5NumZero1               : signed(51 DOWNTO 0);  -- sfix52_En46
  SIGNAL numPre15NumZero1                 : signed(51 DOWNTO 0);  -- sfix52_En46
  SIGNAL numPre25NumZero1                 : signed(51 DOWNTO 0);  -- sfix52_En46
  SIGNAL prod5NumZero1                    : signed(76 DOWNTO 0);  -- sfix77_En69
  SIGNAL numPost15NumZero1                : signed(76 DOWNTO 0);  -- sfix77_En69
  SIGNAL numPost25NumZero1                : signed(76 DOWNTO 0);  -- sfix77_En69
  SIGNAL delayline6NumZero1               : signed(51 DOWNTO 0);  -- sfix52_En46
  SIGNAL numPre16NumZero1                 : signed(51 DOWNTO 0);  -- sfix52_En46
  SIGNAL numPre26NumZero1                 : signed(51 DOWNTO 0);  -- sfix52_En46
  SIGNAL prod6NumZero1                    : signed(76 DOWNTO 0);  -- sfix77_En69
  SIGNAL numPost16NumZero1                : signed(76 DOWNTO 0);  -- sfix77_En69
  SIGNAL numPost26NumZero1                : signed(76 DOWNTO 0);  -- sfix77_En69
  SIGNAL adder_add_cast_10                : signed(77 DOWNTO 0);  -- sfix78_En69
  SIGNAL adder_add_cast_11                : signed(77 DOWNTO 0);  -- sfix78_En69
  SIGNAL sumL1V3NumZero1                  : signed(77 DOWNTO 0);  -- sfix78_En69
  SIGNAL sumregL1V3NumZero1               : signed(77 DOWNTO 0);  -- sfix78_En69
  SIGNAL delayline7NumZero1               : signed(51 DOWNTO 0);  -- sfix52_En46
  SIGNAL numPre17NumZero1                 : signed(51 DOWNTO 0);  -- sfix52_En46
  SIGNAL numPre27NumZero1                 : signed(51 DOWNTO 0);  -- sfix52_En46
  SIGNAL prod7NumZero1                    : signed(76 DOWNTO 0);  -- sfix77_En69
  SIGNAL numPost17NumZero1                : signed(76 DOWNTO 0);  -- sfix77_En69
  SIGNAL numPost27NumZero1                : signed(76 DOWNTO 0);  -- sfix77_En69
  SIGNAL sumL1V4NumZero1                  : signed(77 DOWNTO 0);  -- sfix78_En69
  SIGNAL sumregL1V4NumZero1               : signed(77 DOWNTO 0);  -- sfix78_En69
  SIGNAL adder_add_cast_12                : signed(78 DOWNTO 0);  -- sfix79_En69
  SIGNAL adder_add_cast_13                : signed(78 DOWNTO 0);  -- sfix79_En69
  SIGNAL sumL2V2NumZero1                  : signed(78 DOWNTO 0);  -- sfix79_En69
  SIGNAL sumregL2V2NumZero1               : signed(78 DOWNTO 0);  -- sfix79_En69
  SIGNAL adder_add_cast_14                : signed(79 DOWNTO 0);  -- sfix80_En69
  SIGNAL adder_add_cast_15                : signed(79 DOWNTO 0);  -- sfix80_En69
  SIGNAL sumL3V1NumZero1                  : signed(79 DOWNTO 0);  -- sfix80_En69
  SIGNAL sumregL3V1NumZero1               : signed(79 DOWNTO 0);  -- sfix80_En69
  SIGNAL denOut                           : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL den2DelayReg_reg                 : vector_of_signed25(0 TO 2);  -- sfix25 [3]
  SIGNAL denOutDelay                      : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL den2InPipe1                      : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL den2InPipe2                      : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL denProd2                         : signed(49 DOWNTO 0);  -- sfix50_En46
  SIGNAL den2OutPipe1                     : signed(49 DOWNTO 0);  -- sfix50_En46
  SIGNAL state2                           : signed(49 DOWNTO 0);  -- sfix50_En46
  SIGNAL den1InPipe1                      : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL den1InPipe2                      : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL denProd1                         : signed(49 DOWNTO 0);  -- sfix50_En46
  SIGNAL den1OutPipe1                     : signed(49 DOWNTO 0);  -- sfix50_En46
  SIGNAL adder_add_cast_16                : signed(50 DOWNTO 0);  -- sfix51_En46
  SIGNAL adder_add_cast_17                : signed(50 DOWNTO 0);  -- sfix51_En46
  SIGNAL denSum2                          : signed(50 DOWNTO 0);  -- sfix51_En46
  SIGNAL state1                           : signed(50 DOWNTO 0);  -- sfix51_En46
  SIGNAL adder_add_cast_18                : signed(79 DOWNTO 0);  -- sfix80_En69
  SIGNAL denSum1                          : signed(79 DOWNTO 0);  -- sfix80_En69
  SIGNAL dataOut_tmp                      : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL intdelay_reg                     : std_logic_vector(14 DOWNTO 0);  -- ufix1 [15]
  SIGNAL delayvalidreg                    : std_logic;
  SIGNAL prevalidreg                      : std_logic;

BEGIN
  InValidRegister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        inValidReg <= '0';
      ELSE 
        inValidReg <= validIn;
      END IF;
    END IF;
  END PROCESS InValidRegister_process;


  dataIn_signed <= signed(dataIn);

  InRegister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        inReg <= to_signed(16#0000000#, 25);
      ELSE 
        inReg <= dataIn_signed;
      END IF;
    END IF;
  END PROCESS InRegister_process;


  tapDelay1Line_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        delayline1Num1 <= to_signed(16#0000000#, 25);
      ELSE 
        IF inValidReg = '1' THEN
          delayline1Num1 <= inReg;
        END IF;
      END IF;
    END IF;
  END PROCESS tapDelay1Line_process;


  numPre1Num1Reg1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        numPre11Num1 <= to_signed(16#0000000#, 25);
      ELSE 
        IF inValidReg = '1' THEN
          numPre11Num1 <= delayline1Num1;
        END IF;
      END IF;
    END IF;
  END PROCESS numPre1Num1Reg1_process;


  numPre1Num1Reg2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        numPre21Num1 <= to_signed(16#0000000#, 25);
      ELSE 
        IF inValidReg = '1' THEN
          numPre21Num1 <= numPre11Num1;
        END IF;
      END IF;
    END IF;
  END PROCESS numPre1Num1Reg2_process;


  prod1Num1 <= resize(numPre21Num1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 50);

  numPost1Num1Reg1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        numPost11Num1 <= to_signed(0, 50);
      ELSE 
        IF inValidReg = '1' THEN
          numPost11Num1 <= prod1Num1;
        END IF;
      END IF;
    END IF;
  END PROCESS numPost1Num1Reg1_process;


  numPost1Num1Reg2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        numPost21Num1 <= to_signed(0, 50);
      ELSE 
        IF inValidReg = '1' THEN
          numPost21Num1 <= numPost11Num1;
        END IF;
      END IF;
    END IF;
  END PROCESS numPost1Num1Reg2_process;


  tapDelay2Line_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        delayline2Num1 <= to_signed(16#0000000#, 25);
      ELSE 
        IF inValidReg = '1' THEN
          delayline2Num1 <= delayline1Num1;
        END IF;
      END IF;
    END IF;
  END PROCESS tapDelay2Line_process;


  numPre2Num1Reg1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        numPre12Num1 <= to_signed(16#0000000#, 25);
      ELSE 
        IF inValidReg = '1' THEN
          numPre12Num1 <= delayline2Num1;
        END IF;
      END IF;
    END IF;
  END PROCESS numPre2Num1Reg1_process;


  numPre2Num1Reg2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        numPre22Num1 <= to_signed(16#0000000#, 25);
      ELSE 
        IF inValidReg = '1' THEN
          numPre22Num1 <= numPre12Num1;
        END IF;
      END IF;
    END IF;
  END PROCESS numPre2Num1Reg2_process;


  prod2Num1 <= resize(numPre22Num1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 50);

  numPost2Num1Reg1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        numPost12Num1 <= to_signed(0, 50);
      ELSE 
        IF inValidReg = '1' THEN
          numPost12Num1 <= prod2Num1;
        END IF;
      END IF;
    END IF;
  END PROCESS numPost2Num1Reg1_process;


  numPost2Num1Reg2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        numPost22Num1 <= to_signed(0, 50);
      ELSE 
        IF inValidReg = '1' THEN
          numPost22Num1 <= numPost12Num1;
        END IF;
      END IF;
    END IF;
  END PROCESS numPost2Num1Reg2_process;


  adder_add_cast <= resize(numPost21Num1, 51);
  adder_add_cast_1 <= resize(numPost22Num1, 51);
  sumL1V1Num1 <= adder_add_cast + adder_add_cast_1;

  sumL1V1RegNum1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        sumregL1V1Num1 <= to_signed(0, 51);
      ELSE 
        IF inValidReg = '1' THEN
          sumregL1V1Num1 <= sumL1V1Num1;
        END IF;
      END IF;
    END IF;
  END PROCESS sumL1V1RegNum1_process;


  tapDelay3Line_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        delayline3Num1 <= to_signed(16#0000000#, 25);
      ELSE 
        IF inValidReg = '1' THEN
          delayline3Num1 <= delayline2Num1;
        END IF;
      END IF;
    END IF;
  END PROCESS tapDelay3Line_process;


  numPre3Num1Reg1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        numPre13Num1 <= to_signed(16#0000000#, 25);
      ELSE 
        IF inValidReg = '1' THEN
          numPre13Num1 <= delayline3Num1;
        END IF;
      END IF;
    END IF;
  END PROCESS numPre3Num1Reg1_process;


  numPre3Num1Reg2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        numPre23Num1 <= to_signed(16#0000000#, 25);
      ELSE 
        IF inValidReg = '1' THEN
          numPre23Num1 <= numPre13Num1;
        END IF;
      END IF;
    END IF;
  END PROCESS numPre3Num1Reg2_process;


  prod3Num1 <= to_signed(0, 50);

  numPost3Num1Reg1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        numPost13Num1 <= to_signed(0, 50);
      ELSE 
        IF inValidReg = '1' THEN
          numPost13Num1 <= prod3Num1;
        END IF;
      END IF;
    END IF;
  END PROCESS numPost3Num1Reg1_process;


  numPost3Num1Reg2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        numPost23Num1 <= to_signed(0, 50);
      ELSE 
        IF inValidReg = '1' THEN
          numPost23Num1 <= numPost13Num1;
        END IF;
      END IF;
    END IF;
  END PROCESS numPost3Num1Reg2_process;


  sumL1V2Num1 <= resize(numPost23Num1, 51);

  sumL1V2RegNum1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        sumregL1V2Num1 <= to_signed(0, 51);
      ELSE 
        IF inValidReg = '1' THEN
          sumregL1V2Num1 <= sumL1V2Num1;
        END IF;
      END IF;
    END IF;
  END PROCESS sumL1V2RegNum1_process;


  adder_add_cast_2 <= resize(sumregL1V1Num1, 52);
  adder_add_cast_3 <= resize(sumregL1V2Num1, 52);
  sumL2V1Num1 <= adder_add_cast_2 + adder_add_cast_3;

  sumL2V1RegNum1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        sumregL2V1Num1 <= to_signed(0, 52);
      ELSE 
        IF inValidReg = '1' THEN
          sumregL2V1Num1 <= sumL2V1Num1;
        END IF;
      END IF;
    END IF;
  END PROCESS sumL2V1RegNum1_process;


  tapDelay1Line_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        delayline1NumZero1 <= to_signed(0, 52);
      ELSE 
        IF inValidReg = '1' THEN
          delayline1NumZero1 <= sumregL2V1Num1;
        END IF;
      END IF;
    END IF;
  END PROCESS tapDelay1Line_1_process;


  numPre1NumZero1Reg1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        numPre11NumZero1 <= to_signed(0, 52);
      ELSE 
        IF inValidReg = '1' THEN
          numPre11NumZero1 <= delayline1NumZero1;
        END IF;
      END IF;
    END IF;
  END PROCESS numPre1NumZero1Reg1_process;


  numPre1NumZero1Reg2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        numPre21NumZero1 <= to_signed(0, 52);
      ELSE 
        IF inValidReg = '1' THEN
          numPre21NumZero1 <= numPre11NumZero1;
        END IF;
      END IF;
    END IF;
  END PROCESS numPre1NumZero1Reg2_process;


  prod1NumZero1 <= resize(numPre21NumZero1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 77);

  numPost1NumZero1Reg1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        numPost11NumZero1 <= to_signed(0, 77);
      ELSE 
        IF inValidReg = '1' THEN
          numPost11NumZero1 <= prod1NumZero1;
        END IF;
      END IF;
    END IF;
  END PROCESS numPost1NumZero1Reg1_process;


  numPost1NumZero1Reg2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        numPost21NumZero1 <= to_signed(0, 77);
      ELSE 
        IF inValidReg = '1' THEN
          numPost21NumZero1 <= numPost11NumZero1;
        END IF;
      END IF;
    END IF;
  END PROCESS numPost1NumZero1Reg2_process;


  tapDelay2Line_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        delayline2NumZero1 <= to_signed(0, 52);
      ELSE 
        IF inValidReg = '1' THEN
          delayline2NumZero1 <= delayline1NumZero1;
        END IF;
      END IF;
    END IF;
  END PROCESS tapDelay2Line_1_process;


  numPre2NumZero1Reg1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        numPre12NumZero1 <= to_signed(0, 52);
      ELSE 
        IF inValidReg = '1' THEN
          numPre12NumZero1 <= delayline2NumZero1;
        END IF;
      END IF;
    END IF;
  END PROCESS numPre2NumZero1Reg1_process;


  numPre2NumZero1Reg2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        numPre22NumZero1 <= to_signed(0, 52);
      ELSE 
        IF inValidReg = '1' THEN
          numPre22NumZero1 <= numPre12NumZero1;
        END IF;
      END IF;
    END IF;
  END PROCESS numPre2NumZero1Reg2_process;


  prod2NumZero1 <= to_signed(16#079B8F4#, 25) * numPre22NumZero1;

  numPost2NumZero1Reg1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        numPost12NumZero1 <= to_signed(0, 77);
      ELSE 
        IF inValidReg = '1' THEN
          numPost12NumZero1 <= prod2NumZero1;
        END IF;
      END IF;
    END IF;
  END PROCESS numPost2NumZero1Reg1_process;


  numPost2NumZero1Reg2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        numPost22NumZero1 <= to_signed(0, 77);
      ELSE 
        IF inValidReg = '1' THEN
          numPost22NumZero1 <= numPost12NumZero1;
        END IF;
      END IF;
    END IF;
  END PROCESS numPost2NumZero1Reg2_process;


  adder_add_cast_4 <= resize(numPost21NumZero1, 78);
  adder_add_cast_5 <= resize(numPost22NumZero1, 78);
  sumL1V1NumZero1 <= adder_add_cast_4 + adder_add_cast_5;

  sumL1V1RegNumZero1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        sumregL1V1NumZero1 <= to_signed(0, 78);
      ELSE 
        IF inValidReg = '1' THEN
          sumregL1V1NumZero1 <= sumL1V1NumZero1;
        END IF;
      END IF;
    END IF;
  END PROCESS sumL1V1RegNumZero1_process;


  tapDelay3Line_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        delayline3NumZero1 <= to_signed(0, 52);
      ELSE 
        IF inValidReg = '1' THEN
          delayline3NumZero1 <= delayline2NumZero1;
        END IF;
      END IF;
    END IF;
  END PROCESS tapDelay3Line_1_process;


  numPre3NumZero1Reg1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        numPre13NumZero1 <= to_signed(0, 52);
      ELSE 
        IF inValidReg = '1' THEN
          numPre13NumZero1 <= delayline3NumZero1;
        END IF;
      END IF;
    END IF;
  END PROCESS numPre3NumZero1Reg1_process;


  numPre3NumZero1Reg2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        numPre23NumZero1 <= to_signed(0, 52);
      ELSE 
        IF inValidReg = '1' THEN
          numPre23NumZero1 <= numPre13NumZero1;
        END IF;
      END IF;
    END IF;
  END PROCESS numPre3NumZero1Reg2_process;


  prod3NumZero1 <= to_signed(16#073C0B8#, 25) * numPre23NumZero1;

  numPost3NumZero1Reg1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        numPost13NumZero1 <= to_signed(0, 77);
      ELSE 
        IF inValidReg = '1' THEN
          numPost13NumZero1 <= prod3NumZero1;
        END IF;
      END IF;
    END IF;
  END PROCESS numPost3NumZero1Reg1_process;


  numPost3NumZero1Reg2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        numPost23NumZero1 <= to_signed(0, 77);
      ELSE 
        IF inValidReg = '1' THEN
          numPost23NumZero1 <= numPost13NumZero1;
        END IF;
      END IF;
    END IF;
  END PROCESS numPost3NumZero1Reg2_process;


  tapDelay4Line_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        delayline4NumZero1 <= to_signed(0, 52);
      ELSE 
        IF inValidReg = '1' THEN
          delayline4NumZero1 <= delayline3NumZero1;
        END IF;
      END IF;
    END IF;
  END PROCESS tapDelay4Line_process;


  numPre4NumZero1Reg1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        numPre14NumZero1 <= to_signed(0, 52);
      ELSE 
        IF inValidReg = '1' THEN
          numPre14NumZero1 <= delayline4NumZero1;
        END IF;
      END IF;
    END IF;
  END PROCESS numPre4NumZero1Reg1_process;


  numPre4NumZero1Reg2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        numPre24NumZero1 <= to_signed(0, 52);
      ELSE 
        IF inValidReg = '1' THEN
          numPre24NumZero1 <= numPre14NumZero1;
        END IF;
      END IF;
    END IF;
  END PROCESS numPre4NumZero1Reg2_process;


  prod4NumZero1 <= to_signed(16#06E136F#, 25) * numPre24NumZero1;

  numPost4NumZero1Reg1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        numPost14NumZero1 <= to_signed(0, 77);
      ELSE 
        IF inValidReg = '1' THEN
          numPost14NumZero1 <= prod4NumZero1;
        END IF;
      END IF;
    END IF;
  END PROCESS numPost4NumZero1Reg1_process;


  numPost4NumZero1Reg2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        numPost24NumZero1 <= to_signed(0, 77);
      ELSE 
        IF inValidReg = '1' THEN
          numPost24NumZero1 <= numPost14NumZero1;
        END IF;
      END IF;
    END IF;
  END PROCESS numPost4NumZero1Reg2_process;


  adder_add_cast_6 <= resize(numPost23NumZero1, 78);
  adder_add_cast_7 <= resize(numPost24NumZero1, 78);
  sumL1V2NumZero1 <= adder_add_cast_6 + adder_add_cast_7;

  sumL1V2RegNumZero1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        sumregL1V2NumZero1 <= to_signed(0, 78);
      ELSE 
        IF inValidReg = '1' THEN
          sumregL1V2NumZero1 <= sumL1V2NumZero1;
        END IF;
      END IF;
    END IF;
  END PROCESS sumL1V2RegNumZero1_process;


  adder_add_cast_8 <= resize(sumregL1V1NumZero1, 79);
  adder_add_cast_9 <= resize(sumregL1V2NumZero1, 79);
  sumL2V1NumZero1 <= adder_add_cast_8 + adder_add_cast_9;

  sumL2V1RegNumZero1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        sumregL2V1NumZero1 <= to_signed(0, 79);
      ELSE 
        IF inValidReg = '1' THEN
          sumregL2V1NumZero1 <= sumL2V1NumZero1;
        END IF;
      END IF;
    END IF;
  END PROCESS sumL2V1RegNumZero1_process;


  tapDelay5Line_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        delayline5NumZero1 <= to_signed(0, 52);
      ELSE 
        IF inValidReg = '1' THEN
          delayline5NumZero1 <= delayline4NumZero1;
        END IF;
      END IF;
    END IF;
  END PROCESS tapDelay5Line_process;


  numPre5NumZero1Reg1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        numPre15NumZero1 <= to_signed(0, 52);
      ELSE 
        IF inValidReg = '1' THEN
          numPre15NumZero1 <= delayline5NumZero1;
        END IF;
      END IF;
    END IF;
  END PROCESS numPre5NumZero1Reg1_process;


  numPre5NumZero1Reg2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        numPre25NumZero1 <= to_signed(0, 52);
      ELSE 
        IF inValidReg = '1' THEN
          numPre25NumZero1 <= numPre15NumZero1;
        END IF;
      END IF;
    END IF;
  END PROCESS numPre5NumZero1Reg2_process;


  prod5NumZero1 <= to_signed(0, 77);

  numPost5NumZero1Reg1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        numPost15NumZero1 <= to_signed(0, 77);
      ELSE 
        IF inValidReg = '1' THEN
          numPost15NumZero1 <= prod5NumZero1;
        END IF;
      END IF;
    END IF;
  END PROCESS numPost5NumZero1Reg1_process;


  numPost5NumZero1Reg2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        numPost25NumZero1 <= to_signed(0, 77);
      ELSE 
        IF inValidReg = '1' THEN
          numPost25NumZero1 <= numPost15NumZero1;
        END IF;
      END IF;
    END IF;
  END PROCESS numPost5NumZero1Reg2_process;


  tapDelay6Line_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        delayline6NumZero1 <= to_signed(0, 52);
      ELSE 
        IF inValidReg = '1' THEN
          delayline6NumZero1 <= delayline5NumZero1;
        END IF;
      END IF;
    END IF;
  END PROCESS tapDelay6Line_process;


  numPre6NumZero1Reg1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        numPre16NumZero1 <= to_signed(0, 52);
      ELSE 
        IF inValidReg = '1' THEN
          numPre16NumZero1 <= delayline6NumZero1;
        END IF;
      END IF;
    END IF;
  END PROCESS numPre6NumZero1Reg1_process;


  numPre6NumZero1Reg2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        numPre26NumZero1 <= to_signed(0, 52);
      ELSE 
        IF inValidReg = '1' THEN
          numPre26NumZero1 <= numPre16NumZero1;
        END IF;
      END IF;
    END IF;
  END PROCESS numPre6NumZero1Reg2_process;


  prod6NumZero1 <= to_signed(0, 77);

  numPost6NumZero1Reg1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        numPost16NumZero1 <= to_signed(0, 77);
      ELSE 
        IF inValidReg = '1' THEN
          numPost16NumZero1 <= prod6NumZero1;
        END IF;
      END IF;
    END IF;
  END PROCESS numPost6NumZero1Reg1_process;


  numPost6NumZero1Reg2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        numPost26NumZero1 <= to_signed(0, 77);
      ELSE 
        IF inValidReg = '1' THEN
          numPost26NumZero1 <= numPost16NumZero1;
        END IF;
      END IF;
    END IF;
  END PROCESS numPost6NumZero1Reg2_process;


  adder_add_cast_10 <= resize(numPost25NumZero1, 78);
  adder_add_cast_11 <= resize(numPost26NumZero1, 78);
  sumL1V3NumZero1 <= adder_add_cast_10 + adder_add_cast_11;

  sumL1V3RegNumZero1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        sumregL1V3NumZero1 <= to_signed(0, 78);
      ELSE 
        IF inValidReg = '1' THEN
          sumregL1V3NumZero1 <= sumL1V3NumZero1;
        END IF;
      END IF;
    END IF;
  END PROCESS sumL1V3RegNumZero1_process;


  tapDelay7Line_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        delayline7NumZero1 <= to_signed(0, 52);
      ELSE 
        IF inValidReg = '1' THEN
          delayline7NumZero1 <= delayline6NumZero1;
        END IF;
      END IF;
    END IF;
  END PROCESS tapDelay7Line_process;


  numPre7NumZero1Reg1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        numPre17NumZero1 <= to_signed(0, 52);
      ELSE 
        IF inValidReg = '1' THEN
          numPre17NumZero1 <= delayline7NumZero1;
        END IF;
      END IF;
    END IF;
  END PROCESS numPre7NumZero1Reg1_process;


  numPre7NumZero1Reg2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        numPre27NumZero1 <= to_signed(0, 52);
      ELSE 
        IF inValidReg = '1' THEN
          numPre27NumZero1 <= numPre17NumZero1;
        END IF;
      END IF;
    END IF;
  END PROCESS numPre7NumZero1Reg2_process;


  prod7NumZero1 <= to_signed(0, 77);

  numPost7NumZero1Reg1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        numPost17NumZero1 <= to_signed(0, 77);
      ELSE 
        IF inValidReg = '1' THEN
          numPost17NumZero1 <= prod7NumZero1;
        END IF;
      END IF;
    END IF;
  END PROCESS numPost7NumZero1Reg1_process;


  numPost7NumZero1Reg2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        numPost27NumZero1 <= to_signed(0, 77);
      ELSE 
        IF inValidReg = '1' THEN
          numPost27NumZero1 <= numPost17NumZero1;
        END IF;
      END IF;
    END IF;
  END PROCESS numPost7NumZero1Reg2_process;


  sumL1V4NumZero1 <= resize(numPost27NumZero1, 78);

  sumL1V4RegNumZero1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        sumregL1V4NumZero1 <= to_signed(0, 78);
      ELSE 
        IF inValidReg = '1' THEN
          sumregL1V4NumZero1 <= sumL1V4NumZero1;
        END IF;
      END IF;
    END IF;
  END PROCESS sumL1V4RegNumZero1_process;


  adder_add_cast_12 <= resize(sumregL1V3NumZero1, 79);
  adder_add_cast_13 <= resize(sumregL1V4NumZero1, 79);
  sumL2V2NumZero1 <= adder_add_cast_12 + adder_add_cast_13;

  sumL2V2RegNumZero1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        sumregL2V2NumZero1 <= to_signed(0, 79);
      ELSE 
        IF inValidReg = '1' THEN
          sumregL2V2NumZero1 <= sumL2V2NumZero1;
        END IF;
      END IF;
    END IF;
  END PROCESS sumL2V2RegNumZero1_process;


  adder_add_cast_14 <= resize(sumregL2V1NumZero1, 80);
  adder_add_cast_15 <= resize(sumregL2V2NumZero1, 80);
  sumL3V1NumZero1 <= adder_add_cast_14 + adder_add_cast_15;

  sumL3V1RegNumZero1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        sumregL3V1NumZero1 <= to_signed(0, 80);
      ELSE 
        IF inValidReg = '1' THEN
          sumregL3V1NumZero1 <= sumL3V1NumZero1;
        END IF;
      END IF;
    END IF;
  END PROCESS sumL3V1RegNumZero1_process;


  den2DelayReg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        den2DelayReg_reg <= (OTHERS => to_signed(16#0000000#, 25));
      ELSE 
        IF inValidReg = '1' THEN
          den2DelayReg_reg(0) <= denOut;
          den2DelayReg_reg(1 TO 2) <= den2DelayReg_reg(0 TO 1);
        END IF;
      END IF;
    END IF;
  END PROCESS den2DelayReg_process;

  denOutDelay <= den2DelayReg_reg(2);

  den2InPipeReg1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        den2InPipe1 <= to_signed(16#0000000#, 25);
      ELSE 
        IF inValidReg = '1' THEN
          den2InPipe1 <= denOutDelay;
        END IF;
      END IF;
    END IF;
  END PROCESS den2InPipeReg1_process;


  den2InPipeReg2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        den2InPipe2 <= to_signed(16#0000000#, 25);
      ELSE 
        IF inValidReg = '1' THEN
          den2InPipe2 <= den2InPipe1;
        END IF;
      END IF;
    END IF;
  END PROCESS den2InPipeReg2_process;


  denProd2 <= to_signed(0, 50);

  den2OutPipeReg1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        den2OutPipe1 <= to_signed(0, 50);
      ELSE 
        IF inValidReg = '1' THEN
          den2OutPipe1 <= denProd2;
        END IF;
      END IF;
    END IF;
  END PROCESS den2OutPipeReg1_process;


  State2Reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        state2 <= to_signed(0, 50);
      ELSE 
        IF inValidReg = '1' THEN
          state2 <= den2OutPipe1;
        END IF;
      END IF;
    END IF;
  END PROCESS State2Reg_process;


  den1InPipeReg1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        den1InPipe1 <= to_signed(16#0000000#, 25);
      ELSE 
        IF inValidReg = '1' THEN
          den1InPipe1 <= denOut;
        END IF;
      END IF;
    END IF;
  END PROCESS den1InPipeReg1_process;


  den1InPipeReg2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        den1InPipe2 <= to_signed(16#0000000#, 25);
      ELSE 
        IF inValidReg = '1' THEN
          den1InPipe2 <= den1InPipe1;
        END IF;
      END IF;
    END IF;
  END PROCESS den1InPipeReg2_process;


  denProd1 <= to_signed(16#068AD6D#, 25) * den1InPipe2;

  den1OutPipeReg1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        den1OutPipe1 <= to_signed(0, 50);
      ELSE 
        IF inValidReg = '1' THEN
          den1OutPipe1 <= denProd1;
        END IF;
      END IF;
    END IF;
  END PROCESS den1OutPipeReg1_process;


  adder_add_cast_16 <= resize(den1OutPipe1, 51);
  adder_add_cast_17 <= resize(state2, 51);
  denSum2 <= adder_add_cast_16 + adder_add_cast_17;

  State1Reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        state1 <= to_signed(0, 51);
      ELSE 
        IF inValidReg = '1' THEN
          state1 <= denSum2;
        END IF;
      END IF;
    END IF;
  END PROCESS State1Reg_process;


  adder_add_cast_18 <= resize(state1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 80);
  denSum1 <= sumregL3V1NumZero1 + adder_add_cast_18;

  
  denOut <= "0111111111111111111111111" WHEN ((denSum1(79) = '0') AND (denSum1(78 DOWNTO 70) /= "000000000")) OR ((denSum1(79) = '0') AND (denSum1(70 DOWNTO 46) = "0111111111111111111111111")) ELSE
      "1000000000000000000000000" WHEN (denSum1(79) = '1') AND (denSum1(78 DOWNTO 70) /= "111111111") ELSE
      denSum1(70 DOWNTO 46) + ('0' & denSum1(45));

  outputReg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        dataOut_tmp <= to_signed(16#0000000#, 25);
      ELSE 
        IF inValidReg = '1' THEN
          dataOut_tmp <= denOut;
        END IF;
      END IF;
    END IF;
  END PROCESS outputReg_process;


  dataOut <= std_logic_vector(dataOut_tmp);

  intdelay_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        intdelay_reg <= (OTHERS => '0');
      ELSE 
        IF inValidReg = '1' THEN
          intdelay_reg(0) <= inValidReg;
          intdelay_reg(14 DOWNTO 1) <= intdelay_reg(13 DOWNTO 0);
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_process;

  delayvalidreg <= intdelay_reg(14);

  prevalidreg <= inValidReg AND delayvalidreg;

  validoutputreg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        validOut <= '0';
      ELSE 
        validOut <= prevalidreg;
      END IF;
    END IF;
  END PROCESS validoutputreg_process;


END rtl;

