function designedFilter = WIDEIQFILT

% Generated by MATLAB(R) 26.1 and DSP System Toolbox 26.1.
% Generated on: 20-Jul-2026 22:57:55

designedFilter = designfilt('lowpassiir', ...
    'FilterOrder',1,'HalfPowerFrequency',1000000, ...
    'SampleRate',125000000,'ScaleSOS',true, ...
    'SystemObject',true);

designedFilter.NumeratorDataType=numerictype(true,25,24);
designedFilter.DenominatorDataType=numerictype(true,25,23);
designedFilter.ScaleValuesDataType=numerictype(true,25,28);

end