-- -------------------------------------------------------------
-- 
-- File Name: SEL_Reverted\hdlsrc\SEL_test\SEL_toTest_src_MIX.vhd
-- Created: 2026-07-27 16:14:57
-- 
-- Generated by MATLAB 26.1, HDL Coder 26.1, and Simulink 26.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: SEL_toTest_src_MIX
-- Source Path: SEL_test/TESTBENCH/SEL/SEL_WRAPPED/DSP_LOGIC/DEMUX/MIX
-- Hierarchy Level: 4
-- Model version: 1.616
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.SEL_toTest_src_SEL_pkg.ALL;

ENTITY SEL_toTest_src_MIX IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        adc_in_TDATA                      :   IN    std_logic_vector(15 DOWNTO 0);  -- int16
        mix_bus_in_NSIN_MIX               :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En23
        mix_bus_in_COS_MIX                :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En23
        valid_in                          :   IN    std_logic;
        Q_mix1                            :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En17
        I_mixed                           :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En17
        mix_bus_out_NSIN_MIX              :   OUT   std_logic_vector(24 DOWNTO 0);  -- sfix25_En23
        mix_bus_out_COS_MIX               :   OUT   std_logic_vector(24 DOWNTO 0);  -- sfix25_En23
        valid_out                         :   OUT   std_logic
        );
END SEL_toTest_src_MIX;


ARCHITECTURE rtl OF SEL_toTest_src_MIX IS

  -- Signals
  SIGNAL TDATA                            : signed(15 DOWNTO 0);  -- int16
  SIGNAL Data_Type_Conversion_out1        : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL rd_0_reg                         : vector_of_signed16(0 TO 1);  -- sfix16 [2]
  SIGNAL Data_Type_Conversion_out1_1      : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL Data_Type_Conversion_out1_2      : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL Data_Type_Conversion_out1_3      : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL Data_Type_Conversion_out1_4      : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL NSIN_MIX                         : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL NSIN_MIX_1                       : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL Q_mix_1                          : signed(40 DOWNTO 0);  -- sfix41_En38
  SIGNAL Q_mix_2                          : signed(40 DOWNTO 0);  -- sfix41_En38
  SIGNAL Q_mix_3                          : signed(17 DOWNTO 0);  -- sfix18_En17
  SIGNAL COS_MIX                          : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL COS_MIX_1                        : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL I_mixed_1                        : signed(40 DOWNTO 0);  -- sfix41_En38
  SIGNAL I_mixed_2                        : signed(40 DOWNTO 0);  -- sfix41_En38
  SIGNAL I_mixed_tmp                      : signed(17 DOWNTO 0);  -- sfix18_En17

  ATTRIBUTE use_dsp : string;

  ATTRIBUTE use_dsp OF Q_mix_1 : SIGNAL IS "yes";
  ATTRIBUTE use_dsp OF I_mixed_1 : SIGNAL IS "yes";

BEGIN
  TDATA <= signed(adc_in_TDATA);

  Data_Type_Conversion_out1 <= TDATA;

  rd_0_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        rd_0_reg <= (OTHERS => to_signed(16#0000#, 16));
      ELSE 
        rd_0_reg(0) <= Data_Type_Conversion_out1;
        rd_0_reg(1) <= rd_0_reg(0);
      END IF;
    END IF;
  END PROCESS rd_0_process;

  Data_Type_Conversion_out1_1 <= rd_0_reg(1);

  reduced_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Data_Type_Conversion_out1_2 <= to_signed(16#0000#, 16);
      ELSE 
        Data_Type_Conversion_out1_2 <= Data_Type_Conversion_out1_1;
      END IF;
    END IF;
  END PROCESS reduced_process;


  reduced_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Data_Type_Conversion_out1_3 <= to_signed(16#0000#, 16);
      ELSE 
        Data_Type_Conversion_out1_3 <= Data_Type_Conversion_out1_2;
      END IF;
    END IF;
  END PROCESS reduced_1_process;


  HwModeRegister2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Data_Type_Conversion_out1_4 <= to_signed(16#0000#, 16);
      ELSE 
        Data_Type_Conversion_out1_4 <= Data_Type_Conversion_out1_3;
      END IF;
    END IF;
  END PROCESS HwModeRegister2_process;


  NSIN_MIX <= signed(mix_bus_in_NSIN_MIX);

  HwModeRegister3_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        NSIN_MIX_1 <= to_signed(16#0000000#, 25);
      ELSE 
        NSIN_MIX_1 <= NSIN_MIX;
      END IF;
    END IF;
  END PROCESS HwModeRegister3_process;


  Q_mix_1 <= Data_Type_Conversion_out1_4 * NSIN_MIX_1;

  PipelineRegister1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Q_mix_2 <= to_signed(0, 41);
      ELSE 
        Q_mix_2 <= Q_mix_1;
      END IF;
    END IF;
  END PROCESS PipelineRegister1_process;


  
  Q_mix_3 <= "011111111111111111" WHEN ((Q_mix_2(40) = '0') AND (Q_mix_2(39 DOWNTO 38) /= "00")) OR ((Q_mix_2(40) = '0') AND (Q_mix_2(38 DOWNTO 21) = "011111111111111111")) ELSE
      "100000000000000000" WHEN (Q_mix_2(40) = '1') AND (Q_mix_2(39 DOWNTO 38) /= "11") ELSE
      Q_mix_2(38 DOWNTO 21) + ('0' & Q_mix_2(20));

  Q_mix1 <= std_logic_vector(Q_mix_3);

  COS_MIX <= signed(mix_bus_in_COS_MIX);

  HwModeRegister1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        COS_MIX_1 <= to_signed(16#0000000#, 25);
      ELSE 
        COS_MIX_1 <= COS_MIX;
      END IF;
    END IF;
  END PROCESS HwModeRegister1_process;


  I_mixed_1 <= Data_Type_Conversion_out1_2 * COS_MIX_1;

  PipelineRegister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        I_mixed_2 <= to_signed(0, 41);
      ELSE 
        I_mixed_2 <= I_mixed_1;
      END IF;
    END IF;
  END PROCESS PipelineRegister_process;


  
  I_mixed_tmp <= "011111111111111111" WHEN ((I_mixed_2(40) = '0') AND (I_mixed_2(39 DOWNTO 38) /= "00")) OR ((I_mixed_2(40) = '0') AND (I_mixed_2(38 DOWNTO 21) = "011111111111111111")) ELSE
      "100000000000000000" WHEN (I_mixed_2(40) = '1') AND (I_mixed_2(39 DOWNTO 38) /= "11") ELSE
      I_mixed_2(38 DOWNTO 21) + ('0' & I_mixed_2(20));

  I_mixed <= std_logic_vector(I_mixed_tmp);

  mix_bus_out_NSIN_MIX <= mix_bus_in_NSIN_MIX;

  mix_bus_out_COS_MIX <= mix_bus_in_COS_MIX;

  valid_out <= valid_in;

END rtl;

