-- -------------------------------------------------------------
-- 
-- File Name: SEL_Reverted\hdlsrc\SEL_test\SEL_toTest_src_DSP_LOGIC.vhd
-- Created: 2026-07-27 16:14:58
-- 
-- Generated by MATLAB 26.1, HDL Coder 26.1, and Simulink 26.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: SEL_toTest_src_DSP_LOGIC
-- Source Path: SEL_test/TESTBENCH/SEL/SEL_WRAPPED/DSP_LOGIC
-- Hierarchy Level: 2
-- Model version: 1.616
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.SEL_toTest_src_SEL_pkg.ALL;

ENTITY SEL_toTest_src_DSP_LOGIC IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        ADC1_IN_TDATA                     :   IN    std_logic_vector(15 DOWNTO 0);  -- int16
        AXI_LITE_CONTROL_PHASE_COS        :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
        AXI_LITE_CONTROL_PHASE_SIN        :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
        AXI_LITE_CONTROL_MAG_SET          :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
        AXI_LITE_CONTROL_K_HIGH           :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
        AXI_LITE_CONTROL_K_LOW            :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
        AXI_LITE_CONTROL_PULSE_WIDTH      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        AXI_LITE_CONTROL_PULSE_EN         :   IN    std_logic;
        AXI_LITE_CONTROL_AUTO_EN          :   IN    std_logic;
        AXI_LITE_CONTROL_REP_PERIOD       :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        DAC1_OUT_TDATA                    :   OUT   std_logic_vector(15 DOWNTO 0);  -- int16
        DAC1_OUT_TVALID                   :   OUT   std_logic
        );
END SEL_toTest_src_DSP_LOGIC;


ARCHITECTURE rtl OF SEL_toTest_src_DSP_LOGIC IS

  -- Component Declarations
  COMPONENT SEL_toTest_src_DEMUX
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          adc_TDATA                       :   IN    std_logic_vector(15 DOWNTO 0);  -- int16
          I                               :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En17
          Q                               :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En17
          valid_o                         :   OUT   std_logic;
          Mix_bus_NSIN_MIX                :   OUT   std_logic_vector(24 DOWNTO 0);  -- sfix25_En23
          Mix_bus_COS_MIX                 :   OUT   std_logic_vector(24 DOWNTO 0)  -- sfix25_En23
          );
  END COMPONENT;

  COMPONENT SEL_toTest_src_LPF
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          I                               :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En17
          Q                               :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En17
          valid                           :   IN    std_logic;
          I_filtered                      :   OUT   std_logic_vector(24 DOWNTO 0);  -- sfix25_En23
          Q_filtered                      :   OUT   std_logic_vector(24 DOWNTO 0);  -- sfix25_En23
          valid_o                         :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT SEL_toTest_src_NORMALIZE
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          I                               :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En23
          Q                               :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En23
          valid                           :   IN    std_logic;
          pulse_bus_K_HIGH                :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
          pulse_bus_K_LOW                 :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
          pulse_bus_PULSE_WIDTH           :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          pulse_bus_PULSE_EN              :   IN    std_logic;
          pulse_bus_AUTO_EN               :   IN    std_logic;
          pulse_bus_REP_PERIOD            :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          I_normalized                    :   OUT   std_logic_vector(24 DOWNTO 0);  -- sfix25_En23
          Q_normalized                    :   OUT   std_logic_vector(24 DOWNTO 0);  -- sfix25_En23
          valid_o                         :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT SEL_toTest_src_COMPLEX_ROTATE
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          I                               :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En23
          Q                               :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En23
          valid                           :   IN    std_logic;
          user_offset_PHASE_COS           :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
          user_offset_PHASE_SIN           :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
          I_offset                        :   OUT   std_logic_vector(25 DOWNTO 0);  -- sfix26_En23
          Q_offset                        :   OUT   std_logic_vector(25 DOWNTO 0);  -- sfix26_En23
          valid_o                         :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT SEL_toTest_src_MUX
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          I                               :   IN    std_logic_vector(25 DOWNTO 0);  -- sfix26_En23
          Q                               :   IN    std_logic_vector(25 DOWNTO 0);  -- sfix26_En23
          valid                           :   IN    std_logic;
          mix_bus_NSIN_MIX                :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En23
          mix_bus_COS_MIX                 :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En23
          user_gain_MAG_SET               :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
          dac_o_TDATA                     :   OUT   std_logic_vector(15 DOWNTO 0);  -- int16
          dac_o_TVALID                    :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : SEL_toTest_src_DEMUX
    USE ENTITY work.SEL_toTest_src_DEMUX(rtl);

  FOR ALL : SEL_toTest_src_LPF
    USE ENTITY work.SEL_toTest_src_LPF(rtl);

  FOR ALL : SEL_toTest_src_NORMALIZE
    USE ENTITY work.SEL_toTest_src_NORMALIZE(rtl);

  FOR ALL : SEL_toTest_src_COMPLEX_ROTATE
    USE ENTITY work.SEL_toTest_src_COMPLEX_ROTATE(rtl);

  FOR ALL : SEL_toTest_src_MUX
    USE ENTITY work.SEL_toTest_src_MUX(rtl);

  -- Signals
  SIGNAL DEMUX_I                          : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL DEMUX_Q                          : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL DEMUX_valid_o                    : std_logic;
  SIGNAL DEMUX_Mix_bus_NSIN_MIX           : std_logic_vector(24 DOWNTO 0);  -- ufix25
  SIGNAL DEMUX_Mix_bus_COS_MIX            : std_logic_vector(24 DOWNTO 0);  -- ufix25
  SIGNAL LPF_I_filtered                   : std_logic_vector(24 DOWNTO 0);  -- ufix25
  SIGNAL LPF_Q_filtered                   : std_logic_vector(24 DOWNTO 0);  -- ufix25
  SIGNAL LPF_valid_o                      : std_logic;
  SIGNAL NORMALIZE_I_normalized           : std_logic_vector(24 DOWNTO 0);  -- ufix25
  SIGNAL NORMALIZE_Q_normalized           : std_logic_vector(24 DOWNTO 0);  -- ufix25
  SIGNAL NORMALIZE_valid_o                : std_logic;
  SIGNAL COMPLEX_ROTATE_I_offset          : std_logic_vector(25 DOWNTO 0);  -- ufix26
  SIGNAL COMPLEX_ROTATE_Q_offset          : std_logic_vector(25 DOWNTO 0);  -- ufix26
  SIGNAL COMPLEX_ROTATE_valid_o           : std_logic;
  SIGNAL DEMUX_Mix_bus_NSIN_MIX_signed    : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL rd_0_reg                         : vector_of_signed25(0 TO 15);  -- sfix25 [16]
  SIGNAL NSIN_MIX                         : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL DEMUX_Mix_bus_COS_MIX_signed     : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL rd_1_reg                         : vector_of_signed25(0 TO 17);  -- sfix25 [18]
  SIGNAL COS_MIX                          : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL MUX_dac_o_TDATA                  : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL MUX_dac_o_TVALID                 : std_logic;

BEGIN
  u_DEMUX : SEL_toTest_src_DEMUX
    PORT MAP( clk => clk,
              reset => reset,
              adc_TDATA => ADC1_IN_TDATA,  -- int16
              I => DEMUX_I,  -- sfix18_En17
              Q => DEMUX_Q,  -- sfix18_En17
              valid_o => DEMUX_valid_o,
              Mix_bus_NSIN_MIX => DEMUX_Mix_bus_NSIN_MIX,  -- sfix25_En23
              Mix_bus_COS_MIX => DEMUX_Mix_bus_COS_MIX  -- sfix25_En23
              );

  u_LPF : SEL_toTest_src_LPF
    PORT MAP( clk => clk,
              reset => reset,
              I => DEMUX_I,  -- sfix18_En17
              Q => DEMUX_Q,  -- sfix18_En17
              valid => DEMUX_valid_o,
              I_filtered => LPF_I_filtered,  -- sfix25_En23
              Q_filtered => LPF_Q_filtered,  -- sfix25_En23
              valid_o => LPF_valid_o
              );

  u_NORMALIZE : SEL_toTest_src_NORMALIZE
    PORT MAP( clk => clk,
              reset => reset,
              I => LPF_I_filtered,  -- sfix25_En23
              Q => LPF_Q_filtered,  -- sfix25_En23
              valid => LPF_valid_o,
              pulse_bus_K_HIGH => AXI_LITE_CONTROL_K_HIGH,  -- sfix18_En16
              pulse_bus_K_LOW => AXI_LITE_CONTROL_K_LOW,  -- sfix18_En16
              pulse_bus_PULSE_WIDTH => AXI_LITE_CONTROL_PULSE_WIDTH,  -- uint32
              pulse_bus_PULSE_EN => AXI_LITE_CONTROL_PULSE_EN,
              pulse_bus_AUTO_EN => AXI_LITE_CONTROL_AUTO_EN,
              pulse_bus_REP_PERIOD => AXI_LITE_CONTROL_REP_PERIOD,  -- uint32
              I_normalized => NORMALIZE_I_normalized,  -- sfix25_En23
              Q_normalized => NORMALIZE_Q_normalized,  -- sfix25_En23
              valid_o => NORMALIZE_valid_o
              );

  u_COMPLEX_ROTATE : SEL_toTest_src_COMPLEX_ROTATE
    PORT MAP( clk => clk,
              reset => reset,
              I => NORMALIZE_I_normalized,  -- sfix25_En23
              Q => NORMALIZE_Q_normalized,  -- sfix25_En23
              valid => NORMALIZE_valid_o,
              user_offset_PHASE_COS => AXI_LITE_CONTROL_PHASE_COS,  -- sfix18_En16
              user_offset_PHASE_SIN => AXI_LITE_CONTROL_PHASE_SIN,  -- sfix18_En16
              I_offset => COMPLEX_ROTATE_I_offset,  -- sfix26_En23
              Q_offset => COMPLEX_ROTATE_Q_offset,  -- sfix26_En23
              valid_o => COMPLEX_ROTATE_valid_o
              );

  u_MUX : SEL_toTest_src_MUX
    PORT MAP( clk => clk,
              reset => reset,
              I => COMPLEX_ROTATE_I_offset,  -- sfix26_En23
              Q => COMPLEX_ROTATE_Q_offset,  -- sfix26_En23
              valid => COMPLEX_ROTATE_valid_o,
              mix_bus_NSIN_MIX => std_logic_vector(NSIN_MIX),  -- sfix25_En23
              mix_bus_COS_MIX => std_logic_vector(COS_MIX),  -- sfix25_En23
              user_gain_MAG_SET => AXI_LITE_CONTROL_MAG_SET,  -- sfix18_En16
              dac_o_TDATA => MUX_dac_o_TDATA,  -- int16
              dac_o_TVALID => MUX_dac_o_TVALID
              );

  DEMUX_Mix_bus_NSIN_MIX_signed <= signed(DEMUX_Mix_bus_NSIN_MIX);

  rd_0_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        rd_0_reg <= (OTHERS => to_signed(16#0000000#, 25));
      ELSE 
        rd_0_reg(0) <= DEMUX_Mix_bus_NSIN_MIX_signed;
        rd_0_reg(1 TO 15) <= rd_0_reg(0 TO 14);
      END IF;
    END IF;
  END PROCESS rd_0_process;

  NSIN_MIX <= rd_0_reg(15);

  DEMUX_Mix_bus_COS_MIX_signed <= signed(DEMUX_Mix_bus_COS_MIX);

  rd_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        rd_1_reg <= (OTHERS => to_signed(16#0000000#, 25));
      ELSE 
        rd_1_reg(0) <= DEMUX_Mix_bus_COS_MIX_signed;
        rd_1_reg(1 TO 17) <= rd_1_reg(0 TO 16);
      END IF;
    END IF;
  END PROCESS rd_1_process;

  COS_MIX <= rd_1_reg(17);

  DAC1_OUT_TDATA <= MUX_dac_o_TDATA;

  DAC1_OUT_TVALID <= MUX_dac_o_TVALID;

END rtl;

