-- -------------------------------------------------------------
-- 
-- File Name: SEL_Reverted\hdlsrc\SEL_test\SEL_toTest.vhd
-- Created: 2026-07-27 16:15:07
-- 
-- Generated by MATLAB 26.1, HDL Coder 26.1, and Simulink 26.1
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: -1
-- Target subsystem base rate: -1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: SEL_toTest
-- Source Path: SEL_toTest
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY SEL_toTest IS
  PORT( IPCORE_CLK                        :   IN    std_logic;  -- ufix1
        IPCORE_RESETN                     :   IN    std_logic;  -- ufix1
        AXI4_Stream_DAC2_Master_TREADY    :   IN    std_logic;  -- ufix1
        AXI4_Stream_DAC1_Master_TREADY    :   IN    std_logic;  -- ufix1
        AXI4_Stream_ADC1_Slave_TDATA      :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16
        AXI4_Stream_ADC1_Slave_TVALID     :   IN    std_logic;  -- ufix1
        AXI4_Lite_ACLK                    :   IN    std_logic;  -- ufix1
        AXI4_Lite_ARESETN                 :   IN    std_logic;  -- ufix1
        AXI4_Lite_AWADDR                  :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16
        AXI4_Lite_AWVALID                 :   IN    std_logic;  -- ufix1
        AXI4_Lite_WDATA                   :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        AXI4_Lite_WSTRB                   :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
        AXI4_Lite_WVALID                  :   IN    std_logic;  -- ufix1
        AXI4_Lite_BREADY                  :   IN    std_logic;  -- ufix1
        AXI4_Lite_ARADDR                  :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16
        AXI4_Lite_ARVALID                 :   IN    std_logic;  -- ufix1
        AXI4_Lite_RREADY                  :   IN    std_logic;  -- ufix1
        AXI4_Stream_DAC2_Master_TDATA     :   OUT   std_logic_vector(15 DOWNTO 0);  -- ufix16
        AXI4_Stream_DAC2_Master_TVALID    :   OUT   std_logic;  -- ufix1
        AXI4_Stream_DAC2_Master_TLAST     :   OUT   std_logic;  -- ufix1
        AXI4_Stream_DAC1_Master_TDATA     :   OUT   std_logic_vector(15 DOWNTO 0);  -- ufix16
        AXI4_Stream_DAC1_Master_TVALID    :   OUT   std_logic;  -- ufix1
        AXI4_Stream_DAC1_Master_TLAST     :   OUT   std_logic;  -- ufix1
        AXI4_Stream_ADC1_Slave_TREADY     :   OUT   std_logic;  -- ufix1
        AXI4_Lite_AWREADY                 :   OUT   std_logic;  -- ufix1
        AXI4_Lite_WREADY                  :   OUT   std_logic;  -- ufix1
        AXI4_Lite_BRESP                   :   OUT   std_logic_vector(1 DOWNTO 0);  -- ufix2
        AXI4_Lite_BVALID                  :   OUT   std_logic;  -- ufix1
        AXI4_Lite_ARREADY                 :   OUT   std_logic;  -- ufix1
        AXI4_Lite_RDATA                   :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        AXI4_Lite_RRESP                   :   OUT   std_logic_vector(1 DOWNTO 0);  -- ufix2
        AXI4_Lite_RVALID                  :   OUT   std_logic  -- ufix1
        );
END SEL_toTest;


ARCHITECTURE rtl OF SEL_toTest IS

  -- Component Declarations
  COMPONENT SEL_toTest_axi_lite
    PORT( reset                           :   IN    std_logic;
          AXI4_Lite_ACLK                  :   IN    std_logic;  -- ufix1
          AXI4_Lite_ARESETN               :   IN    std_logic;  -- ufix1
          AXI4_Lite_AWADDR                :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16
          AXI4_Lite_AWVALID               :   IN    std_logic;  -- ufix1
          AXI4_Lite_WDATA                 :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          AXI4_Lite_WSTRB                 :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
          AXI4_Lite_WVALID                :   IN    std_logic;  -- ufix1
          AXI4_Lite_BREADY                :   IN    std_logic;  -- ufix1
          AXI4_Lite_ARADDR                :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16
          AXI4_Lite_ARVALID               :   IN    std_logic;  -- ufix1
          AXI4_Lite_RREADY                :   IN    std_logic;  -- ufix1
          read_ip_timestamp               :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          AXI4_Lite_AWREADY               :   OUT   std_logic;  -- ufix1
          AXI4_Lite_WREADY                :   OUT   std_logic;  -- ufix1
          AXI4_Lite_BRESP                 :   OUT   std_logic_vector(1 DOWNTO 0);  -- ufix2
          AXI4_Lite_BVALID                :   OUT   std_logic;  -- ufix1
          AXI4_Lite_ARREADY               :   OUT   std_logic;  -- ufix1
          AXI4_Lite_RDATA                 :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          AXI4_Lite_RRESP                 :   OUT   std_logic_vector(1 DOWNTO 0);  -- ufix2
          AXI4_Lite_RVALID                :   OUT   std_logic;  -- ufix1
          write_packet_size_axi4_stream_dac2_master :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          write_packet_size_axi4_stream_dac1_master :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          write_AXI4_LITE_CONTROL_PHASE_COS :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
          write_AXI4_LITE_CONTROL_PHASE_SIN :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
          write_AXI4_LITE_CONTROL_MAG_SET :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
          write_AXI4_LITE_CONTROL_K_HIGH  :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
          write_AXI4_LITE_CONTROL_K_LOW   :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
          write_AXI4_LITE_CONTROL_PULSE_WIDTH :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          write_AXI4_LITE_CONTROL_PULSE_EN :   OUT   std_logic;  -- ufix1
          write_AXI4_LITE_CONTROL_AUTO_EN :   OUT   std_logic;  -- ufix1
          write_AXI4_LITE_CONTROL_REP_PERIOD :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          reset_internal                  :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  COMPONENT SEL_toTest_reset_sync
    PORT( clk_in                          :   IN    std_logic;
          reset_in                        :   IN    std_logic;  -- ufix1
          reset_out                       :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT SEL_toTest_axi4_stream_adc1_slave
    PORT( clk                             :   IN    std_logic;  -- ufix1
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          AXI4_Stream_ADC1_Slave_TDATA    :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16
          AXI4_Stream_ADC1_Slave_TVALID   :   IN    std_logic;  -- ufix1
          AXI4_Stream_ADC1_Slave_TREADY   :   OUT   std_logic;  -- ufix1
          user_data                       :   OUT   std_logic_vector(15 DOWNTO 0);  -- ufix16
          user_valid                      :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  COMPONENT SEL_toTest_dut
    PORT( clk_1                           :   IN    std_logic;
          reset_1                         :   IN    std_logic;
          S_AXIS_ADC1_TDATA               :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16
          S_AXIS_ADC1_TVALID              :   IN    std_logic;  -- ufix1
          AXI4_LITE_CONTROL_PHASE_COS     :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
          AXI4_LITE_CONTROL_PHASE_SIN     :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
          AXI4_LITE_CONTROL_MAG_SET       :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
          AXI4_LITE_CONTROL_K_HIGH        :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
          AXI4_LITE_CONTROL_K_LOW         :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
          AXI4_LITE_CONTROL_PULSE_WIDTH   :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          AXI4_LITE_CONTROL_PULSE_EN      :   IN    std_logic;  -- ufix1
          AXI4_LITE_CONTROL_AUTO_EN       :   IN    std_logic;  -- ufix1
          AXI4_LITE_CONTROL_REP_PERIOD    :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          M_AXIS_DAC1_TDATA               :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16
          M_AXIS_DAC1_TVALID              :   OUT   std_logic;  -- ufix1
          M_AXIS_DAC2_TDATA               :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16
          M_AXIS_DAC2_TVALID              :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  COMPONENT SEL_toTest_axi4_stream_dac2_master
    PORT( clk                             :   IN    std_logic;  -- ufix1
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          AXI4_Stream_DAC2_Master_TREADY  :   IN    std_logic;  -- ufix1
          user_data                       :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16
          user_valid                      :   IN    std_logic;  -- ufix1
          write_packet_size_axi4_stream_dac2_master :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          AXI4_Stream_DAC2_Master_TDATA   :   OUT   std_logic_vector(15 DOWNTO 0);  -- ufix16
          AXI4_Stream_DAC2_Master_TVALID  :   OUT   std_logic;  -- ufix1
          AXI4_Stream_DAC2_Master_TLAST   :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  COMPONENT SEL_toTest_axi4_stream_dac1_master
    PORT( clk                             :   IN    std_logic;  -- ufix1
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          AXI4_Stream_DAC1_Master_TREADY  :   IN    std_logic;  -- ufix1
          user_data                       :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16
          user_valid                      :   IN    std_logic;  -- ufix1
          write_packet_size_axi4_stream_dac1_master :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          AXI4_Stream_DAC1_Master_TDATA   :   OUT   std_logic_vector(15 DOWNTO 0);  -- ufix16
          AXI4_Stream_DAC1_Master_TVALID  :   OUT   std_logic;  -- ufix1
          AXI4_Stream_DAC1_Master_TLAST   :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : SEL_toTest_axi_lite
    USE ENTITY work.SEL_toTest_axi_lite(rtl);

  FOR ALL : SEL_toTest_reset_sync
    USE ENTITY work.SEL_toTest_reset_sync(rtl);

  FOR ALL : SEL_toTest_axi4_stream_adc1_slave
    USE ENTITY work.SEL_toTest_axi4_stream_adc1_slave(rtl);

  FOR ALL : SEL_toTest_dut
    USE ENTITY work.SEL_toTest_dut(rtl);

  FOR ALL : SEL_toTest_axi4_stream_dac2_master
    USE ENTITY work.SEL_toTest_axi4_stream_dac2_master(rtl);

  FOR ALL : SEL_toTest_axi4_stream_dac1_master
    USE ENTITY work.SEL_toTest_axi4_stream_dac1_master(rtl);

  -- Signals
  SIGNAL reset                            : std_logic;
  SIGNAL const_1                          : std_logic;  -- ufix1
  SIGNAL reset_cm                         : std_logic;  -- ufix1
  SIGNAL ip_timestamp                     : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL AXI4_Lite_BRESP_tmp              : std_logic_vector(1 DOWNTO 0);  -- ufix2
  SIGNAL AXI4_Lite_RDATA_tmp              : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL AXI4_Lite_RRESP_tmp              : std_logic_vector(1 DOWNTO 0);  -- ufix2
  SIGNAL write_packet_size_axi4_stream_dac2_master : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL write_packet_size_axi4_stream_dac1_master : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL write_AXI4_LITE_CONTROL_PHASE_COS : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL write_AXI4_LITE_CONTROL_PHASE_SIN : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL write_AXI4_LITE_CONTROL_MAG_SET  : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL write_AXI4_LITE_CONTROL_K_HIGH   : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL write_AXI4_LITE_CONTROL_K_LOW    : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL write_AXI4_LITE_CONTROL_PULSE_WIDTH : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL write_AXI4_LITE_CONTROL_PULSE_EN : std_logic;  -- ufix1
  SIGNAL write_AXI4_LITE_CONTROL_AUTO_EN  : std_logic;  -- ufix1
  SIGNAL write_AXI4_LITE_CONTROL_REP_PERIOD : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL reset_internal                   : std_logic;  -- ufix1
  SIGNAL reset_before_sync                : std_logic;  -- ufix1
  SIGNAL top_user_data                    : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL top_user_valid                   : std_logic;  -- ufix1
  SIGNAL top_user_data_unsigned           : unsigned(15 DOWNTO 0);  -- ufix16
  SIGNAL S_AXIS_ADC1_TDATA_sig            : signed(15 DOWNTO 0);  -- sfix16
  SIGNAL M_AXIS_DAC1_TDATA_sig            : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL M_AXIS_DAC1_TVALID_sig           : std_logic;  -- ufix1
  SIGNAL M_AXIS_DAC2_TDATA_sig            : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL M_AXIS_DAC2_TVALID_sig           : std_logic;  -- ufix1
  SIGNAL M_AXIS_DAC2_TDATA_sig_signed     : signed(15 DOWNTO 0);  -- sfix16
  SIGNAL top_user_data_1                  : unsigned(15 DOWNTO 0);  -- ufix16
  SIGNAL AXI4_Stream_DAC2_Master_TDATA_tmp : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL M_AXIS_DAC1_TDATA_sig_signed     : signed(15 DOWNTO 0);  -- sfix16
  SIGNAL top_user_data_2                  : unsigned(15 DOWNTO 0);  -- ufix16
  SIGNAL AXI4_Stream_DAC1_Master_TDATA_tmp : std_logic_vector(15 DOWNTO 0);  -- ufix16

BEGIN
  u_SEL_toTest_axi_lite_inst : SEL_toTest_axi_lite
    PORT MAP( reset => reset,
              AXI4_Lite_ACLK => AXI4_Lite_ACLK,  -- ufix1
              AXI4_Lite_ARESETN => AXI4_Lite_ARESETN,  -- ufix1
              AXI4_Lite_AWADDR => AXI4_Lite_AWADDR,  -- ufix16
              AXI4_Lite_AWVALID => AXI4_Lite_AWVALID,  -- ufix1
              AXI4_Lite_WDATA => AXI4_Lite_WDATA,  -- ufix32
              AXI4_Lite_WSTRB => AXI4_Lite_WSTRB,  -- ufix4
              AXI4_Lite_WVALID => AXI4_Lite_WVALID,  -- ufix1
              AXI4_Lite_BREADY => AXI4_Lite_BREADY,  -- ufix1
              AXI4_Lite_ARADDR => AXI4_Lite_ARADDR,  -- ufix16
              AXI4_Lite_ARVALID => AXI4_Lite_ARVALID,  -- ufix1
              AXI4_Lite_RREADY => AXI4_Lite_RREADY,  -- ufix1
              read_ip_timestamp => std_logic_vector(ip_timestamp),  -- ufix32
              AXI4_Lite_AWREADY => AXI4_Lite_AWREADY,  -- ufix1
              AXI4_Lite_WREADY => AXI4_Lite_WREADY,  -- ufix1
              AXI4_Lite_BRESP => AXI4_Lite_BRESP_tmp,  -- ufix2
              AXI4_Lite_BVALID => AXI4_Lite_BVALID,  -- ufix1
              AXI4_Lite_ARREADY => AXI4_Lite_ARREADY,  -- ufix1
              AXI4_Lite_RDATA => AXI4_Lite_RDATA_tmp,  -- ufix32
              AXI4_Lite_RRESP => AXI4_Lite_RRESP_tmp,  -- ufix2
              AXI4_Lite_RVALID => AXI4_Lite_RVALID,  -- ufix1
              write_packet_size_axi4_stream_dac2_master => write_packet_size_axi4_stream_dac2_master,  -- ufix32
              write_packet_size_axi4_stream_dac1_master => write_packet_size_axi4_stream_dac1_master,  -- ufix32
              write_AXI4_LITE_CONTROL_PHASE_COS => write_AXI4_LITE_CONTROL_PHASE_COS,  -- sfix18_En16
              write_AXI4_LITE_CONTROL_PHASE_SIN => write_AXI4_LITE_CONTROL_PHASE_SIN,  -- sfix18_En16
              write_AXI4_LITE_CONTROL_MAG_SET => write_AXI4_LITE_CONTROL_MAG_SET,  -- sfix18_En16
              write_AXI4_LITE_CONTROL_K_HIGH => write_AXI4_LITE_CONTROL_K_HIGH,  -- sfix18_En16
              write_AXI4_LITE_CONTROL_K_LOW => write_AXI4_LITE_CONTROL_K_LOW,  -- sfix18_En16
              write_AXI4_LITE_CONTROL_PULSE_WIDTH => write_AXI4_LITE_CONTROL_PULSE_WIDTH,  -- ufix32
              write_AXI4_LITE_CONTROL_PULSE_EN => write_AXI4_LITE_CONTROL_PULSE_EN,  -- ufix1
              write_AXI4_LITE_CONTROL_AUTO_EN => write_AXI4_LITE_CONTROL_AUTO_EN,  -- ufix1
              write_AXI4_LITE_CONTROL_REP_PERIOD => write_AXI4_LITE_CONTROL_REP_PERIOD,  -- ufix32
              reset_internal => reset_internal  -- ufix1
              );

  u_SEL_toTest_reset_sync_inst : SEL_toTest_reset_sync
    PORT MAP( clk_in => IPCORE_CLK,
              reset_in => reset_before_sync,  -- ufix1
              reset_out => reset
              );

  u_SEL_toTest_axi4_stream_adc1_slave_inst : SEL_toTest_axi4_stream_adc1_slave
    PORT MAP( clk => IPCORE_CLK,  -- ufix1
              reset => reset,
              enb => const_1,
              AXI4_Stream_ADC1_Slave_TDATA => AXI4_Stream_ADC1_Slave_TDATA,  -- ufix16
              AXI4_Stream_ADC1_Slave_TVALID => AXI4_Stream_ADC1_Slave_TVALID,  -- ufix1
              AXI4_Stream_ADC1_Slave_TREADY => AXI4_Stream_ADC1_Slave_TREADY,  -- ufix1
              user_data => top_user_data,  -- ufix16
              user_valid => top_user_valid  -- ufix1
              );

  u_SEL_toTest_dut_inst : SEL_toTest_dut
    PORT MAP( clk_1 => IPCORE_CLK,
              reset_1 => reset,
              S_AXIS_ADC1_TDATA => std_logic_vector(S_AXIS_ADC1_TDATA_sig),  -- sfix16
              S_AXIS_ADC1_TVALID => top_user_valid,  -- ufix1
              AXI4_LITE_CONTROL_PHASE_COS => write_AXI4_LITE_CONTROL_PHASE_COS,  -- sfix18_En16
              AXI4_LITE_CONTROL_PHASE_SIN => write_AXI4_LITE_CONTROL_PHASE_SIN,  -- sfix18_En16
              AXI4_LITE_CONTROL_MAG_SET => write_AXI4_LITE_CONTROL_MAG_SET,  -- sfix18_En16
              AXI4_LITE_CONTROL_K_HIGH => write_AXI4_LITE_CONTROL_K_HIGH,  -- sfix18_En16
              AXI4_LITE_CONTROL_K_LOW => write_AXI4_LITE_CONTROL_K_LOW,  -- sfix18_En16
              AXI4_LITE_CONTROL_PULSE_WIDTH => write_AXI4_LITE_CONTROL_PULSE_WIDTH,  -- ufix32
              AXI4_LITE_CONTROL_PULSE_EN => write_AXI4_LITE_CONTROL_PULSE_EN,  -- ufix1
              AXI4_LITE_CONTROL_AUTO_EN => write_AXI4_LITE_CONTROL_AUTO_EN,  -- ufix1
              AXI4_LITE_CONTROL_REP_PERIOD => write_AXI4_LITE_CONTROL_REP_PERIOD,  -- ufix32
              M_AXIS_DAC1_TDATA => M_AXIS_DAC1_TDATA_sig,  -- sfix16
              M_AXIS_DAC1_TVALID => M_AXIS_DAC1_TVALID_sig,  -- ufix1
              M_AXIS_DAC2_TDATA => M_AXIS_DAC2_TDATA_sig,  -- sfix16
              M_AXIS_DAC2_TVALID => M_AXIS_DAC2_TVALID_sig  -- ufix1
              );

  u_SEL_toTest_axi4_stream_dac2_master_inst : SEL_toTest_axi4_stream_dac2_master
    PORT MAP( clk => IPCORE_CLK,  -- ufix1
              reset => reset,
              enb => const_1,
              AXI4_Stream_DAC2_Master_TREADY => AXI4_Stream_DAC2_Master_TREADY,  -- ufix1
              user_data => std_logic_vector(top_user_data_1),  -- ufix16
              user_valid => M_AXIS_DAC2_TVALID_sig,  -- ufix1
              write_packet_size_axi4_stream_dac2_master => write_packet_size_axi4_stream_dac2_master,  -- ufix32
              AXI4_Stream_DAC2_Master_TDATA => AXI4_Stream_DAC2_Master_TDATA_tmp,  -- ufix16
              AXI4_Stream_DAC2_Master_TVALID => AXI4_Stream_DAC2_Master_TVALID,  -- ufix1
              AXI4_Stream_DAC2_Master_TLAST => AXI4_Stream_DAC2_Master_TLAST  -- ufix1
              );

  u_SEL_toTest_axi4_stream_dac1_master_inst : SEL_toTest_axi4_stream_dac1_master
    PORT MAP( clk => IPCORE_CLK,  -- ufix1
              reset => reset,
              enb => const_1,
              AXI4_Stream_DAC1_Master_TREADY => AXI4_Stream_DAC1_Master_TREADY,  -- ufix1
              user_data => std_logic_vector(top_user_data_2),  -- ufix16
              user_valid => M_AXIS_DAC1_TVALID_sig,  -- ufix1
              write_packet_size_axi4_stream_dac1_master => write_packet_size_axi4_stream_dac1_master,  -- ufix32
              AXI4_Stream_DAC1_Master_TDATA => AXI4_Stream_DAC1_Master_TDATA_tmp,  -- ufix16
              AXI4_Stream_DAC1_Master_TVALID => AXI4_Stream_DAC1_Master_TVALID,  -- ufix1
              AXI4_Stream_DAC1_Master_TLAST => AXI4_Stream_DAC1_Master_TLAST  -- ufix1
              );

  const_1 <= '1';

  reset_cm <=  NOT IPCORE_RESETN;

  ip_timestamp <= unsigned'(X"9B67CEBF");

  reset_before_sync <= reset_cm OR reset_internal;

  top_user_data_unsigned <= unsigned(top_user_data);

  S_AXIS_ADC1_TDATA_sig <= signed(top_user_data_unsigned);

  M_AXIS_DAC2_TDATA_sig_signed <= signed(M_AXIS_DAC2_TDATA_sig);

  top_user_data_1 <= unsigned(M_AXIS_DAC2_TDATA_sig_signed);

  AXI4_Stream_DAC2_Master_TDATA <= AXI4_Stream_DAC2_Master_TDATA_tmp;

  M_AXIS_DAC1_TDATA_sig_signed <= signed(M_AXIS_DAC1_TDATA_sig);

  top_user_data_2 <= unsigned(M_AXIS_DAC1_TDATA_sig_signed);

  AXI4_Stream_DAC1_Master_TDATA <= AXI4_Stream_DAC1_Master_TDATA_tmp;

  AXI4_Lite_BRESP <= AXI4_Lite_BRESP_tmp;

  AXI4_Lite_RDATA <= AXI4_Lite_RDATA_tmp;

  AXI4_Lite_RRESP <= AXI4_Lite_RRESP_tmp;

END rtl;

