-- -------------------------------------------------------------
-- 
-- File Name: SEL_Reverted\hdlsrc\SEL_test\SEL_toTest_src_SCALE_FACTOR.vhd
-- Created: 2026-07-27 16:14:58
-- 
-- Generated by MATLAB 26.1, HDL Coder 26.1, and Simulink 26.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: SEL_toTest_src_SCALE_FACTOR
-- Source Path: SEL_test/TESTBENCH/SEL/SEL_WRAPPED/DSP_LOGIC/NORMALIZE/SCALE_FACTOR
-- Hierarchy Level: 4
-- Model version: 1.616
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.SEL_toTest_src_SEL_pkg.ALL;

ENTITY SEL_toTest_src_SCALE_FACTOR IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        In1                               :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En23
        In2                               :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En23
        Out1                              :   OUT   std_logic_vector(17 DOWNTO 0)  -- ufix18_En4
        );
END SEL_toTest_src_SCALE_FACTOR;


ARCHITECTURE rtl OF SEL_toTest_src_SCALE_FACTOR IS

  -- Component Declarations
  COMPONENT SEL_toTest_src_rSqrt
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          S_in                            :   IN    std_logic_vector(36 DOWNTO 0);  -- sfix37_En32
          K                               :   OUT   std_logic_vector(17 DOWNTO 0)  -- ufix18_En4
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : SEL_toTest_src_rSqrt
    USE ENTITY work.SEL_toTest_src_rSqrt(rtl);

  -- Signals
  SIGNAL In1_signed                       : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL Data_Type_Conversion2_out1       : signed(17 DOWNTO 0);  -- sfix18_En16
  SIGNAL Data_Type_Conversion2_out1_1     : signed(17 DOWNTO 0);  -- sfix18_En16
  SIGNAL Product_out1                     : signed(35 DOWNTO 0);  -- sfix36_En32
  SIGNAL Product_out1_1                   : signed(35 DOWNTO 0);  -- sfix36_En32
  SIGNAL rd_0_reg                         : vector_of_signed36(0 TO 1);  -- sfix36 [2]
  SIGNAL Product_out1_2                   : signed(35 DOWNTO 0);  -- sfix36_En32
  SIGNAL In2_signed                       : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL Data_Type_Conversion1_out1       : signed(17 DOWNTO 0);  -- sfix18_En16
  SIGNAL Data_Type_Conversion1_out1_1     : signed(17 DOWNTO 0);  -- sfix18_En16
  SIGNAL Product1_out1                    : signed(35 DOWNTO 0);  -- sfix36_En32
  SIGNAL Product1_out1_1                  : signed(35 DOWNTO 0);  -- sfix36_En32
  SIGNAL Sum_add_cast                     : signed(36 DOWNTO 0);  -- sfix37_En32
  SIGNAL Sum_add_cast_1                   : signed(36 DOWNTO 0);  -- sfix37_En32
  SIGNAL Sum_out1                         : signed(36 DOWNTO 0);  -- sfix37_En32
  SIGNAL rsqrt                            : std_logic_vector(17 DOWNTO 0);  -- ufix18

  ATTRIBUTE use_dsp : string;

  ATTRIBUTE use_dsp OF Product_out1 : SIGNAL IS "yes";
  ATTRIBUTE use_dsp OF Product1_out1 : SIGNAL IS "yes";

BEGIN
  -- S_in = I^2 + Q^2

  u_rSqrt : SEL_toTest_src_rSqrt
    PORT MAP( clk => clk,
              reset => reset,
              S_in => std_logic_vector(Sum_out1),  -- sfix37_En32
              K => rsqrt  -- ufix18_En4
              );

  In1_signed <= signed(In1);

  
  Data_Type_Conversion2_out1 <= "011111111111111111" WHEN (In1_signed(24) = '0') AND (In1_signed(23 DOWNTO 7) = "11111111111111111") ELSE
      In1_signed(24 DOWNTO 7) + ('0' & In1_signed(6));

  reduced_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Data_Type_Conversion2_out1_1 <= to_signed(16#00000#, 18);
      ELSE 
        Data_Type_Conversion2_out1_1 <= Data_Type_Conversion2_out1;
      END IF;
    END IF;
  END PROCESS reduced_process;


  Product_out1 <= Data_Type_Conversion2_out1_1 * Data_Type_Conversion2_out1_1;

  PipelineRegister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Product_out1_1 <= to_signed(0, 36);
      ELSE 
        Product_out1_1 <= Product_out1;
      END IF;
    END IF;
  END PROCESS PipelineRegister_process;


  rd_0_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        rd_0_reg <= (OTHERS => to_signed(0, 36));
      ELSE 
        rd_0_reg(0) <= Product_out1_1;
        rd_0_reg(1) <= rd_0_reg(0);
      END IF;
    END IF;
  END PROCESS rd_0_process;

  Product_out1_2 <= rd_0_reg(1);

  In2_signed <= signed(In2);

  
  Data_Type_Conversion1_out1 <= "011111111111111111" WHEN (In2_signed(24) = '0') AND (In2_signed(23 DOWNTO 7) = "11111111111111111") ELSE
      In2_signed(24 DOWNTO 7) + ('0' & In2_signed(6));

  reduced_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Data_Type_Conversion1_out1_1 <= to_signed(16#00000#, 18);
      ELSE 
        Data_Type_Conversion1_out1_1 <= Data_Type_Conversion1_out1;
      END IF;
    END IF;
  END PROCESS reduced_1_process;


  Product1_out1 <= Data_Type_Conversion1_out1_1 * Data_Type_Conversion1_out1_1;

  PipelineRegister1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Product1_out1_1 <= to_signed(0, 36);
      ELSE 
        Product1_out1_1 <= Product1_out1;
      END IF;
    END IF;
  END PROCESS PipelineRegister1_process;


  Sum_add_cast <= resize(Product_out1_2, 37);
  Sum_add_cast_1 <= resize(Product1_out1_1, 37);
  Sum_out1 <= Sum_add_cast + Sum_add_cast_1;

  Out1 <= rsqrt;

END rtl;

