-- -------------------------------------------------------------
-- 
-- File Name: SEL_Reverted\hdlsrc\SEL_test\SEL_toTest_src_MOVING_AVG.vhd
-- Created: 2026-07-27 16:14:58
-- 
-- Generated by MATLAB 26.1, HDL Coder 26.1, and Simulink 26.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: SEL_toTest_src_MOVING_AVG
-- Source Path: SEL_test/TESTBENCH/SEL/SEL_WRAPPED/DSP_LOGIC/NORMALIZE/SCALE_FACTOR/rSqrt/MOVING_AVG
-- Hierarchy Level: 6
-- Model version: 1.616
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY SEL_toTest_src_MOVING_AVG IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        In1                               :   IN    std_logic_vector(27 DOWNTO 0);  -- ufix28_En27
        S_in                              :   OUT   std_logic_vector(27 DOWNTO 0)  -- ufix28_En27
        );
END SEL_toTest_src_MOVING_AVG;


ARCHITECTURE rtl OF SEL_toTest_src_MOVING_AVG IS

  -- Signals
  SIGNAL In1_unsigned                     : unsigned(27 DOWNTO 0);  -- ufix28_En27
  SIGNAL Unit_Delay_out1                  : unsigned(27 DOWNTO 0);  -- ufix28_En27
  SIGNAL Sum_add_cast                     : unsigned(28 DOWNTO 0);  -- ufix29_En27
  SIGNAL Sum_add_cast_1                   : unsigned(28 DOWNTO 0);  -- ufix29_En27
  SIGNAL Sum_out1                         : unsigned(28 DOWNTO 0);  -- ufix29_En27
  SIGNAL Sum_out1_1                       : unsigned(28 DOWNTO 0);  -- ufix29_En27
  SIGNAL Gain_cast                        : unsigned(57 DOWNTO 0);  -- ufix58_En56
  SIGNAL Gain_out1                        : unsigned(27 DOWNTO 0);  -- ufix28_En27

BEGIN
  In1_unsigned <= unsigned(In1);

  rd_0_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Unit_Delay_out1 <= to_unsigned(16#0000000#, 28);
      ELSE 
        Unit_Delay_out1 <= In1_unsigned;
      END IF;
    END IF;
  END PROCESS rd_0_process;


  Sum_add_cast <= resize(Unit_Delay_out1, 29);
  Sum_add_cast_1 <= resize(In1_unsigned, 29);
  Sum_out1 <= Sum_add_cast + Sum_add_cast_1;

  cd_0_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Sum_out1_1 <= to_unsigned(16#00000000#, 29);
      ELSE 
        Sum_out1_1 <= Sum_out1;
      END IF;
    END IF;
  END PROCESS cd_0_process;


  Gain_cast <= resize(Sum_out1_1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 58);
  
  Gain_out1 <= X"FFFFFFF" WHEN (Gain_cast(57) /= '0') OR (Gain_cast(56 DOWNTO 29) = X"FFFFFFF") ELSE
      Gain_cast(56 DOWNTO 29) + ('0' & Gain_cast(28));

  S_in <= std_logic_vector(Gain_out1);

END rtl;

