-- -------------------------------------------------------------
-- 
-- File Name: SEL_Reverted\hdlsrc\SEL_test\SEL_toTest_src_MUX.vhd
-- Created: 2026-07-27 16:14:58
-- 
-- Generated by MATLAB 26.1, HDL Coder 26.1, and Simulink 26.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: SEL_toTest_src_MUX
-- Source Path: SEL_test/TESTBENCH/SEL/SEL_WRAPPED/DSP_LOGIC/MUX
-- Hierarchy Level: 3
-- Model version: 1.616
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.SEL_toTest_src_SEL_pkg.ALL;

ENTITY SEL_toTest_src_MUX IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        I                                 :   IN    std_logic_vector(25 DOWNTO 0);  -- sfix26_En23
        Q                                 :   IN    std_logic_vector(25 DOWNTO 0);  -- sfix26_En23
        valid                             :   IN    std_logic;
        mix_bus_NSIN_MIX                  :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En23
        mix_bus_COS_MIX                   :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En23
        user_gain_MAG_SET                 :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
        dac_o_TDATA                       :   OUT   std_logic_vector(15 DOWNTO 0);  -- int16
        dac_o_TVALID                      :   OUT   std_logic
        );
END SEL_toTest_src_MUX;


ARCHITECTURE rtl OF SEL_toTest_src_MUX IS

  -- Signals
  SIGNAL TVALID                           : std_logic;
  SIGNAL Q_signed                         : signed(25 DOWNTO 0);  -- sfix26_En23
  SIGNAL Q_1                              : signed(25 DOWNTO 0);  -- sfix26_En23
  SIGNAL Data_Type_Conversion2_out1       : signed(17 DOWNTO 0);  -- sfix18_En16
  SIGNAL Data_Type_Conversion2_out1_1     : signed(17 DOWNTO 0);  -- sfix18_En16
  SIGNAL Data_Type_Conversion2_out1_2     : signed(17 DOWNTO 0);  -- sfix18_En16
  SIGNAL NSIN_MIX                         : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL rd_2_reg                         : vector_of_signed25(0 TO 26);  -- sfix25 [27]
  SIGNAL NSIN_MIX_1                       : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL NSIN_MIX_2                       : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL Product_out1                     : signed(42 DOWNTO 0);  -- sfix43_En39
  SIGNAL Product_out1_1                   : signed(42 DOWNTO 0);  -- sfix43_En39
  SIGNAL Product_out1_2                   : signed(42 DOWNTO 0);  -- sfix43_En39
  SIGNAL COS_MIX                          : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL rd_4_reg                         : vector_of_signed25(0 TO 26);  -- sfix25 [27]
  SIGNAL COS_MIX_1                        : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL COS_MIX_2                        : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL I_signed                         : signed(25 DOWNTO 0);  -- sfix26_En23
  SIGNAL I_1                              : signed(25 DOWNTO 0);  -- sfix26_En23
  SIGNAL Data_Type_Conversion3_out1       : signed(17 DOWNTO 0);  -- sfix18_En16
  SIGNAL Data_Type_Conversion3_out1_1     : signed(17 DOWNTO 0);  -- sfix18_En16
  SIGNAL Data_Type_Conversion3_out1_2     : signed(17 DOWNTO 0);  -- sfix18_En16
  SIGNAL Product1_out1                    : signed(42 DOWNTO 0);  -- sfix43_En39
  SIGNAL Product1_out1_1                  : signed(42 DOWNTO 0);  -- sfix43_En39
  SIGNAL Product1_out1_2                  : signed(42 DOWNTO 0);  -- sfix43_En39
  SIGNAL Sum_add_cast                     : signed(43 DOWNTO 0);  -- sfix44_En39
  SIGNAL Sum_add_cast_1                   : signed(43 DOWNTO 0);  -- sfix44_En39
  SIGNAL Sum_out1                         : signed(43 DOWNTO 0);  -- sfix44_En39
  SIGNAL Sum_out1_1                       : signed(24 DOWNTO 0);  -- sfix25_En22
  SIGNAL Sum_out1_2                       : signed(24 DOWNTO 0);  -- sfix25_En22
  SIGNAL MAG_SET                          : signed(17 DOWNTO 0);  -- sfix18_En16
  SIGNAL rd_8_reg                         : vector_of_signed18(0 TO 26);  -- sfix18 [27]
  SIGNAL MAG_SET_1                        : signed(17 DOWNTO 0);  -- sfix18_En16
  SIGNAL MAG_SET_2                        : signed(17 DOWNTO 0);  -- sfix18_En16
  SIGNAL Product2_out1                    : signed(42 DOWNTO 0);  -- sfix43_En38
  SIGNAL Product2_out1_1                  : signed(42 DOWNTO 0);  -- sfix43_En38
  SIGNAL Data_Type_Conversion_out1        : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL TDATA                            : signed(15 DOWNTO 0);  -- int16
  SIGNAL TVALID_1                         : std_logic;

  ATTRIBUTE use_dsp : string;

  ATTRIBUTE use_dsp OF Product_out1 : SIGNAL IS "yes";
  ATTRIBUTE use_dsp OF Product1_out1 : SIGNAL IS "yes";

BEGIN
  Q_signed <= signed(Q);

  rd_0_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Q_1 <= to_signed(16#0000000#, 26);
      ELSE 
        Q_1 <= Q_signed;
      END IF;
    END IF;
  END PROCESS rd_0_process;


  
  Data_Type_Conversion2_out1 <= "011111111111111111" WHEN ((Q_1(25) = '0') AND (Q_1(24) /= '0')) OR ((Q_1(25) = '0') AND (Q_1(24 DOWNTO 7) = "011111111111111111")) ELSE
      "100000000000000000" WHEN (Q_1(25) = '1') AND (Q_1(24) /= '1') ELSE
      Q_1(24 DOWNTO 7) + ('0' & Q_1(6));

  rd_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Data_Type_Conversion2_out1_1 <= to_signed(16#00000#, 18);
      ELSE 
        Data_Type_Conversion2_out1_1 <= Data_Type_Conversion2_out1;
      END IF;
    END IF;
  END PROCESS rd_1_process;


  HwModeRegister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Data_Type_Conversion2_out1_2 <= to_signed(16#00000#, 18);
      ELSE 
        Data_Type_Conversion2_out1_2 <= Data_Type_Conversion2_out1_1;
      END IF;
    END IF;
  END PROCESS HwModeRegister_process;


  NSIN_MIX <= signed(mix_bus_NSIN_MIX);

  rd_2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        rd_2_reg <= (OTHERS => to_signed(16#0000000#, 25));
      ELSE 
        rd_2_reg(0) <= NSIN_MIX;
        rd_2_reg(1 TO 26) <= rd_2_reg(0 TO 25);
      END IF;
    END IF;
  END PROCESS rd_2_process;

  NSIN_MIX_1 <= rd_2_reg(26);

  HwModeRegister1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        NSIN_MIX_2 <= to_signed(16#0000000#, 25);
      ELSE 
        NSIN_MIX_2 <= NSIN_MIX_1;
      END IF;
    END IF;
  END PROCESS HwModeRegister1_process;


  Product_out1 <= Data_Type_Conversion2_out1_2 * NSIN_MIX_2;

  PipelineRegister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Product_out1_1 <= to_signed(0, 43);
      ELSE 
        Product_out1_1 <= Product_out1;
      END IF;
    END IF;
  END PROCESS PipelineRegister_process;


  rd_3_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Product_out1_2 <= to_signed(0, 43);
      ELSE 
        Product_out1_2 <= Product_out1_1;
      END IF;
    END IF;
  END PROCESS rd_3_process;


  COS_MIX <= signed(mix_bus_COS_MIX);

  rd_4_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        rd_4_reg <= (OTHERS => to_signed(16#0000000#, 25));
      ELSE 
        rd_4_reg(0) <= COS_MIX;
        rd_4_reg(1 TO 26) <= rd_4_reg(0 TO 25);
      END IF;
    END IF;
  END PROCESS rd_4_process;

  COS_MIX_1 <= rd_4_reg(26);

  HwModeRegister2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        COS_MIX_2 <= to_signed(16#0000000#, 25);
      ELSE 
        COS_MIX_2 <= COS_MIX_1;
      END IF;
    END IF;
  END PROCESS HwModeRegister2_process;


  I_signed <= signed(I);

  rd_5_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        I_1 <= to_signed(16#0000000#, 26);
      ELSE 
        I_1 <= I_signed;
      END IF;
    END IF;
  END PROCESS rd_5_process;


  
  Data_Type_Conversion3_out1 <= "011111111111111111" WHEN ((I_1(25) = '0') AND (I_1(24) /= '0')) OR ((I_1(25) = '0') AND (I_1(24 DOWNTO 7) = "011111111111111111")) ELSE
      "100000000000000000" WHEN (I_1(25) = '1') AND (I_1(24) /= '1') ELSE
      I_1(24 DOWNTO 7) + ('0' & I_1(6));

  rd_6_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Data_Type_Conversion3_out1_1 <= to_signed(16#00000#, 18);
      ELSE 
        Data_Type_Conversion3_out1_1 <= Data_Type_Conversion3_out1;
      END IF;
    END IF;
  END PROCESS rd_6_process;


  HwModeRegister3_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Data_Type_Conversion3_out1_2 <= to_signed(16#00000#, 18);
      ELSE 
        Data_Type_Conversion3_out1_2 <= Data_Type_Conversion3_out1_1;
      END IF;
    END IF;
  END PROCESS HwModeRegister3_process;


  Product1_out1 <= COS_MIX_2 * Data_Type_Conversion3_out1_2;

  PipelineRegister1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Product1_out1_1 <= to_signed(0, 43);
      ELSE 
        Product1_out1_1 <= Product1_out1;
      END IF;
    END IF;
  END PROCESS PipelineRegister1_process;


  rd_7_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Product1_out1_2 <= to_signed(0, 43);
      ELSE 
        Product1_out1_2 <= Product1_out1_1;
      END IF;
    END IF;
  END PROCESS rd_7_process;


  Sum_add_cast <= resize(Product_out1_2, 44);
  Sum_add_cast_1 <= resize(Product1_out1_2, 44);
  Sum_out1 <= Sum_add_cast + Sum_add_cast_1;

  
  Sum_out1_1 <= "0111111111111111111111111" WHEN ((Sum_out1(43) = '0') AND (Sum_out1(42 DOWNTO 41) /= "00")) OR ((Sum_out1(43) = '0') AND (Sum_out1(41 DOWNTO 17) = "0111111111111111111111111")) ELSE
      "1000000000000000000000000" WHEN (Sum_out1(43) = '1') AND (Sum_out1(42 DOWNTO 41) /= "11") ELSE
      Sum_out1(41 DOWNTO 17) + ('0' & Sum_out1(16));

  HwModeRegister4_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Sum_out1_2 <= to_signed(16#0000000#, 25);
      ELSE 
        Sum_out1_2 <= Sum_out1_1;
      END IF;
    END IF;
  END PROCESS HwModeRegister4_process;


  MAG_SET <= signed(user_gain_MAG_SET);

  rd_8_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        rd_8_reg <= (OTHERS => to_signed(16#00000#, 18));
      ELSE 
        rd_8_reg(0) <= MAG_SET;
        rd_8_reg(1 TO 26) <= rd_8_reg(0 TO 25);
      END IF;
    END IF;
  END PROCESS rd_8_process;

  MAG_SET_1 <= rd_8_reg(26);

  HwModeRegister5_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        MAG_SET_2 <= to_signed(16#00000#, 18);
      ELSE 
        MAG_SET_2 <= MAG_SET_1;
      END IF;
    END IF;
  END PROCESS HwModeRegister5_process;


  Product2_out1 <= Sum_out1_2 * MAG_SET_2;

  PipelineRegister2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Product2_out1_1 <= to_signed(0, 43);
      ELSE 
        Product2_out1_1 <= Product2_out1;
      END IF;
    END IF;
  END PROCESS PipelineRegister2_process;


  
  Data_Type_Conversion_out1 <= X"7FFF" WHEN ((Product2_out1_1(42) = '0') AND (Product2_out1_1(41 DOWNTO 38) /= "0000")) OR ((Product2_out1_1(42) = '0') AND (Product2_out1_1(38 DOWNTO 23) = X"7FFF")) ELSE
      X"8000" WHEN (Product2_out1_1(42) = '1') AND (Product2_out1_1(41 DOWNTO 38) /= "1111") ELSE
      Product2_out1_1(38 DOWNTO 23) + ('0' & Product2_out1_1(22));

  TDATA <= Data_Type_Conversion_out1;

  dac_o_TDATA <= std_logic_vector(TDATA);

  TVALID <= valid;

  rd_9_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        TVALID_1 <= '0';
      ELSE 
        TVALID_1 <= TVALID;
      END IF;
    END IF;
  END PROCESS rd_9_process;


  dac_o_TVALID <= TVALID_1;

END rtl;

